// Generated by CIRCT firtool-1.135.0
module AheadBtbBank(	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:28:7
  input          clock,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:28:7
                 reset,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:28:7
                 io_readReq_valid,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  input  [4:0]   io_readReq_bits_setIdx,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output         io_readResp_entries_0_valid,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [23:0]  io_readResp_entries_0_tag,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [3:0]   io_readResp_entries_0_position,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [1:0]   io_readResp_entries_0_attribute_branchType,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
                 io_readResp_entries_0_attribute_rasAction,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [21:0]  io_readResp_entries_0_targetLowerBits,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output         io_readResp_entries_1_valid,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [23:0]  io_readResp_entries_1_tag,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [3:0]   io_readResp_entries_1_position,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [1:0]   io_readResp_entries_1_attribute_branchType,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
                 io_readResp_entries_1_attribute_rasAction,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [21:0]  io_readResp_entries_1_targetLowerBits,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output         io_readResp_entries_2_valid,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [23:0]  io_readResp_entries_2_tag,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [3:0]   io_readResp_entries_2_position,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [1:0]   io_readResp_entries_2_attribute_branchType,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
                 io_readResp_entries_2_attribute_rasAction,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [21:0]  io_readResp_entries_2_targetLowerBits,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output         io_readResp_entries_3_valid,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [23:0]  io_readResp_entries_3_tag,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [3:0]   io_readResp_entries_3_position,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [1:0]   io_readResp_entries_3_attribute_branchType,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
                 io_readResp_entries_3_attribute_rasAction,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [21:0]  io_readResp_entries_3_targetLowerBits,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output         io_readResp_entries_4_valid,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [23:0]  io_readResp_entries_4_tag,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [3:0]   io_readResp_entries_4_position,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [1:0]   io_readResp_entries_4_attribute_branchType,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
                 io_readResp_entries_4_attribute_rasAction,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [21:0]  io_readResp_entries_4_targetLowerBits,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output         io_readResp_entries_5_valid,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [23:0]  io_readResp_entries_5_tag,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [3:0]   io_readResp_entries_5_position,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [1:0]   io_readResp_entries_5_attribute_branchType,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
                 io_readResp_entries_5_attribute_rasAction,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [21:0]  io_readResp_entries_5_targetLowerBits,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output         io_readResp_entries_6_valid,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [23:0]  io_readResp_entries_6_tag,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [3:0]   io_readResp_entries_6_position,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [1:0]   io_readResp_entries_6_attribute_branchType,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
                 io_readResp_entries_6_attribute_rasAction,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [21:0]  io_readResp_entries_6_targetLowerBits,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output         io_readResp_entries_7_valid,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [23:0]  io_readResp_entries_7_tag,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [3:0]   io_readResp_entries_7_position,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [1:0]   io_readResp_entries_7_attribute_branchType,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
                 io_readResp_entries_7_attribute_rasAction,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [21:0]  io_readResp_entries_7_targetLowerBits,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  input          io_writeReq_valid,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
                 io_writeReq_bits_needResetCtr,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  input  [4:0]   io_writeReq_bits_setIdx,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  input  [2:0]   io_writeReq_bits_wayIdx,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  input          io_writeReq_bits_entry_valid,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  input  [23:0]  io_writeReq_bits_entry_tag,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  input  [3:0]   io_writeReq_bits_entry_position,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  input  [1:0]   io_writeReq_bits_entry_attribute_branchType,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
                 io_writeReq_bits_entry_attribute_rasAction,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  input  [21:0]  io_writeReq_bits_entry_targetLowerBits,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output         io_writeResp_valid,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
                 io_writeResp_bits_needResetCtr,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [4:0]   io_writeResp_bits_setIdx,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output [2:0]   io_writeResp_bits_wayIdx,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  output         io_sramResetDone,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:37:22
  input  [5:0]   boreChildrenBd_bore_addr,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
                 boreChildrenBd_bore_addr_rd,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  input  [109:0] boreChildrenBd_bore_wdata,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  input  [1:0]   boreChildrenBd_bore_wmask,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  input          boreChildrenBd_bore_re,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
                 boreChildrenBd_bore_we,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  output [109:0] boreChildrenBd_bore_rdata,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  input          boreChildrenBd_bore_ack,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
                 boreChildrenBd_bore_selectedOH,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  input  [5:0]   boreChildrenBd_bore_array,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
                 boreChildrenBd_bore_1_addr,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
                 boreChildrenBd_bore_1_addr_rd,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  input  [109:0] boreChildrenBd_bore_1_wdata,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  input  [1:0]   boreChildrenBd_bore_1_wmask,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  input          boreChildrenBd_bore_1_re,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
                 boreChildrenBd_bore_1_we,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  output [109:0] boreChildrenBd_bore_1_rdata,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  input          boreChildrenBd_bore_1_ack,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
                 boreChildrenBd_bore_1_selectedOH,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  input  [5:0]   boreChildrenBd_bore_1_array,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
                 boreChildrenBd_bore_2_addr,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
                 boreChildrenBd_bore_2_addr_rd,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  input  [109:0] boreChildrenBd_bore_2_wdata,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  input  [1:0]   boreChildrenBd_bore_2_wmask,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  input          boreChildrenBd_bore_2_re,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
                 boreChildrenBd_bore_2_we,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  output [109:0] boreChildrenBd_bore_2_rdata,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  input          boreChildrenBd_bore_2_ack,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
                 boreChildrenBd_bore_2_selectedOH,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  input  [5:0]   boreChildrenBd_bore_2_array,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
                 boreChildrenBd_bore_3_addr,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
                 boreChildrenBd_bore_3_addr_rd,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  input  [109:0] boreChildrenBd_bore_3_wdata,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  input  [1:0]   boreChildrenBd_bore_3_wmask,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  input          boreChildrenBd_bore_3_re,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
                 boreChildrenBd_bore_3_we,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  output [109:0] boreChildrenBd_bore_3_rdata,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  input          boreChildrenBd_bore_3_ack,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
                 boreChildrenBd_bore_3_selectedOH,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  input  [5:0]   boreChildrenBd_bore_3_array,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/Mbist.scala:116:46
  input          sigFromSrams_bore_ram_hold,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_ram_bypass,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_ram_bp_clken,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_ram_aux_clk,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_ram_aux_ckbp,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_ram_mcp_hold,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_cgen,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_1_ram_hold,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_1_ram_bypass,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_1_ram_bp_clken,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_1_ram_aux_clk,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_1_ram_aux_ckbp,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_1_ram_mcp_hold,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_1_cgen,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_2_ram_hold,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_2_ram_bypass,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_2_ram_bp_clken,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_2_ram_aux_clk,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_2_ram_aux_ckbp,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_2_ram_mcp_hold,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_2_cgen,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_3_ram_hold,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_3_ram_bypass,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_3_ram_bp_clken,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_3_ram_aux_clk,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_3_ram_aux_ckbp,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_3_ram_mcp_hold,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
                 sigFromSrams_bore_3_cgen	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/sram/SramHelper.scala:122:23
);

  wire        _writeBuffer_io_read_0_valid;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
  wire [4:0]  _writeBuffer_io_read_0_bits_setIdx;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
  wire [2:0]  _writeBuffer_io_read_0_bits_wayIdx;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
  wire        _writeBuffer_io_read_0_bits_entry_valid;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
  wire [23:0] _writeBuffer_io_read_0_bits_entry_tag;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
  wire [3:0]  _writeBuffer_io_read_0_bits_entry_position;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
  wire [1:0]  _writeBuffer_io_read_0_bits_entry_attribute_branchType;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
  wire [1:0]  _writeBuffer_io_read_0_bits_entry_attribute_rasAction;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
  wire [21:0] _writeBuffer_io_read_0_bits_entry_targetLowerBits;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
  wire        _sram_io_w_req_ready;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:39:28
  wire        writeBuffer_io_read_0_ready = _sram_io_w_req_ready & ~io_readReq_valid;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:39:28, :85:{57,60}
  SplittedSRAMTemplate_2 sram (	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:39:28
    .clock                                     (clock),
    .reset                                     (reset),
    .io_r_req_valid                            (io_readReq_valid),
    .io_r_req_bits_setIdx                      (io_readReq_bits_setIdx),
    .io_r_resp_data_0_valid                    (io_readResp_entries_0_valid),
    .io_r_resp_data_0_tag                      (io_readResp_entries_0_tag),
    .io_r_resp_data_0_position                 (io_readResp_entries_0_position),
    .io_r_resp_data_0_attribute_branchType     (io_readResp_entries_0_attribute_branchType),
    .io_r_resp_data_0_attribute_rasAction      (io_readResp_entries_0_attribute_rasAction),
    .io_r_resp_data_0_targetLowerBits          (io_readResp_entries_0_targetLowerBits),
    .io_r_resp_data_1_valid                    (io_readResp_entries_1_valid),
    .io_r_resp_data_1_tag                      (io_readResp_entries_1_tag),
    .io_r_resp_data_1_position                 (io_readResp_entries_1_position),
    .io_r_resp_data_1_attribute_branchType     (io_readResp_entries_1_attribute_branchType),
    .io_r_resp_data_1_attribute_rasAction      (io_readResp_entries_1_attribute_rasAction),
    .io_r_resp_data_1_targetLowerBits          (io_readResp_entries_1_targetLowerBits),
    .io_r_resp_data_2_valid                    (io_readResp_entries_2_valid),
    .io_r_resp_data_2_tag                      (io_readResp_entries_2_tag),
    .io_r_resp_data_2_position                 (io_readResp_entries_2_position),
    .io_r_resp_data_2_attribute_branchType     (io_readResp_entries_2_attribute_branchType),
    .io_r_resp_data_2_attribute_rasAction      (io_readResp_entries_2_attribute_rasAction),
    .io_r_resp_data_2_targetLowerBits          (io_readResp_entries_2_targetLowerBits),
    .io_r_resp_data_3_valid                    (io_readResp_entries_3_valid),
    .io_r_resp_data_3_tag                      (io_readResp_entries_3_tag),
    .io_r_resp_data_3_position                 (io_readResp_entries_3_position),
    .io_r_resp_data_3_attribute_branchType     (io_readResp_entries_3_attribute_branchType),
    .io_r_resp_data_3_attribute_rasAction      (io_readResp_entries_3_attribute_rasAction),
    .io_r_resp_data_3_targetLowerBits          (io_readResp_entries_3_targetLowerBits),
    .io_r_resp_data_4_valid                    (io_readResp_entries_4_valid),
    .io_r_resp_data_4_tag                      (io_readResp_entries_4_tag),
    .io_r_resp_data_4_position                 (io_readResp_entries_4_position),
    .io_r_resp_data_4_attribute_branchType     (io_readResp_entries_4_attribute_branchType),
    .io_r_resp_data_4_attribute_rasAction      (io_readResp_entries_4_attribute_rasAction),
    .io_r_resp_data_4_targetLowerBits          (io_readResp_entries_4_targetLowerBits),
    .io_r_resp_data_5_valid                    (io_readResp_entries_5_valid),
    .io_r_resp_data_5_tag                      (io_readResp_entries_5_tag),
    .io_r_resp_data_5_position                 (io_readResp_entries_5_position),
    .io_r_resp_data_5_attribute_branchType     (io_readResp_entries_5_attribute_branchType),
    .io_r_resp_data_5_attribute_rasAction      (io_readResp_entries_5_attribute_rasAction),
    .io_r_resp_data_5_targetLowerBits          (io_readResp_entries_5_targetLowerBits),
    .io_r_resp_data_6_valid                    (io_readResp_entries_6_valid),
    .io_r_resp_data_6_tag                      (io_readResp_entries_6_tag),
    .io_r_resp_data_6_position                 (io_readResp_entries_6_position),
    .io_r_resp_data_6_attribute_branchType     (io_readResp_entries_6_attribute_branchType),
    .io_r_resp_data_6_attribute_rasAction      (io_readResp_entries_6_attribute_rasAction),
    .io_r_resp_data_6_targetLowerBits          (io_readResp_entries_6_targetLowerBits),
    .io_r_resp_data_7_valid                    (io_readResp_entries_7_valid),
    .io_r_resp_data_7_tag                      (io_readResp_entries_7_tag),
    .io_r_resp_data_7_position                 (io_readResp_entries_7_position),
    .io_r_resp_data_7_attribute_branchType     (io_readResp_entries_7_attribute_branchType),
    .io_r_resp_data_7_attribute_rasAction      (io_readResp_entries_7_attribute_rasAction),
    .io_r_resp_data_7_targetLowerBits          (io_readResp_entries_7_targetLowerBits),
    .io_w_req_ready                            (_sram_io_w_req_ready),
    .io_w_req_valid                            (_writeBuffer_io_read_0_valid & ~io_readReq_valid),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35, :85:60, :87:61
    .io_w_req_bits_setIdx                      (_writeBuffer_io_read_0_bits_setIdx),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_0_valid                (_writeBuffer_io_read_0_bits_entry_valid),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_0_tag                  (_writeBuffer_io_read_0_bits_entry_tag),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_0_position             (_writeBuffer_io_read_0_bits_entry_position),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_0_attribute_branchType (_writeBuffer_io_read_0_bits_entry_attribute_branchType),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_0_attribute_rasAction  (_writeBuffer_io_read_0_bits_entry_attribute_rasAction),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_0_targetLowerBits      (_writeBuffer_io_read_0_bits_entry_targetLowerBits),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_1_valid                (_writeBuffer_io_read_0_bits_entry_valid),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_1_tag                  (_writeBuffer_io_read_0_bits_entry_tag),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_1_position             (_writeBuffer_io_read_0_bits_entry_position),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_1_attribute_branchType (_writeBuffer_io_read_0_bits_entry_attribute_branchType),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_1_attribute_rasAction  (_writeBuffer_io_read_0_bits_entry_attribute_rasAction),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_1_targetLowerBits      (_writeBuffer_io_read_0_bits_entry_targetLowerBits),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_2_valid                (_writeBuffer_io_read_0_bits_entry_valid),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_2_tag                  (_writeBuffer_io_read_0_bits_entry_tag),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_2_position             (_writeBuffer_io_read_0_bits_entry_position),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_2_attribute_branchType (_writeBuffer_io_read_0_bits_entry_attribute_branchType),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_2_attribute_rasAction  (_writeBuffer_io_read_0_bits_entry_attribute_rasAction),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_2_targetLowerBits      (_writeBuffer_io_read_0_bits_entry_targetLowerBits),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_3_valid                (_writeBuffer_io_read_0_bits_entry_valid),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_3_tag                  (_writeBuffer_io_read_0_bits_entry_tag),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_3_position             (_writeBuffer_io_read_0_bits_entry_position),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_3_attribute_branchType (_writeBuffer_io_read_0_bits_entry_attribute_branchType),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_3_attribute_rasAction  (_writeBuffer_io_read_0_bits_entry_attribute_rasAction),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_3_targetLowerBits      (_writeBuffer_io_read_0_bits_entry_targetLowerBits),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_4_valid                (_writeBuffer_io_read_0_bits_entry_valid),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_4_tag                  (_writeBuffer_io_read_0_bits_entry_tag),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_4_position             (_writeBuffer_io_read_0_bits_entry_position),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_4_attribute_branchType (_writeBuffer_io_read_0_bits_entry_attribute_branchType),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_4_attribute_rasAction  (_writeBuffer_io_read_0_bits_entry_attribute_rasAction),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_4_targetLowerBits      (_writeBuffer_io_read_0_bits_entry_targetLowerBits),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_5_valid                (_writeBuffer_io_read_0_bits_entry_valid),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_5_tag                  (_writeBuffer_io_read_0_bits_entry_tag),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_5_position             (_writeBuffer_io_read_0_bits_entry_position),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_5_attribute_branchType (_writeBuffer_io_read_0_bits_entry_attribute_branchType),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_5_attribute_rasAction  (_writeBuffer_io_read_0_bits_entry_attribute_rasAction),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_5_targetLowerBits      (_writeBuffer_io_read_0_bits_entry_targetLowerBits),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_6_valid                (_writeBuffer_io_read_0_bits_entry_valid),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_6_tag                  (_writeBuffer_io_read_0_bits_entry_tag),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_6_position             (_writeBuffer_io_read_0_bits_entry_position),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_6_attribute_branchType (_writeBuffer_io_read_0_bits_entry_attribute_branchType),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_6_attribute_rasAction  (_writeBuffer_io_read_0_bits_entry_attribute_rasAction),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_6_targetLowerBits      (_writeBuffer_io_read_0_bits_entry_targetLowerBits),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_7_valid                (_writeBuffer_io_read_0_bits_entry_valid),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_7_tag                  (_writeBuffer_io_read_0_bits_entry_tag),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_7_position             (_writeBuffer_io_read_0_bits_entry_position),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_7_attribute_branchType (_writeBuffer_io_read_0_bits_entry_attribute_branchType),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_7_attribute_rasAction  (_writeBuffer_io_read_0_bits_entry_attribute_rasAction),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_data_7_targetLowerBits      (_writeBuffer_io_read_0_bits_entry_targetLowerBits),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .io_w_req_bits_waymask                     (8'h1 << _writeBuffer_io_read_0_bits_wayIdx),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_resetDone                              (io_sramResetDone),
    .boreChildrenBd_bore_addr                  (boreChildrenBd_bore_addr),
    .boreChildrenBd_bore_addr_rd               (boreChildrenBd_bore_addr_rd),
    .boreChildrenBd_bore_wdata                 (boreChildrenBd_bore_wdata),
    .boreChildrenBd_bore_wmask                 (boreChildrenBd_bore_wmask),
    .boreChildrenBd_bore_re                    (boreChildrenBd_bore_re),
    .boreChildrenBd_bore_we                    (boreChildrenBd_bore_we),
    .boreChildrenBd_bore_rdata                 (boreChildrenBd_bore_rdata),
    .boreChildrenBd_bore_ack                   (boreChildrenBd_bore_ack),
    .boreChildrenBd_bore_selectedOH            (boreChildrenBd_bore_selectedOH),
    .boreChildrenBd_bore_array                 (boreChildrenBd_bore_array),
    .boreChildrenBd_bore_1_addr                (boreChildrenBd_bore_1_addr),
    .boreChildrenBd_bore_1_addr_rd             (boreChildrenBd_bore_1_addr_rd),
    .boreChildrenBd_bore_1_wdata               (boreChildrenBd_bore_1_wdata),
    .boreChildrenBd_bore_1_wmask               (boreChildrenBd_bore_1_wmask),
    .boreChildrenBd_bore_1_re                  (boreChildrenBd_bore_1_re),
    .boreChildrenBd_bore_1_we                  (boreChildrenBd_bore_1_we),
    .boreChildrenBd_bore_1_rdata               (boreChildrenBd_bore_1_rdata),
    .boreChildrenBd_bore_1_ack                 (boreChildrenBd_bore_1_ack),
    .boreChildrenBd_bore_1_selectedOH          (boreChildrenBd_bore_1_selectedOH),
    .boreChildrenBd_bore_1_array               (boreChildrenBd_bore_1_array),
    .boreChildrenBd_bore_2_addr                (boreChildrenBd_bore_2_addr),
    .boreChildrenBd_bore_2_addr_rd             (boreChildrenBd_bore_2_addr_rd),
    .boreChildrenBd_bore_2_wdata               (boreChildrenBd_bore_2_wdata),
    .boreChildrenBd_bore_2_wmask               (boreChildrenBd_bore_2_wmask),
    .boreChildrenBd_bore_2_re                  (boreChildrenBd_bore_2_re),
    .boreChildrenBd_bore_2_we                  (boreChildrenBd_bore_2_we),
    .boreChildrenBd_bore_2_rdata               (boreChildrenBd_bore_2_rdata),
    .boreChildrenBd_bore_2_ack                 (boreChildrenBd_bore_2_ack),
    .boreChildrenBd_bore_2_selectedOH          (boreChildrenBd_bore_2_selectedOH),
    .boreChildrenBd_bore_2_array               (boreChildrenBd_bore_2_array),
    .boreChildrenBd_bore_3_addr                (boreChildrenBd_bore_3_addr),
    .boreChildrenBd_bore_3_addr_rd             (boreChildrenBd_bore_3_addr_rd),
    .boreChildrenBd_bore_3_wdata               (boreChildrenBd_bore_3_wdata),
    .boreChildrenBd_bore_3_wmask               (boreChildrenBd_bore_3_wmask),
    .boreChildrenBd_bore_3_re                  (boreChildrenBd_bore_3_re),
    .boreChildrenBd_bore_3_we                  (boreChildrenBd_bore_3_we),
    .boreChildrenBd_bore_3_rdata               (boreChildrenBd_bore_3_rdata),
    .boreChildrenBd_bore_3_ack                 (boreChildrenBd_bore_3_ack),
    .boreChildrenBd_bore_3_selectedOH          (boreChildrenBd_bore_3_selectedOH),
    .boreChildrenBd_bore_3_array               (boreChildrenBd_bore_3_array),
    .sigFromSrams_bore_ram_hold                (sigFromSrams_bore_ram_hold),
    .sigFromSrams_bore_ram_bypass              (sigFromSrams_bore_ram_bypass),
    .sigFromSrams_bore_ram_bp_clken            (sigFromSrams_bore_ram_bp_clken),
    .sigFromSrams_bore_ram_aux_clk             (sigFromSrams_bore_ram_aux_clk),
    .sigFromSrams_bore_ram_aux_ckbp            (sigFromSrams_bore_ram_aux_ckbp),
    .sigFromSrams_bore_ram_mcp_hold            (sigFromSrams_bore_ram_mcp_hold),
    .sigFromSrams_bore_cgen                    (sigFromSrams_bore_cgen),
    .sigFromSrams_bore_1_ram_hold              (sigFromSrams_bore_1_ram_hold),
    .sigFromSrams_bore_1_ram_bypass            (sigFromSrams_bore_1_ram_bypass),
    .sigFromSrams_bore_1_ram_bp_clken          (sigFromSrams_bore_1_ram_bp_clken),
    .sigFromSrams_bore_1_ram_aux_clk           (sigFromSrams_bore_1_ram_aux_clk),
    .sigFromSrams_bore_1_ram_aux_ckbp          (sigFromSrams_bore_1_ram_aux_ckbp),
    .sigFromSrams_bore_1_ram_mcp_hold          (sigFromSrams_bore_1_ram_mcp_hold),
    .sigFromSrams_bore_1_cgen                  (sigFromSrams_bore_1_cgen),
    .sigFromSrams_bore_2_ram_hold              (sigFromSrams_bore_2_ram_hold),
    .sigFromSrams_bore_2_ram_bypass            (sigFromSrams_bore_2_ram_bypass),
    .sigFromSrams_bore_2_ram_bp_clken          (sigFromSrams_bore_2_ram_bp_clken),
    .sigFromSrams_bore_2_ram_aux_clk           (sigFromSrams_bore_2_ram_aux_clk),
    .sigFromSrams_bore_2_ram_aux_ckbp          (sigFromSrams_bore_2_ram_aux_ckbp),
    .sigFromSrams_bore_2_ram_mcp_hold          (sigFromSrams_bore_2_ram_mcp_hold),
    .sigFromSrams_bore_2_cgen                  (sigFromSrams_bore_2_cgen),
    .sigFromSrams_bore_3_ram_hold              (sigFromSrams_bore_3_ram_hold),
    .sigFromSrams_bore_3_ram_bypass            (sigFromSrams_bore_3_ram_bypass),
    .sigFromSrams_bore_3_ram_bp_clken          (sigFromSrams_bore_3_ram_bp_clken),
    .sigFromSrams_bore_3_ram_aux_clk           (sigFromSrams_bore_3_ram_aux_clk),
    .sigFromSrams_bore_3_ram_aux_ckbp          (sigFromSrams_bore_3_ram_aux_ckbp),
    .sigFromSrams_bore_3_ram_mcp_hold          (sigFromSrams_bore_3_ram_mcp_hold),
    .sigFromSrams_bore_3_cgen                  (sigFromSrams_bore_3_cgen)
  );	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:39:28
  WriteBuffer writeBuffer (	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
    .clock                                      (clock),
    .reset                                      (reset),
    .io_write_0_valid                           (io_writeReq_valid),
    .io_write_0_bits_needResetCtr               (io_writeReq_bits_needResetCtr),
    .io_write_0_bits_setIdx                     (io_writeReq_bits_setIdx),
    .io_write_0_bits_wayIdx                     (io_writeReq_bits_wayIdx),
    .io_write_0_bits_entry_valid                (io_writeReq_bits_entry_valid),
    .io_write_0_bits_entry_tag                  (io_writeReq_bits_entry_tag),
    .io_write_0_bits_entry_position             (io_writeReq_bits_entry_position),
    .io_write_0_bits_entry_attribute_branchType (io_writeReq_bits_entry_attribute_branchType),
    .io_write_0_bits_entry_attribute_rasAction  (io_writeReq_bits_entry_attribute_rasAction),
    .io_write_0_bits_entry_targetLowerBits      (io_writeReq_bits_entry_targetLowerBits),
    .io_read_0_ready                            (writeBuffer_io_read_0_ready),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:85:57
    .io_read_0_valid                            (_writeBuffer_io_read_0_valid),
    .io_read_0_bits_needResetCtr                (io_writeResp_bits_needResetCtr),
    .io_read_0_bits_setIdx                      (_writeBuffer_io_read_0_bits_setIdx),
    .io_read_0_bits_wayIdx                      (_writeBuffer_io_read_0_bits_wayIdx),
    .io_read_0_bits_entry_valid                 (_writeBuffer_io_read_0_bits_entry_valid),
    .io_read_0_bits_entry_tag                   (_writeBuffer_io_read_0_bits_entry_tag),
    .io_read_0_bits_entry_position              (_writeBuffer_io_read_0_bits_entry_position),
    .io_read_0_bits_entry_attribute_branchType  (_writeBuffer_io_read_0_bits_entry_attribute_branchType),
    .io_read_0_bits_entry_attribute_rasAction   (_writeBuffer_io_read_0_bits_entry_attribute_rasAction),
    .io_read_0_bits_entry_targetLowerBits       (_writeBuffer_io_read_0_bits_entry_targetLowerBits)
  );	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:74:35
  assign io_writeResp_valid = writeBuffer_io_read_0_ready & _writeBuffer_io_read_0_valid;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:28:7, :74:35, :85:57, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  assign io_writeResp_bits_setIdx = _writeBuffer_io_read_0_bits_setIdx;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:28:7, :74:35
  assign io_writeResp_bits_wayIdx = _writeBuffer_io_read_0_bits_wayIdx;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/abtb/AheadBtbBank.scala:28:7, :74:35
endmodule

