// Generated by CIRCT firtool-1.135.0
module Arbiter2_L2TLBImp_Anon(	// src/main/scala/chisel3/util/Arbiter.scala:149:7
  output        io_in_0_ready,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input         io_in_0_valid,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [1:0]  io_in_0_bits_source,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [37:0] io_in_0_bits_gvpn,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output        io_in_1_ready,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input         io_in_1_valid,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [2:0]  io_in_1_bits_id,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [1:0]  io_in_1_bits_source,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [37:0] io_in_1_bits_gvpn,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input         io_out_ready,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output        io_out_valid,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output [2:0]  io_out_bits_id,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output [1:0]  io_out_bits_source,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output [37:0] io_out_bits_gvpn	// src/main/scala/chisel3/util/Arbiter.scala:156:14
);

  assign io_in_0_ready = io_out_ready;	// src/main/scala/chisel3/util/Arbiter.scala:149:7
  assign io_in_1_ready = ~io_in_0_valid & io_out_ready;	// src/main/scala/chisel3/util/Arbiter.scala:45:78, :149:7, :169:19
  assign io_out_valid = io_in_0_valid | io_in_1_valid;	// src/main/scala/chisel3/util/Arbiter.scala:149:7, :170:31
  assign io_out_bits_id = io_in_0_valid ? 3'h6 : io_in_1_bits_id;	// src/main/scala/chisel3/util/Arbiter.scala:149:7, :156:14, :159:15, :161:26, :163:19
  assign io_out_bits_source = io_in_0_valid ? io_in_0_bits_source : io_in_1_bits_source;	// src/main/scala/chisel3/util/Arbiter.scala:149:7, :159:15, :161:26, :163:19
  assign io_out_bits_gvpn = io_in_0_valid ? io_in_0_bits_gvpn : io_in_1_bits_gvpn;	// src/main/scala/chisel3/util/Arbiter.scala:149:7, :159:15, :161:26, :163:19
endmodule

