// Generated by CIRCT firtool-1.135.0
module Arbiter1_L1BankedDataWriteReq_reference(	// src/main/scala/chisel3/util/Arbiter.scala:149:7
  input         io_in_0_valid,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [7:0]  io_in_0_bits_wmask,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  input  [63:0] io_in_0_bits_data_0,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
                io_in_0_bits_data_1,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
                io_in_0_bits_data_2,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
                io_in_0_bits_data_3,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
                io_in_0_bits_data_4,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
                io_in_0_bits_data_5,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
                io_in_0_bits_data_6,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
                io_in_0_bits_data_7,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output        io_out_valid,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output [7:0]  io_out_bits_wmask,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
  output [63:0] io_out_bits_data_0,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
                io_out_bits_data_1,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
                io_out_bits_data_2,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
                io_out_bits_data_3,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
                io_out_bits_data_4,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
                io_out_bits_data_5,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
                io_out_bits_data_6,	// src/main/scala/chisel3/util/Arbiter.scala:156:14
                io_out_bits_data_7	// src/main/scala/chisel3/util/Arbiter.scala:156:14
);

  assign io_out_valid = io_in_0_valid;	// src/main/scala/chisel3/util/Arbiter.scala:149:7
  assign io_out_bits_wmask = io_in_0_bits_wmask;	// src/main/scala/chisel3/util/Arbiter.scala:149:7
  assign io_out_bits_data_0 = io_in_0_bits_data_0;	// src/main/scala/chisel3/util/Arbiter.scala:149:7
  assign io_out_bits_data_1 = io_in_0_bits_data_1;	// src/main/scala/chisel3/util/Arbiter.scala:149:7
  assign io_out_bits_data_2 = io_in_0_bits_data_2;	// src/main/scala/chisel3/util/Arbiter.scala:149:7
  assign io_out_bits_data_3 = io_in_0_bits_data_3;	// src/main/scala/chisel3/util/Arbiter.scala:149:7
  assign io_out_bits_data_4 = io_in_0_bits_data_4;	// src/main/scala/chisel3/util/Arbiter.scala:149:7
  assign io_out_bits_data_5 = io_in_0_bits_data_5;	// src/main/scala/chisel3/util/Arbiter.scala:149:7
  assign io_out_bits_data_6 = io_in_0_bits_data_6;	// src/main/scala/chisel3/util/Arbiter.scala:149:7
  assign io_out_bits_data_7 = io_in_0_bits_data_7;	// src/main/scala/chisel3/util/Arbiter.scala:149:7
endmodule

