// Generated by CIRCT firtool-1.135.0
module ClockMux_reference(	// home/davide/gitdir/bianco_ci/bianco/XiangShan/utility/src/main/scala/utility/ClockMux.scala:21:7
  input  clk0,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/utility/src/main/scala/utility/ClockMux.scala:22:18
         clk1,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/utility/src/main/scala/utility/ClockMux.scala:23:18
         sel,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/utility/src/main/scala/utility/ClockMux.scala:24:18
  output clkout	// home/davide/gitdir/bianco_ci/bianco/XiangShan/utility/src/main/scala/utility/ClockMux.scala:25:18
);

  assign clkout = sel ? clk1 : clk0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/utility/src/main/scala/utility/ClockMux.scala:21:7, :27:16
endmodule

