// Generated by CIRCT firtool-1.135.0
module ClosePathAdderF16Pipeline_reference(	// home/davide/gitdir/bianco_ci/bianco/XiangShan/yunsuan/src/main/scala/yunsuan/vector/VectorFloatAdder.scala:2201:7
  input  [10:0] io_adder_op0,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/yunsuan/src/main/scala/yunsuan/vector/VectorFloatAdder.scala:2202:14
                io_adder_op1,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/yunsuan/src/main/scala/yunsuan/vector/VectorFloatAdder.scala:2202:14
  output [11:0] io_result	// home/davide/gitdir/bianco_ci/bianco/XiangShan/yunsuan/src/main/scala/yunsuan/vector/VectorFloatAdder.scala:2202:14
);

  assign io_result = {1'h0, io_adder_op0} - {1'h0, io_adder_op1};	// home/davide/gitdir/bianco_ci/bianco/XiangShan/yunsuan/src/main/scala/yunsuan/vector/VectorFloatAdder.scala:2201:7, :2208:42
endmodule

