// Generated by CIRCT firtool-1.135.0
module CountModule_reference(	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:27:7
  input         clock,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:27:7
  input  [63:0] io_src,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:28:14
  input  [8:0]  io_func,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:28:14
  input         io_regEnable,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:28:14
  output [63:0] io_out	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:28:14
);

  reg  [8:0]  funcReg;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:53:26
  reg  [3:0]  c2_0;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:54:15
  reg  [3:0]  c2_1;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:54:15
  reg  [3:0]  c2_2;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:54:15
  reg  [3:0]  c2_3;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:54:15
  reg  [3:0]  c2_4;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:54:15
  reg  [3:0]  c2_5;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:54:15
  reg  [3:0]  c2_6;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:54:15
  reg  [3:0]  c2_7;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:54:15
  reg  [4:0]  cpopTmp_0;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:55:20
  reg  [4:0]  cpopTmp_1;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:55:20
  reg  [4:0]  cpopTmp_2;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:55:20
  reg  [4:0]  cpopTmp_3;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:55:20
  wire [4:0]  c3_0 = c2_1[3] ? {c2_1[3] & c2_0[3], ~(c2_0[3]), c2_0[2:0]} : {1'h0, c2_1};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,78}, :54:15
  wire [4:0]  c3_1 = c2_3[3] ? {c2_3[3] & c2_2[3], ~(c2_2[3]), c2_2[2:0]} : {1'h0, c2_3};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,78}, :54:15
  wire [4:0]  c3_2 = c2_5[3] ? {c2_5[3] & c2_4[3], ~(c2_4[3]), c2_4[2:0]} : {1'h0, c2_5};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,78}, :54:15
  wire [4:0]  c3_3 = c2_7[3] ? {c2_7[3] & c2_6[3], ~(c2_6[3]), c2_6[2:0]} : {1'h0, c2_7};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,78}, :54:15
  wire [5:0]  c4_0 = c3_1[4] ? {c3_1[4] & c3_0[4], ~(c3_0[4]), c3_0[3:0]} : {1'h0, c3_1};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,78}
  wire [5:0]  c4_1 = c3_3[4] ? {c3_3[4] & c3_2[4], ~(c3_2[4]), c3_2[3:0]} : {1'h0, c3_3};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,78}
  wire [6:0]  _GEN = {1'h0, {1'h0, cpopTmp_0} + {1'h0, cpopTmp_1}};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:55:20, :74:29, :77:26
  wire [63:0] _countSrc_T_9 = {32'h0, io_src[63:32]} | {io_src[31:0], 32'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:41
  wire [63:0] _countSrc_T_19 =
    {16'h0, _countSrc_T_9[63:16] & 48'hFFFF0000FFFF} | {_countSrc_T_9[47:0] & 48'hFFFF0000FFFF, 16'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:41
  wire [63:0] _countSrc_T_29 =
    {8'h0, _countSrc_T_19[63:8] & 56'hFF00FF00FF00FF} | {_countSrc_T_19[55:0] & 56'hFF00FF00FF00FF, 8'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:41
  wire [63:0] _countSrc_T_39 =
    {4'h0, _countSrc_T_29[63:4] & 60'hF0F0F0F0F0F0F0F} | {_countSrc_T_29[59:0] & 60'hF0F0F0F0F0F0F0F, 4'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:41
  wire [63:0] _countSrc_T_49 =
    {2'h0, _countSrc_T_39[63:2] & 62'h3333333333333333} | {_countSrc_T_39[61:0] & 62'h3333333333333333, 2'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:41
  wire [63:0] countSrc =
    io_func[1]
      ? {1'h0, _countSrc_T_49[63:1] & 63'h5555555555555555} | {_countSrc_T_49[62:0] & 63'h5555555555555555, 1'h0}
      : io_src;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:{21,29,41}
  wire [1:0]  c0_0 = countSrc[1:0] == 2'h1 ? 2'h1 : {countSrc[1:0] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_1 = countSrc[3:2] == 2'h1 ? 2'h1 : {countSrc[3:2] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_2 = countSrc[5:4] == 2'h1 ? 2'h1 : {countSrc[5:4] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_3 = countSrc[7:6] == 2'h1 ? 2'h1 : {countSrc[7:6] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_4 = countSrc[9:8] == 2'h1 ? 2'h1 : {countSrc[9:8] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_5 = countSrc[11:10] == 2'h1 ? 2'h1 : {countSrc[11:10] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_6 = countSrc[13:12] == 2'h1 ? 2'h1 : {countSrc[13:12] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_7 = countSrc[15:14] == 2'h1 ? 2'h1 : {countSrc[15:14] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_8 = countSrc[17:16] == 2'h1 ? 2'h1 : {countSrc[17:16] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_9 = countSrc[19:18] == 2'h1 ? 2'h1 : {countSrc[19:18] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_10 = countSrc[21:20] == 2'h1 ? 2'h1 : {countSrc[21:20] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_11 = countSrc[23:22] == 2'h1 ? 2'h1 : {countSrc[23:22] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_12 = countSrc[25:24] == 2'h1 ? 2'h1 : {countSrc[25:24] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_13 = countSrc[27:26] == 2'h1 ? 2'h1 : {countSrc[27:26] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_14 = countSrc[29:28] == 2'h1 ? 2'h1 : {countSrc[29:28] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_15 = countSrc[31:30] == 2'h1 ? 2'h1 : {countSrc[31:30] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_16 = countSrc[33:32] == 2'h1 ? 2'h1 : {countSrc[33:32] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_17 = countSrc[35:34] == 2'h1 ? 2'h1 : {countSrc[35:34] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_18 = countSrc[37:36] == 2'h1 ? 2'h1 : {countSrc[37:36] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_19 = countSrc[39:38] == 2'h1 ? 2'h1 : {countSrc[39:38] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_20 = countSrc[41:40] == 2'h1 ? 2'h1 : {countSrc[41:40] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_21 = countSrc[43:42] == 2'h1 ? 2'h1 : {countSrc[43:42] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_22 = countSrc[45:44] == 2'h1 ? 2'h1 : {countSrc[45:44] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_23 = countSrc[47:46] == 2'h1 ? 2'h1 : {countSrc[47:46] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_24 = countSrc[49:48] == 2'h1 ? 2'h1 : {countSrc[49:48] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_25 = countSrc[51:50] == 2'h1 ? 2'h1 : {countSrc[51:50] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_26 = countSrc[53:52] == 2'h1 ? 2'h1 : {countSrc[53:52] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_27 = countSrc[55:54] == 2'h1 ? 2'h1 : {countSrc[55:54] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_28 = countSrc[57:56] == 2'h1 ? 2'h1 : {countSrc[57:56] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_29 = countSrc[59:58] == 2'h1 ? 2'h1 : {countSrc[59:58] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_30 = countSrc[61:60] == 2'h1 ? 2'h1 : {countSrc[61:60] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [1:0]  c0_31 = countSrc[63:62] == 2'h1 ? 2'h1 : {countSrc[63:62] == 2'h0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:47:21, :49:49, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [2:0]  c1_0 = c0_1[1] ? {c0_1[1] & c0_0[1], ~(c0_0[1]), c0_0[0]} : {1'h0, c0_1};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,64}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [2:0]  c1_1 = c0_3[1] ? {c0_3[1] & c0_2[1], ~(c0_2[1]), c0_2[0]} : {1'h0, c0_3};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,64}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [2:0]  c1_2 = c0_5[1] ? {c0_5[1] & c0_4[1], ~(c0_4[1]), c0_4[0]} : {1'h0, c0_5};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,64}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [2:0]  c1_3 = c0_7[1] ? {c0_7[1] & c0_6[1], ~(c0_6[1]), c0_6[0]} : {1'h0, c0_7};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,64}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [2:0]  c1_4 = c0_9[1] ? {c0_9[1] & c0_8[1], ~(c0_8[1]), c0_8[0]} : {1'h0, c0_9};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,64}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [2:0]  c1_5 = c0_11[1] ? {c0_11[1] & c0_10[1], ~(c0_10[1]), c0_10[0]} : {1'h0, c0_11};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,64}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [2:0]  c1_6 = c0_13[1] ? {c0_13[1] & c0_12[1], ~(c0_12[1]), c0_12[0]} : {1'h0, c0_13};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,64}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [2:0]  c1_7 = c0_15[1] ? {c0_15[1] & c0_14[1], ~(c0_14[1]), c0_14[0]} : {1'h0, c0_15};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,64}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [2:0]  c1_8 = c0_17[1] ? {c0_17[1] & c0_16[1], ~(c0_16[1]), c0_16[0]} : {1'h0, c0_17};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,64}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [2:0]  c1_9 = c0_19[1] ? {c0_19[1] & c0_18[1], ~(c0_18[1]), c0_18[0]} : {1'h0, c0_19};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,64}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [2:0]  c1_10 = c0_21[1] ? {c0_21[1] & c0_20[1], ~(c0_20[1]), c0_20[0]} : {1'h0, c0_21};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,64}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [2:0]  c1_11 = c0_23[1] ? {c0_23[1] & c0_22[1], ~(c0_22[1]), c0_22[0]} : {1'h0, c0_23};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,64}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [2:0]  c1_12 = c0_25[1] ? {c0_25[1] & c0_24[1], ~(c0_24[1]), c0_24[0]} : {1'h0, c0_25};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,64}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [2:0]  c1_13 = c0_27[1] ? {c0_27[1] & c0_26[1], ~(c0_26[1]), c0_26[0]} : {1'h0, c0_27};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,64}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [2:0]  c1_14 = c0_29[1] ? {c0_29[1] & c0_28[1], ~(c0_28[1]), c0_28[0]} : {1'h0, c0_29};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,64}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  wire [2:0]  c1_15 = c0_31[1] ? {c0_31[1] & c0_30[1], ~(c0_30[1]), c0_30[0]} : {1'h0, c0_31};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,64}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LookupTree.scala:32:28
  always @(posedge clock) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:27:7
    if (io_regEnable) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:28:14
      funcReg <= io_func;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:53:26
      c2_0 <= c1_1[2] ? {c1_1[2] & c1_0[2], ~(c1_0[2]), c1_0[1:0]} : {1'h0, c1_1};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,78}, :54:15
      c2_1 <= c1_3[2] ? {c1_3[2] & c1_2[2], ~(c1_2[2]), c1_2[1:0]} : {1'h0, c1_3};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,78}, :54:15
      c2_2 <= c1_5[2] ? {c1_5[2] & c1_4[2], ~(c1_4[2]), c1_4[1:0]} : {1'h0, c1_5};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,78}, :54:15
      c2_3 <= c1_7[2] ? {c1_7[2] & c1_6[2], ~(c1_6[2]), c1_6[1:0]} : {1'h0, c1_7};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,78}, :54:15
      c2_4 <= c1_9[2] ? {c1_9[2] & c1_8[2], ~(c1_8[2]), c1_8[1:0]} : {1'h0, c1_9};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,78}, :54:15
      c2_5 <= c1_11[2] ? {c1_11[2] & c1_10[2], ~(c1_10[2]), c1_10[1:0]} : {1'h0, c1_11};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,78}, :54:15
      c2_6 <= c1_13[2] ? {c1_13[2] & c1_12[2], ~(c1_12[2]), c1_12[1:0]} : {1'h0, c1_13};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,78}, :54:15
      c2_7 <= c1_15[2] ? {c1_15[2] & c1_14[2], ~(c1_14[2]), c1_14[1:0]} : {1'h0, c1_15};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:39:{8,13}, :40:{10,21,29,36,78}, :54:15
      cpopTmp_0 <=
        {1'h0,
         {1'h0, {1'h0, {1'h0, io_src[0]} + {1'h0, io_src[1]}} + {1'h0, {1'h0, io_src[2]} + {1'h0, io_src[3]}}}
           + {1'h0, {1'h0, {1'h0, io_src[4]} + {1'h0, io_src[5]}} + {1'h0, {1'h0, io_src[6]} + {1'h0, io_src[7]}}}}
        + {1'h0,
           {1'h0, {1'h0, {1'h0, io_src[8]} + {1'h0, io_src[9]}} + {1'h0, {1'h0, io_src[10]} + {1'h0, io_src[11]}}}
             + {1'h0,
                {1'h0, {1'h0, io_src[12]} + {1'h0, io_src[13]}} + {1'h0, {1'h0, io_src[14]} + {1'h0, io_src[15]}}}};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:55:20, :61:{29,36}
      cpopTmp_1 <=
        {1'h0,
         {1'h0, {1'h0, {1'h0, io_src[16]} + {1'h0, io_src[17]}} + {1'h0, {1'h0, io_src[18]} + {1'h0, io_src[19]}}}
           + {1'h0, {1'h0, {1'h0, io_src[20]} + {1'h0, io_src[21]}} + {1'h0, {1'h0, io_src[22]} + {1'h0, io_src[23]}}}}
        + {1'h0,
           {1'h0, {1'h0, {1'h0, io_src[24]} + {1'h0, io_src[25]}} + {1'h0, {1'h0, io_src[26]} + {1'h0, io_src[27]}}}
             + {1'h0,
                {1'h0, {1'h0, io_src[28]} + {1'h0, io_src[29]}} + {1'h0, {1'h0, io_src[30]} + {1'h0, io_src[31]}}}};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:55:20, :61:{29,36}
      cpopTmp_2 <=
        {1'h0,
         {1'h0, {1'h0, {1'h0, io_src[32]} + {1'h0, io_src[33]}} + {1'h0, {1'h0, io_src[34]} + {1'h0, io_src[35]}}}
           + {1'h0, {1'h0, {1'h0, io_src[36]} + {1'h0, io_src[37]}} + {1'h0, {1'h0, io_src[38]} + {1'h0, io_src[39]}}}}
        + {1'h0,
           {1'h0, {1'h0, {1'h0, io_src[40]} + {1'h0, io_src[41]}} + {1'h0, {1'h0, io_src[42]} + {1'h0, io_src[43]}}}
             + {1'h0,
                {1'h0, {1'h0, io_src[44]} + {1'h0, io_src[45]}} + {1'h0, {1'h0, io_src[46]} + {1'h0, io_src[47]}}}};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:55:20, :61:{29,36}
      cpopTmp_3 <=
        {1'h0,
         {1'h0, {1'h0, {1'h0, io_src[48]} + {1'h0, io_src[49]}} + {1'h0, {1'h0, io_src[50]} + {1'h0, io_src[51]}}}
           + {1'h0, {1'h0, {1'h0, io_src[52]} + {1'h0, io_src[53]}} + {1'h0, {1'h0, io_src[54]} + {1'h0, io_src[55]}}}}
        + {1'h0,
           {1'h0, {1'h0, {1'h0, io_src[56]} + {1'h0, io_src[57]}} + {1'h0, {1'h0, io_src[58]} + {1'h0, io_src[59]}}}
             + {1'h0,
                {1'h0, {1'h0, io_src[60]} + {1'h0, io_src[61]}} + {1'h0, {1'h0, io_src[62]} + {1'h0, io_src[63]}}}};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:55:20, :61:{29,36}
    end
  end // always @(posedge)
  assign io_out =
    {57'h0,
     funcReg[2]
       ? (funcReg[0] ? _GEN : _GEN + {1'h0, {1'h0, cpopTmp_2} + {1'h0, cpopTmp_3}})
       : funcReg[0]
           ? {1'h0, funcReg[1] ? c4_1 : c4_0}
           : c4_1[5] ? {c4_1[5] & c4_0[5], ~(c4_0[5]), c4_0[4:0]} : {1'h0, c4_1}};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Bku.scala:27:7, :39:{8,13}, :40:{10,21,29,36,78}, :53:26, :55:20, :72:{21,29}, :75:29, :77:26, :80:{10,16,24,32,40,68}
endmodule

