// Generated by CIRCT firtool-1.135.0
module CSA3to2_152_reference(	// home/davide/gitdir/bianco/XiangShan/yunsuan/src/main/scala/yunsuan/vector/VectorFloatFMA.scala:1581:23
  input  [7:0] io_in_a,	// home/davide/gitdir/bianco/XiangShan/yunsuan/src/main/scala/yunsuan/vector/VectorFloatFMA.scala:1582:14
               io_in_b,	// home/davide/gitdir/bianco/XiangShan/yunsuan/src/main/scala/yunsuan/vector/VectorFloatFMA.scala:1582:14
               io_in_c,	// home/davide/gitdir/bianco/XiangShan/yunsuan/src/main/scala/yunsuan/vector/VectorFloatFMA.scala:1582:14
  output [7:0] io_out_sum,	// home/davide/gitdir/bianco/XiangShan/yunsuan/src/main/scala/yunsuan/vector/VectorFloatFMA.scala:1582:14
               io_out_car	// home/davide/gitdir/bianco/XiangShan/yunsuan/src/main/scala/yunsuan/vector/VectorFloatFMA.scala:1582:14
);

  assign io_out_sum = io_in_a ^ io_in_b ^ io_in_c;	// home/davide/gitdir/bianco/XiangShan/yunsuan/src/main/scala/yunsuan/vector/VectorFloatFMA.scala:1581:23, :1590:{25,35}
  assign io_out_car = {io_in_a[6:0] & io_in_b[6:0] | io_in_a[6:0] & io_in_c[6:0] | io_in_b[6:0] & io_in_c[6:0], 1'h0};	// home/davide/gitdir/bianco/XiangShan/yunsuan/src/main/scala/yunsuan/vector/VectorFloatFMA.scala:1581:23, :1582:14, :1591:{20,33,44,55,66,77}
endmodule

