// Generated by CIRCT firtool-1.135.0
module FCMP_reference(	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
  input         clock,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
                reset,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
  output        io_in_ready,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
  input         io_in_valid,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
  input  [8:0]  io_in_bits_ctrl_fuOpType,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
  input  [1:0]  io_in_bits_ctrl_fpu_fmt,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
  input         io_in_bits_ctrlPipe_3_toRobValid,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
                io_in_bits_ctrlPipe_3_robIdx_flag,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
  input  [5:0]  io_in_bits_ctrlPipe_3_robIdx_value,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
  input  [7:0]  io_in_bits_ctrlPipe_3_pdest,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
  input         io_in_bits_ctrlPipe_3_rfWen,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
                io_in_bits_ctrlPipe_3_fpu_wflags,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
                io_in_bits_validPipe_0,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
  input  [63:0] io_in_bits_data_src_1,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
                io_in_bits_data_src_0,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
                io_in_bits_perfDebugInfo_enqRsTime,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
                io_in_bits_perfDebugInfo_selectTime,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
                io_in_bits_perfDebugInfo_issueTime,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
                io_in_bits_perfDebugInfo_tlbFirstReqTime,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
                io_in_bits_perfDebugInfo_tlbRespTime,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
  input         io_out_ready,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
  output        io_out_valid,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
                io_out_bits_ctrl_toRobValid,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
                io_out_bits_ctrl_robIdx_flag,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
  output [5:0]  io_out_bits_ctrl_robIdx_value,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
  output [7:0]  io_out_bits_ctrl_pdest,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
  output        io_out_bits_ctrl_rfWen,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
                io_out_bits_ctrl_fpu_wflags,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
  output [63:0] io_out_bits_res_data /* #hw<innerSym@__FCMP__DONTTOUCH__28__io_out_bits_res_data> */,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
  output [4:0]  io_out_bits_res_fflags /* #hw<innerSym@__FCMP__DONTTOUCH__29__io_out_bits_res_fflags> */,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
  output [63:0] io_out_bits_perfDebugInfo_enqRsTime,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
                io_out_bits_perfDebugInfo_selectTime,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
                io_out_bits_perfDebugInfo_issueTime,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
                io_out_bits_perfDebugInfo_tlbFirstReqTime,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
                io_out_bits_perfDebugInfo_tlbRespTime	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:148:14
);

  wire        fixRdyVec_2;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:234:37
  wire        fixRdyVec_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:234:37
  wire        validVec_0 = io_in_bits_validPipe_0 & io_in_valid;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:261:77
  reg         fixValidVec_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:222:54
  reg         fixValidVec_2;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:222:54
  reg         fixValidVec_3;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:222:54
  reg  [63:0] perfVec_1_enqRsTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
  reg  [63:0] perfVec_1_selectTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
  reg  [63:0] perfVec_1_issueTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
  reg  [63:0] perfVec_1_tlbFirstReqTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
  reg  [63:0] perfVec_1_tlbRespTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
  reg  [63:0] perfVec_2_enqRsTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
  reg  [63:0] perfVec_2_selectTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
  reg  [63:0] perfVec_2_issueTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
  reg  [63:0] perfVec_2_tlbFirstReqTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
  reg  [63:0] perfVec_2_tlbRespTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
  reg  [63:0] perfVec_3_enqRsTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
  reg  [63:0] perfVec_3_selectTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
  reg  [63:0] perfVec_3_issueTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
  reg  [63:0] perfVec_3_tlbFirstReqTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
  reg  [63:0] perfVec_3_tlbRespTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
  wire        fixRdyVec_0 = ~fixValidVec_1 | fixRdyVec_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:222:54, :234:{20,37}
  assign fixRdyVec_1 = ~fixValidVec_2 | fixRdyVec_2;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:222:54, :234:{20,37}
  assign fixRdyVec_2 = ~fixValidVec_3 | io_out_ready;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:222:54, :234:{20,37}
  always @(posedge clock or posedge reset) begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
    if (reset) begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
      fixValidVec_1 <= 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:222:54, :250:32
      fixValidVec_2 <= 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:222:54, :250:32
      fixValidVec_3 <= 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:222:54, :250:32
    end
    else begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
      fixValidVec_1 <= validVec_0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:222:54, :261:77
      fixValidVec_2 <= fixValidVec_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:222:54
      fixValidVec_3 <= fixValidVec_2;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:222:54
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
    if (fixRdyVec_0 & validVec_0) begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:234:37, :238:26, :261:77
      perfVec_1_enqRsTime <= io_in_bits_perfDebugInfo_enqRsTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
      perfVec_1_selectTime <= io_in_bits_perfDebugInfo_selectTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
      perfVec_1_issueTime <= io_in_bits_perfDebugInfo_issueTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
      perfVec_1_tlbFirstReqTime <= io_in_bits_perfDebugInfo_tlbFirstReqTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
      perfVec_1_tlbRespTime <= io_in_bits_perfDebugInfo_tlbRespTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
    end
    if (fixRdyVec_1 & fixValidVec_1) begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:222:54, :234:37, :238:26
      perfVec_2_enqRsTime <= perfVec_1_enqRsTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
      perfVec_2_selectTime <= perfVec_1_selectTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
      perfVec_2_issueTime <= perfVec_1_issueTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
      perfVec_2_tlbFirstReqTime <= perfVec_1_tlbFirstReqTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
      perfVec_2_tlbRespTime <= perfVec_1_tlbRespTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
    end
    if (fixRdyVec_2 & fixValidVec_2) begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:222:54, :234:37, :238:26
      perfVec_3_enqRsTime <= perfVec_2_enqRsTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
      perfVec_3_selectTime <= perfVec_2_selectTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
      perfVec_3_issueTime <= perfVec_2_issueTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
      perfVec_3_tlbFirstReqTime <= perfVec_2_tlbFirstReqTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
      perfVec_3_tlbRespTime <= perfVec_2_tlbRespTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
      `FIRRTL_BEFORE_INITIAL	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
      if (reset) begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
        fixValidVec_1 = 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:222:54, :250:32
        fixValidVec_2 = 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:222:54, :250:32
        fixValidVec_3 = 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:222:54, :250:32
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
      `FIRRTL_AFTER_INITIAL	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  FloatCompare_reference fcmp (	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:20:28
    .io_src0     (io_in_bits_data_src_0),
    .io_src1     (io_in_bits_data_src_1),
    .io_fpFormat (io_in_bits_ctrl_fpu_fmt),
    .io_opCode   (io_in_bits_ctrl_fuOpType[3:0]),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:15:32
    .io_result   (io_out_bits_res_data),
    .io_fflags   (io_out_bits_res_fflags)
  );	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:20:28
  assign io_in_ready = fixRdyVec_0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:234:37, home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
  assign io_out_valid = fixValidVec_3;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:222:54, home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
  assign io_out_bits_ctrl_toRobValid = io_in_bits_ctrlPipe_3_toRobValid;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
  assign io_out_bits_ctrl_robIdx_flag = io_in_bits_ctrlPipe_3_robIdx_flag;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
  assign io_out_bits_ctrl_robIdx_value = io_in_bits_ctrlPipe_3_robIdx_value;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
  assign io_out_bits_ctrl_pdest = io_in_bits_ctrlPipe_3_pdest;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
  assign io_out_bits_ctrl_rfWen = io_in_bits_ctrlPipe_3_rfWen;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
  assign io_out_bits_ctrl_fpu_wflags = io_in_bits_ctrlPipe_3_fpu_wflags;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
  assign io_out_bits_perfDebugInfo_enqRsTime = perfVec_3_enqRsTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68, home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
  assign io_out_bits_perfDebugInfo_selectTime = perfVec_3_selectTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68, home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
  assign io_out_bits_perfDebugInfo_issueTime = perfVec_3_issueTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68, home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
  assign io_out_bits_perfDebugInfo_tlbFirstReqTime = perfVec_3_tlbFirstReqTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68, home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
  assign io_out_bits_perfDebugInfo_tlbRespTime = perfVec_3_tlbRespTime;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/FuncUnit.scala:225:68, home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/wrapper/FCMP.scala:13:7
endmodule

