// Generated by CIRCT firtool-1.135.0
module FuBusyTableWrite_81_reference(	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:12:7
  input         clock,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:12:7
                reset,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:12:7
                io_in_deqResp_valid,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:15:14
  input  [35:0] io_in_deqResp_bits_fuType,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:15:14
  input         io_in_og0Resp_failed,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:15:14
  input  [35:0] io_in_og0Resp_fuType,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:15:14
  input         io_in_og1Resp_failed,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:15:14
  input  [35:0] io_in_og1Resp_fuType,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:15:14
  output [3:0]  io_out_fuBusyTable	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:15:14
);

  reg [3:0] fuBusyTable;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:22:36
  always @(posedge clock or posedge reset) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:12:7
    if (reset)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:12:7
      fuBusyTable <= 4'h0;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:22:36
    else	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:12:7
      fuBusyTable <=
        {1'h0,
         ~(io_in_og1Resp_failed
             ? {2'h0, |{io_in_og1Resp_fuType[4], io_in_og1Resp_fuType[12], io_in_og1Resp_fuType[13]}}
             : 3'h0)
           & ~(io_in_og0Resp_failed
                 ? {1'h0, |{io_in_og0Resp_fuType[4], io_in_og0Resp_fuType[12], io_in_og0Resp_fuType[13]}, 1'h0}
                 : 3'h0) & fuBusyTable[3:1]}
        | (io_in_deqResp_valid
             ? {1'h0,
                |{io_in_deqResp_bits_fuType[4], io_in_deqResp_bits_fuType[12], io_in_deqResp_bits_fuType[13]},
                1'h0,
                io_in_deqResp_bits_fuType[11]}
             : 4'h0);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:22:36, :44:12, :46:34, :48:11, :52:47, :53:36, :54:38, :55:38, :57:{39,42,69,72,99}
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:12:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:12:7
      `FIRRTL_BEFORE_INITIAL	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:12:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:12:7
      if (reset)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:12:7
        fuBusyTable = 4'h0;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:22:36
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:12:7
      `FIRRTL_AFTER_INITIAL	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:12:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_fuBusyTable = fuBusyTable;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/FuBusyTableWrite.scala:12:7, :22:36
endmodule

