// Generated by CIRCT firtool-1.135.0
module IopmpChecker_reference(	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1334:7
  input         clock,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1334:7
                reset,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1334:7
                io_regcfg_v,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1335:14
                io_regcfg_rw,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1335:14
  input  [31:0] io_regcfg_addr,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1335:14
                io_regcfg_din,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1335:14
  output [31:0] io_regcfg_dout,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1335:14
  output        io_req_ready,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1335:14
  input         io_req_valid,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1335:14
  input  [15:0] io_req_bits_rrid,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1335:14
  input  [47:0] io_req_bits_pa,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1335:14
  input         io_req_bits_rw,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1335:14
  input  [47:0] io_req_bits_len,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1335:14
  input         io_resp_ready,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1335:14
  output        io_resp_valid,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1335:14
                io_resp_bits_cf_r,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1335:14
                io_resp_bits_cf_w,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1335:14
                io_enable	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1335:14
);

  wire [15:0] _ctrl_io_srcmd_s_indx;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
  wire        _ctrl_io_srcmd_s_en;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
  wire [4:0]  _ctrl_io_mdcfg_m_indx;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
  wire        _ctrl_io_mdcfg_m_en;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
  wire [8:0]  _ctrl_io_entry_j_indx;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
  wire        _ctrl_io_entry_j_en;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
  wire        _ctrl_io_reg_i_errinfo_v;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
  wire [1:0]  _ctrl_io_reg_i_errinfo_ttype;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
  wire [3:0]  _ctrl_io_reg_i_errinfo_etype;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
  wire [31:0] _ctrl_io_reg_i_erreqaddr;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
  wire [31:0] _ctrl_io_reg_i_erreqaddrh;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
  wire [15:0] _ctrl_io_reg_i_erreqid_rrid;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
  wire [15:0] _ctrl_io_reg_i_erreqid_eid;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
  wire [31:0] _reg_map_io_regcfg_dout;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1352:23
  wire        _reg_map_io_bits_o_reg_hwcfg0_enable;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1352:23
  wire [15:0] _reg_map_io_bits_o_reg_hwcfg2_prio_entry;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1352:23
  wire        _reg_map_io_bits_o_reg_errinfo_v;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1352:23
  wire [31:0] _entry_table_io_regcfg_dout;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1351:27
  wire [63:0] _entry_table_io_bits_addr;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1351:27
  wire        _entry_table_io_bits_attribute_r;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1351:27
  wire        _entry_table_io_bits_attribute_w;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1351:27
  wire [1:0]  _entry_table_io_bits_attribute_a;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1351:27
  wire [31:0] _mdcfg_table_io_regcfg_dout;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1350:27
  wire [15:0] _mdcfg_table_io_bits_j_indx;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1350:27
  wire [31:0] _srcmd_table_io_regcfg_dout;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1349:27
  wire [30:0] _srcmd_table_io_bits_m_indx;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1349:27
  wire        _regcfg_mux_io_regcfg_regmap_v;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
  wire        _regcfg_mux_io_regcfg_regmap_rw;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
  wire [31:0] _regcfg_mux_io_regcfg_regmap_addr;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
  wire [31:0] _regcfg_mux_io_regcfg_regmap_din;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
  wire        _regcfg_mux_io_regcfg_mdcfg_v;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
  wire        _regcfg_mux_io_regcfg_mdcfg_rw;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
  wire [31:0] _regcfg_mux_io_regcfg_mdcfg_addr;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
  wire [31:0] _regcfg_mux_io_regcfg_mdcfg_din;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
  wire        _regcfg_mux_io_regcfg_srcmd_v;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
  wire        _regcfg_mux_io_regcfg_srcmd_rw;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
  wire [31:0] _regcfg_mux_io_regcfg_srcmd_addr;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
  wire [31:0] _regcfg_mux_io_regcfg_srcmd_din;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
  wire        _regcfg_mux_io_regcfg_entry_v;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
  wire        _regcfg_mux_io_regcfg_entry_rw;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
  wire [31:0] _regcfg_mux_io_regcfg_entry_addr;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
  wire [31:0] _regcfg_mux_io_regcfg_entry_din;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
  RegCfgMux_reference regcfg_mux (	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
    .io_regcfg_v           (io_regcfg_v),
    .io_regcfg_rw          (io_regcfg_rw),
    .io_regcfg_addr        (io_regcfg_addr),
    .io_regcfg_din         (io_regcfg_din),
    .io_regcfg_dout        (io_regcfg_dout),
    .io_regcfg_regmap_v    (_regcfg_mux_io_regcfg_regmap_v),
    .io_regcfg_regmap_rw   (_regcfg_mux_io_regcfg_regmap_rw),
    .io_regcfg_regmap_addr (_regcfg_mux_io_regcfg_regmap_addr),
    .io_regcfg_regmap_din  (_regcfg_mux_io_regcfg_regmap_din),
    .io_regcfg_regmap_dout (_reg_map_io_regcfg_dout),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1352:23
    .io_regcfg_mdcfg_v     (_regcfg_mux_io_regcfg_mdcfg_v),
    .io_regcfg_mdcfg_rw    (_regcfg_mux_io_regcfg_mdcfg_rw),
    .io_regcfg_mdcfg_addr  (_regcfg_mux_io_regcfg_mdcfg_addr),
    .io_regcfg_mdcfg_din   (_regcfg_mux_io_regcfg_mdcfg_din),
    .io_regcfg_mdcfg_dout  (_mdcfg_table_io_regcfg_dout),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1350:27
    .io_regcfg_srcmd_v     (_regcfg_mux_io_regcfg_srcmd_v),
    .io_regcfg_srcmd_rw    (_regcfg_mux_io_regcfg_srcmd_rw),
    .io_regcfg_srcmd_addr  (_regcfg_mux_io_regcfg_srcmd_addr),
    .io_regcfg_srcmd_din   (_regcfg_mux_io_regcfg_srcmd_din),
    .io_regcfg_srcmd_dout  (_srcmd_table_io_regcfg_dout),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1349:27
    .io_regcfg_entry_v     (_regcfg_mux_io_regcfg_entry_v),
    .io_regcfg_entry_rw    (_regcfg_mux_io_regcfg_entry_rw),
    .io_regcfg_entry_addr  (_regcfg_mux_io_regcfg_entry_addr),
    .io_regcfg_entry_din   (_regcfg_mux_io_regcfg_entry_din),
    .io_regcfg_entry_dout  (_entry_table_io_regcfg_dout)	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1351:27
  );	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
  SrcmdTable_reference srcmd_table (	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1349:27
    .clock          (clock),
    .reset          (reset),
    .io_regcfg_v    (_regcfg_mux_io_regcfg_srcmd_v),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
    .io_regcfg_rw   (_regcfg_mux_io_regcfg_srcmd_rw),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
    .io_regcfg_addr (_regcfg_mux_io_regcfg_srcmd_addr),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
    .io_regcfg_din  (_regcfg_mux_io_regcfg_srcmd_din),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
    .io_regcfg_dout (_srcmd_table_io_regcfg_dout),
    .io_bits_s_indx (_ctrl_io_srcmd_s_indx),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
    .io_bits_s_en   (_ctrl_io_srcmd_s_en),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
    .io_bits_m_indx (_srcmd_table_io_bits_m_indx)
  );	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1349:27
  MdcfgTable_reference mdcfg_table (	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1350:27
    .clock          (clock),
    .io_regcfg_v    (_regcfg_mux_io_regcfg_mdcfg_v),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
    .io_regcfg_rw   (_regcfg_mux_io_regcfg_mdcfg_rw),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
    .io_regcfg_addr (_regcfg_mux_io_regcfg_mdcfg_addr),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
    .io_regcfg_din  (_regcfg_mux_io_regcfg_mdcfg_din),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
    .io_regcfg_dout (_mdcfg_table_io_regcfg_dout),
    .io_bits_m_indx (_ctrl_io_mdcfg_m_indx),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
    .io_bits_m_en   (_ctrl_io_mdcfg_m_en),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
    .io_bits_j_indx (_mdcfg_table_io_bits_j_indx)
  );	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1350:27
  EntryTable_reference entry_table (	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1351:27
    .clock               (clock),
    .io_regcfg_v         (_regcfg_mux_io_regcfg_entry_v),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
    .io_regcfg_rw        (_regcfg_mux_io_regcfg_entry_rw),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
    .io_regcfg_addr      (_regcfg_mux_io_regcfg_entry_addr),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
    .io_regcfg_din       (_regcfg_mux_io_regcfg_entry_din),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
    .io_regcfg_dout      (_entry_table_io_regcfg_dout),
    .io_bits_j_indx      (_ctrl_io_entry_j_indx),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
    .io_bits_j_en        (_ctrl_io_entry_j_en),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
    .io_bits_addr        (_entry_table_io_bits_addr),
    .io_bits_attribute_r (_entry_table_io_bits_attribute_r),
    .io_bits_attribute_w (_entry_table_io_bits_attribute_w),
    .io_bits_attribute_a (_entry_table_io_bits_attribute_a)
  );	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1351:27
  RegMap_reference reg_map (	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1352:23
    .clock                           (clock),
    .reset                           (reset),
    .io_regcfg_v                     (_regcfg_mux_io_regcfg_regmap_v),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
    .io_regcfg_rw                    (_regcfg_mux_io_regcfg_regmap_rw),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
    .io_regcfg_addr                  (_regcfg_mux_io_regcfg_regmap_addr),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
    .io_regcfg_din                   (_regcfg_mux_io_regcfg_regmap_din),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1348:26
    .io_regcfg_dout                  (_reg_map_io_regcfg_dout),
    .io_bits_i_errinfo_v             (_ctrl_io_reg_i_errinfo_v),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
    .io_bits_i_errinfo_ttype         (_ctrl_io_reg_i_errinfo_ttype),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
    .io_bits_i_errinfo_etype         (_ctrl_io_reg_i_errinfo_etype),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
    .io_bits_i_erreqaddr             (_ctrl_io_reg_i_erreqaddr),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
    .io_bits_i_erreqaddrh            (_ctrl_io_reg_i_erreqaddrh),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
    .io_bits_i_erreqid_rrid          (_ctrl_io_reg_i_erreqid_rrid),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
    .io_bits_i_erreqid_eid           (_ctrl_io_reg_i_erreqid_eid),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
    .io_bits_o_reg_hwcfg0_enable     (_reg_map_io_bits_o_reg_hwcfg0_enable),
    .io_bits_o_reg_hwcfg2_prio_entry (_reg_map_io_bits_o_reg_hwcfg2_prio_entry),
    .io_bits_o_reg_errinfo_v         (_reg_map_io_bits_o_reg_errinfo_v)
  );	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1352:23
  Ctrl_reference ctrl (	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
    .clock                          (clock),
    .reset                          (reset),
    .io_req_ready                   (io_req_ready),
    .io_req_valid                   (io_req_valid),
    .io_req_bits_rrid               (io_req_bits_rrid),
    .io_req_bits_pa                 (io_req_bits_pa),
    .io_req_bits_rw                 (io_req_bits_rw),
    .io_req_bits_len                (io_req_bits_len),
    .io_resp_ready                  (io_resp_ready),
    .io_resp_valid                  (io_resp_valid),
    .io_resp_bits_cf_r              (io_resp_bits_cf_r),
    .io_resp_bits_cf_w              (io_resp_bits_cf_w),
    .io_srcmd_s_indx                (_ctrl_io_srcmd_s_indx),
    .io_srcmd_s_en                  (_ctrl_io_srcmd_s_en),
    .io_srcmd_m_indx                (_srcmd_table_io_bits_m_indx),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1349:27
    .io_mdcfg_m_indx                (_ctrl_io_mdcfg_m_indx),
    .io_mdcfg_m_en                  (_ctrl_io_mdcfg_m_en),
    .io_mdcfg_j_indx                (_mdcfg_table_io_bits_j_indx),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1350:27
    .io_entry_j_indx                (_ctrl_io_entry_j_indx),
    .io_entry_j_en                  (_ctrl_io_entry_j_en),
    .io_entry_addr                  (_entry_table_io_bits_addr),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1351:27
    .io_entry_attribute_r           (_entry_table_io_bits_attribute_r),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1351:27
    .io_entry_attribute_w           (_entry_table_io_bits_attribute_w),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1351:27
    .io_entry_attribute_a           (_entry_table_io_bits_attribute_a),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1351:27
    .io_reg_i_errinfo_v             (_ctrl_io_reg_i_errinfo_v),
    .io_reg_i_errinfo_ttype         (_ctrl_io_reg_i_errinfo_ttype),
    .io_reg_i_errinfo_etype         (_ctrl_io_reg_i_errinfo_etype),
    .io_reg_i_erreqaddr             (_ctrl_io_reg_i_erreqaddr),
    .io_reg_i_erreqaddrh            (_ctrl_io_reg_i_erreqaddrh),
    .io_reg_i_erreqid_rrid          (_ctrl_io_reg_i_erreqid_rrid),
    .io_reg_i_erreqid_eid           (_ctrl_io_reg_i_erreqid_eid),
    .io_reg_o_reg_hwcfg0_enable     (_reg_map_io_bits_o_reg_hwcfg0_enable),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1352:23
    .io_reg_o_reg_hwcfg2_prio_entry (_reg_map_io_bits_o_reg_hwcfg2_prio_entry),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1352:23
    .io_reg_o_reg_errinfo_v         (_reg_map_io_bits_o_reg_errinfo_v),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1352:23
    .io_stall                       (io_regcfg_v & io_regcfg_rw),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1356:27
    .io_enable                      (io_enable)
  );	// home/davide/gitdir/bianco_ci/bianco/XiangShan/ChiselIOPMP/src/main/scala/IopmpChecker.scala:1353:20
endmodule

