// Generated by CIRCT firtool-1.135.0
module JtagBypassChain_reference(	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/jtag/JtagShifter.scala:56:7
  input  clock /* #hw<innerSym@sym_3> */,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/jtag/JtagShifter.scala:56:7
         reset /* inner_sym: sym_2 */,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/jtag/JtagShifter.scala:56:7
         io_chainIn_shift /* inner_sym: sym_1 */,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/jtag/JtagShifter.scala:58:14
         io_chainIn_data,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/jtag/JtagShifter.scala:58:14
         io_chainIn_capture /* inner_sym: sym */,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/jtag/JtagShifter.scala:58:14
         io_chainIn_update /* inner_sym: sym_0 */,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/jtag/JtagShifter.scala:58:14
  output io_chainOut_data	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/jtag/JtagShifter.scala:58:14
);

  reg reg_0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/jtag/JtagShifter.scala:61:16
  always @(posedge clock) begin	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/jtag/JtagShifter.scala:56:7
    if (io_chainIn_capture)	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/jtag/JtagShifter.scala:56:7
      reg_0 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/jtag/JtagShifter.scala:61:16, :68:9
    else if (io_chainIn_shift)	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/jtag/JtagShifter.scala:58:14
      reg_0 <= io_chainIn_data;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/jtag/JtagShifter.scala:61:16
  end // always @(posedge)
  assign io_chainOut_data = reg_0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/jtag/JtagShifter.scala:56:7, :61:16
endmodule

