// Generated by CIRCT firtool-1.135.0
module L2Directory_1(	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7
  input          clock,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7
                 reset,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7
  input  [3:0]   mbist_array /* #hw<innerSym@__L2Directory_1__DONTTOUCH__2__mbist_array> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:184:17
  input          mbist_all /* #hw<innerSym@__L2Directory_1__DONTTOUCH__3__mbist_all> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:184:17
                 mbist_req /* inner_sym: __L2Directory_1__DONTTOUCH__4__mbist_req */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:184:17
  output         mbist_ack /* #hw<innerSym@__L2Directory_1__DONTTOUCH__5__mbist_ack> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:184:17
  input          mbist_writeen /* #hw<innerSym@__L2Directory_1__DONTTOUCH__6__mbist_writeen> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:184:17
  input  [7:0]   mbist_be /* #hw<innerSym@__L2Directory_1__DONTTOUCH__7__mbist_be> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:184:17
                 mbist_addr /* inner_sym: __L2Directory_1__DONTTOUCH__8__mbist_addr */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:184:17
  input  [135:0] mbist_indata /* #hw<innerSym@__L2Directory_1__DONTTOUCH__9__mbist_indata> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:184:17
  input          mbist_readen /* #hw<innerSym@__L2Directory_1__DONTTOUCH__10__mbist_readen> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:184:17
  input  [7:0]   mbist_addr_rd /* #hw<innerSym@__L2Directory_1__DONTTOUCH__11__mbist_addr_rd> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:184:17
  output [135:0] mbist_outdata /* #hw<innerSym@__L2Directory_1__DONTTOUCH__12__mbist_outdata> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:184:17
  output [7:0]   toSRAM_0_addr /* #hw<innerSym@__L2Directory_1__DONTTOUCH__13__toSRAM_0_addr> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
                 toSRAM_0_addr_rd /* inner_sym: __L2Directory_1__DONTTOUCH__14__toSRAM_0_addr_rd */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output [135:0] toSRAM_0_wdata /* #hw<innerSym@__L2Directory_1__DONTTOUCH__15__toSRAM_0_wdata> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output [3:0]   toSRAM_0_wmask /* #hw<innerSym@__L2Directory_1__DONTTOUCH__16__toSRAM_0_wmask> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output         toSRAM_0_re /* #hw<innerSym@__L2Directory_1__DONTTOUCH__17__toSRAM_0_re> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
                 toSRAM_0_we /* inner_sym: __L2Directory_1__DONTTOUCH__18__toSRAM_0_we */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  input  [135:0] toSRAM_0_rdata /* #hw<innerSym@__L2Directory_1__DONTTOUCH__19__toSRAM_0_rdata> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output         toSRAM_0_ack /* #hw<innerSym@__L2Directory_1__DONTTOUCH__20__toSRAM_0_ack> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
                 toSRAM_0_selectedOH /* inner_sym: __L2Directory_1__DONTTOUCH__21__toSRAM_0_selectedOH */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output [3:0]   toSRAM_0_array /* #hw<innerSym@__L2Directory_1__DONTTOUCH__22__toSRAM_0_array> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output [7:0]   toSRAM_1_addr /* #hw<innerSym@__L2Directory_1__DONTTOUCH__23__toSRAM_1_addr> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
                 toSRAM_1_addr_rd /* inner_sym: __L2Directory_1__DONTTOUCH__24__toSRAM_1_addr_rd */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output [135:0] toSRAM_1_wdata /* #hw<innerSym@__L2Directory_1__DONTTOUCH__25__toSRAM_1_wdata> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output [3:0]   toSRAM_1_wmask /* #hw<innerSym@__L2Directory_1__DONTTOUCH__26__toSRAM_1_wmask> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output         toSRAM_1_re /* #hw<innerSym@__L2Directory_1__DONTTOUCH__27__toSRAM_1_re> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
                 toSRAM_1_we /* inner_sym: __L2Directory_1__DONTTOUCH__28__toSRAM_1_we */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  input  [135:0] toSRAM_1_rdata /* #hw<innerSym@__L2Directory_1__DONTTOUCH__29__toSRAM_1_rdata> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output         toSRAM_1_ack /* #hw<innerSym@__L2Directory_1__DONTTOUCH__30__toSRAM_1_ack> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
                 toSRAM_1_selectedOH /* inner_sym: __L2Directory_1__DONTTOUCH__31__toSRAM_1_selectedOH */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output [3:0]   toSRAM_1_array /* #hw<innerSym@__L2Directory_1__DONTTOUCH__32__toSRAM_1_array> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output [7:0]   toSRAM_2_addr /* #hw<innerSym@__L2Directory_1__DONTTOUCH__33__toSRAM_2_addr> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
                 toSRAM_2_addr_rd /* inner_sym: __L2Directory_1__DONTTOUCH__34__toSRAM_2_addr_rd */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output [55:0]  toSRAM_2_wdata /* #hw<innerSym@__L2Directory_1__DONTTOUCH__35__toSRAM_2_wdata> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output [7:0]   toSRAM_2_wmask /* #hw<innerSym@__L2Directory_1__DONTTOUCH__36__toSRAM_2_wmask> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output         toSRAM_2_re /* #hw<innerSym@__L2Directory_1__DONTTOUCH__37__toSRAM_2_re> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
                 toSRAM_2_we /* inner_sym: __L2Directory_1__DONTTOUCH__38__toSRAM_2_we */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  input  [55:0]  toSRAM_2_rdata /* #hw<innerSym@__L2Directory_1__DONTTOUCH__39__toSRAM_2_rdata> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output         toSRAM_2_ack /* #hw<innerSym@__L2Directory_1__DONTTOUCH__40__toSRAM_2_ack> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
                 toSRAM_2_selectedOH /* inner_sym: __L2Directory_1__DONTTOUCH__41__toSRAM_2_selectedOH */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output [3:0]   toSRAM_2_array /* #hw<innerSym@__L2Directory_1__DONTTOUCH__42__toSRAM_2_array> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output [7:0]   toSRAM_3_addr /* #hw<innerSym@__L2Directory_1__DONTTOUCH__43__toSRAM_3_addr> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
                 toSRAM_3_addr_rd /* inner_sym: __L2Directory_1__DONTTOUCH__44__toSRAM_3_addr_rd */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output [15:0]  toSRAM_3_wdata /* #hw<innerSym@__L2Directory_1__DONTTOUCH__45__toSRAM_3_wdata> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output         toSRAM_3_wmask /* #hw<innerSym@__L2Directory_1__DONTTOUCH__46__toSRAM_3_wmask> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
                 toSRAM_3_re /* inner_sym: __L2Directory_1__DONTTOUCH__47__toSRAM_3_re */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
                 toSRAM_3_we /* inner_sym: __L2Directory_1__DONTTOUCH__48__toSRAM_3_we */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  input  [15:0]  toSRAM_3_rdata /* #hw<innerSym@__L2Directory_1__DONTTOUCH__49__toSRAM_3_rdata> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output         toSRAM_3_ack /* #hw<innerSym@__L2Directory_1__DONTTOUCH__50__toSRAM_3_ack> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
                 toSRAM_3_selectedOH /* inner_sym: __L2Directory_1__DONTTOUCH__51__toSRAM_3_selectedOH */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output [3:0]   toSRAM_3_array /* #hw<innerSym@__L2Directory_1__DONTTOUCH__52__toSRAM_3_array> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output [7:0]   toSRAM_4_addr /* #hw<innerSym@__L2Directory_1__DONTTOUCH__53__toSRAM_4_addr> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
                 toSRAM_4_addr_rd /* inner_sym: __L2Directory_1__DONTTOUCH__54__toSRAM_4_addr_rd */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
                 toSRAM_4_wdata /* inner_sym: __L2Directory_1__DONTTOUCH__55__toSRAM_4_wdata */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
                 toSRAM_4_wmask /* inner_sym: __L2Directory_1__DONTTOUCH__56__toSRAM_4_wmask */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output         toSRAM_4_re /* #hw<innerSym@__L2Directory_1__DONTTOUCH__57__toSRAM_4_re> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
                 toSRAM_4_we /* inner_sym: __L2Directory_1__DONTTOUCH__58__toSRAM_4_we */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  input  [7:0]   toSRAM_4_rdata /* #hw<innerSym@__L2Directory_1__DONTTOUCH__59__toSRAM_4_rdata> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output         toSRAM_4_ack /* #hw<innerSym@__L2Directory_1__DONTTOUCH__60__toSRAM_4_ack> */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
                 toSRAM_4_selectedOH /* inner_sym: __L2Directory_1__DONTTOUCH__61__toSRAM_4_selectedOH */,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
  output [3:0]   toSRAM_4_array /* #hw<innerSym@__L2Directory_1__DONTTOUCH__62__toSRAM_4_array> */	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:186:75
);

  wire [135:0] sramDataOut_4;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:253:14
  wire [135:0] sramDataOut_3;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:253:14
  wire [135:0] sramDataOut_2;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:253:14
  wire [135:0] sramDataOut_1;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:253:20
  wire [135:0] sramDataOut_0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:253:20
  reg  [3:0]   arrayReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:198:35
  reg          reqReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:199:31
  reg          allReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:200:33
  reg          wenReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:203:33
  reg  [7:0]   beReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:204:32
  reg  [7:0]   addrReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:205:34
  reg  [135:0] dataInReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:206:36
  reg          renReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:208:33
  reg  [7:0]   addrRdReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:209:36
  wire         selectedVec_0 = arrayReg == 4'h9;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:191:50, :198:35, :235:50
  wire         doSpread = selectedVec_0 | allReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:200:33, :235:50, :237:33
  assign sramDataOut_0 = selectedVec_0 ? toSRAM_0_rdata : 136'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:206:36, :235:50, :253:20
  wire         selectedVec_0_1 = arrayReg == 4'hA;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:191:50, :198:35, :235:50
  wire         doSpread_1 = selectedVec_0_1 | allReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:200:33, :235:50, :237:33
  assign sramDataOut_1 = selectedVec_0_1 ? toSRAM_1_rdata : 136'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:206:36, :235:50, :253:20
  wire         selectedVec_0_2 = arrayReg == 4'hB;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:191:50, :198:35, :235:50
  wire         doSpread_2 = selectedVec_0_2 | allReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:200:33, :235:50, :237:33
  assign sramDataOut_2 = {80'h0, selectedVec_0_2 ? toSRAM_2_rdata : 56'h0};	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:235:50, :253:{14,20}
  wire         selectedVec_0_3 = arrayReg == 4'hC;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:191:50, :198:35, :235:50
  wire         doSpread_3 = selectedVec_0_3 | allReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:200:33, :235:50, :237:33
  assign sramDataOut_3 = {120'h0, selectedVec_0_3 ? toSRAM_3_rdata : 16'h0};	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:235:50, :253:{14,20}
  wire         selectedVec_0_4 = arrayReg == 4'hD;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:191:50, :198:35, :235:50
  wire         doSpread_4 = selectedVec_0_4 | allReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:200:33, :235:50, :237:33
  assign sramDataOut_4 = {128'h0, selectedVec_0_4 ? toSRAM_4_rdata : 8'h0};	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:204:32, :235:50, :253:{14,20}
  wire         activated =
    mbist_all | mbist_req
    & (mbist_array == 4'h9 | mbist_array == 4'hA | mbist_array == 4'hB | mbist_array == 4'hC | mbist_array == 4'hD);	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:191:{50,76}, :192:{37,50}
  always @(posedge clock or posedge reset) begin	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7
    if (reset) begin	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7
      arrayReg <= 4'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:198:35
      reqReg <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:198:35, :199:31
      allReg <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:198:35, :200:33
      wenReg <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:198:35, :203:33
      beReg <= 8'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:204:32
      addrReg <= 8'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:204:32, :205:34
      dataInReg <= 136'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:206:36
      renReg <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:198:35, :208:33
      addrRdReg <= 8'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:204:32, :209:36
    end
    else begin	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7
      if (activated) begin	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:192:37
        arrayReg <= mbist_array;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:198:35
        allReg <= mbist_all;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:200:33
        wenReg <= mbist_writeen;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:203:33
        renReg <= mbist_readen;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:208:33
      end
      reqReg <= mbist_req;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:199:31
      if (activated & (mbist_readen | mbist_writeen)) begin	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:192:37, :193:{37,53}
        beReg <= mbist_be;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:204:32
        addrReg <= mbist_addr;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:205:34
        dataInReg <= mbist_indata;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:206:36
        addrRdReg <= mbist_addr_rd;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:209:36
      end
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7
      `FIRRTL_BEFORE_INITIAL	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7
      if (reset) begin	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7
        arrayReg = 4'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:198:35
        reqReg = 1'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:198:35, :199:31
        allReg = 1'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:198:35, :200:33
        wenReg = 1'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:198:35, :203:33
        beReg = 8'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:204:32
        addrReg = 8'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:204:32, :205:34
        dataInReg = 136'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:206:36
        renReg = 1'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:198:35, :208:33
        addrRdReg = 8'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:204:32, :209:36
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7
      `FIRRTL_AFTER_INITIAL	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign mbist_ack = reqReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :199:31
  assign mbist_outdata = sramDataOut_0 | sramDataOut_1 | sramDataOut_2 | sramDataOut_3 | sramDataOut_4;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :214:62, :253:{14,20}
  assign toSRAM_0_addr = doSpread ? addrReg : 8'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :204:32, :205:34, :237:33, :240:23
  assign toSRAM_0_addr_rd = doSpread ? addrRdReg : 8'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :204:32, :209:36, :237:33, :241:26
  assign toSRAM_0_wdata = dataInReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :206:36
  assign toSRAM_0_wmask = beReg[3:0];	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :204:32, :245:26
  assign toSRAM_0_re = doSpread & renReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :208:33, :237:33, :243:21
  assign toSRAM_0_we = doSpread & wenReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :203:33, :237:33, :244:21
  assign toSRAM_0_ack = reqReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :199:31
  assign toSRAM_0_selectedOH = allReg | ~reqReg | selectedVec_0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :199:31, :200:33, :235:50, :247:{59,64}
  assign toSRAM_0_array = arrayReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :198:35
  assign toSRAM_1_addr = doSpread_1 ? addrReg : 8'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :204:32, :205:34, :237:33, :240:23
  assign toSRAM_1_addr_rd = doSpread_1 ? addrRdReg : 8'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :204:32, :209:36, :237:33, :241:26
  assign toSRAM_1_wdata = dataInReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :206:36
  assign toSRAM_1_wmask = beReg[3:0];	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :204:32, :245:26
  assign toSRAM_1_re = doSpread_1 & renReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :208:33, :237:33, :243:21
  assign toSRAM_1_we = doSpread_1 & wenReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :203:33, :237:33, :244:21
  assign toSRAM_1_ack = reqReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :199:31
  assign toSRAM_1_selectedOH = allReg | ~reqReg | selectedVec_0_1;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :199:31, :200:33, :235:50, :247:{59,64}
  assign toSRAM_1_array = arrayReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :198:35
  assign toSRAM_2_addr = doSpread_2 ? addrReg : 8'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :204:32, :205:34, :237:33, :240:23
  assign toSRAM_2_addr_rd = doSpread_2 ? addrRdReg : 8'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :204:32, :209:36, :237:33, :241:26
  assign toSRAM_2_wdata = dataInReg[55:0];	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :206:36, :242:30
  assign toSRAM_2_wmask = beReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :204:32
  assign toSRAM_2_re = doSpread_2 & renReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :208:33, :237:33, :243:21
  assign toSRAM_2_we = doSpread_2 & wenReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :203:33, :237:33, :244:21
  assign toSRAM_2_ack = reqReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :199:31
  assign toSRAM_2_selectedOH = allReg | ~reqReg | selectedVec_0_2;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :199:31, :200:33, :235:50, :247:{59,64}
  assign toSRAM_2_array = arrayReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :198:35
  assign toSRAM_3_addr = doSpread_3 ? addrReg : 8'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :204:32, :205:34, :237:33, :240:23
  assign toSRAM_3_addr_rd = doSpread_3 ? addrRdReg : 8'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :204:32, :209:36, :237:33, :241:26
  assign toSRAM_3_wdata = dataInReg[15:0];	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :206:36, :242:30
  assign toSRAM_3_wmask = beReg[0];	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :204:32, :245:26
  assign toSRAM_3_re = doSpread_3 & renReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :208:33, :237:33, :243:21
  assign toSRAM_3_we = doSpread_3 & wenReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :203:33, :237:33, :244:21
  assign toSRAM_3_ack = reqReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :199:31
  assign toSRAM_3_selectedOH = allReg | ~reqReg | selectedVec_0_3;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :199:31, :200:33, :235:50, :247:{59,64}
  assign toSRAM_3_array = arrayReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :198:35
  assign toSRAM_4_addr = doSpread_4 ? addrReg : 8'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :204:32, :205:34, :237:33, :240:23
  assign toSRAM_4_addr_rd = doSpread_4 ? addrRdReg : 8'h0;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :204:32, :209:36, :237:33, :241:26
  assign toSRAM_4_wdata = dataInReg[7:0];	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :206:36, :242:30
  assign toSRAM_4_wmask = beReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :204:32
  assign toSRAM_4_re = doSpread_4 & renReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :208:33, :237:33, :243:21
  assign toSRAM_4_we = doSpread_4 & wenReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :203:33, :237:33, :244:21
  assign toSRAM_4_ack = reqReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :199:31
  assign toSRAM_4_selectedOH = allReg | ~reqReg | selectedVec_0_4;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :199:31, :200:33, :235:50, :247:{59,64}
  assign toSRAM_4_array = arrayReg;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/mbist/MbistPipeline.scala:164:7, :198:35
endmodule

