// Generated by CIRCT firtool-1.135.0
module LeftShiftWordModule_reference(	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Alu.scala:63:7
  input  [4:0]  io_shamt,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Alu.scala:64:14
  input  [31:0] io_sllSrc,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Alu.scala:64:14
  output [31:0] io_sllw	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Alu.scala:64:14
);

  wire [31:0] io_sllw_shifted = io_shamt[4] ? {io_sllSrc[15:0], 16'h0} : io_sllSrc;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/util/ShiftUtils.scala:17:{22,33,48,56}
  wire [31:0] io_sllw_shifted_1 = io_shamt[3] ? {io_sllw_shifted[23:0], 8'h0} : io_sllw_shifted;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/util/ShiftUtils.scala:17:{22,33,48,56}, :18:66
  wire [31:0] io_sllw_shifted_2 = io_shamt[2] ? {io_sllw_shifted_1[27:0], 4'h0} : io_sllw_shifted_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/util/ShiftUtils.scala:17:{22,33,48,56}, :18:66
  wire [31:0] io_sllw_shifted_3 = io_shamt[1] ? {io_sllw_shifted_2[29:0], 2'h0} : io_sllw_shifted_2;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/util/ShiftUtils.scala:17:{22,33,48,56}, :18:66
  assign io_sllw = io_shamt[0] ? {io_sllw_shifted_3[30:0], 1'h0} : io_sllw_shifted_3;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/Alu.scala:63:7, home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/util/ShiftUtils.scala:17:{22,48,56}, :18:66
endmodule

