// Generated by CIRCT firtool-1.135.0
module LqPAddrModule_1_reference(	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:136:7
  input         clock /* #hw<innerSym@sym_6> */,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:136:7
                reset /* inner_sym: sym_3 */,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:136:7
                io_wen_0 /* inner_sym: sym */,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_wen_1 /* inner_sym: sym_0 */,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_wen_2 /* inner_sym: sym_4 */,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
  input  [3:0]  io_waddr_0 /* #hw<innerSym@sym_1> */,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_waddr_1 /* inner_sym: sym_2 */,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_waddr_2 /* inner_sym: sym_5 */,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
  input  [23:0] io_wdata_0,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_wdata_1,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_wdata_2,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMdata_0,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMdata_1,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
  input         io_violationCheckLine_0,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationCheckLine_1,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
  output        io_violationMmask_0_0,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_0_1,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_0_2,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_0_3,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_0_4,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_0_5,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_0_6,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_0_7,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_0_8,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_0_9,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_0_10,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_0_11,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_1_0,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_1_1,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_1_2,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_1_3,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_1_4,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_1_5,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_1_6,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_1_7,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_1_8,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_1_9,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_1_10,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
                io_violationMmask_1_11	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:42:14
);

  wire [23:0] _sx_writeData_resp_pipMod_11_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire [23:0] _sx_writeData_resp_pipMod_10_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire [23:0] _sx_writeData_resp_pipMod_9_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire        _sx_bankWriteEn_delay_11_io_out;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  wire        _sx_bankWriteEn_delay_10_io_out;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  wire        _sx_bankWriteEn_delay_9_io_out;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  wire [2:0]  _sx_bankWriteAddrDec_resp_pipMod_11_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire [2:0]  _sx_bankWriteAddrDec_resp_pipMod_10_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire [2:0]  _sx_bankWriteAddrDec_resp_pipMod_9_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire [23:0] _sx_writeData_resp_pipMod_8_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire [23:0] _sx_writeData_resp_pipMod_7_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire [23:0] _sx_writeData_resp_pipMod_6_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire        _sx_bankWriteEn_delay_8_io_out;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  wire        _sx_bankWriteEn_delay_7_io_out;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  wire        _sx_bankWriteEn_delay_6_io_out;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  wire [2:0]  _sx_bankWriteAddrDec_resp_pipMod_8_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire [2:0]  _sx_bankWriteAddrDec_resp_pipMod_7_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire [2:0]  _sx_bankWriteAddrDec_resp_pipMod_6_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire [23:0] _sx_writeData_resp_pipMod_5_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire [23:0] _sx_writeData_resp_pipMod_4_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire [23:0] _sx_writeData_resp_pipMod_3_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire        _sx_bankWriteEn_delay_5_io_out;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  wire        _sx_bankWriteEn_delay_4_io_out;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  wire        _sx_bankWriteEn_delay_3_io_out;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  wire [2:0]  _sx_bankWriteAddrDec_resp_pipMod_5_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire [2:0]  _sx_bankWriteAddrDec_resp_pipMod_4_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire [2:0]  _sx_bankWriteAddrDec_resp_pipMod_3_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire [23:0] _sx_writeData_resp_pipMod_2_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire [23:0] _sx_writeData_resp_pipMod_1_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire [23:0] _sx_writeData_resp_pipMod_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire        _sx_bankWriteEn_delay_2_io_out;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  wire        _sx_bankWriteEn_delay_1_io_out;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  wire        _sx_bankWriteEn_delay_io_out;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  wire [2:0]  _sx_bankWriteAddrDec_resp_pipMod_2_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire [2:0]  _sx_bankWriteAddrDec_resp_pipMod_1_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  wire [2:0]  _sx_bankWriteAddrDec_resp_pipMod_io_out_bits;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  reg  [23:0] data_0;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17
  reg  [23:0] data_1;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17
  reg  [23:0] data_2;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17
  reg  [23:0] data_3;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17
  reg  [23:0] data_4;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17
  reg  [23:0] data_5;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17
  reg  [23:0] data_6;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17
  reg  [23:0] data_7;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17
  reg  [23:0] data_8;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17
  reg  [23:0] data_9;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17
  reg  [23:0] data_10;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17
  reg  [23:0] data_11;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17
  wire [15:0] writeAddrDec_0 = 16'h1 << io_waddr_0;	// src/main/scala/chisel3/util/OneHot.scala:58:35
  wire [15:0] writeAddrDec_1 = 16'h1 << io_waddr_1;	// src/main/scala/chisel3/util/OneHot.scala:58:35
  wire [15:0] writeAddrDec_2 = 16'h1 << io_waddr_2;	// src/main/scala/chisel3/util/OneHot.scala:58:35
  wire        sx_entryWriteEnVec0_0_0 = _sx_bankWriteEn_delay_io_out & _sx_bankWriteAddrDec_resp_pipMod_io_out_bits[0];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec0_0_1 =
    _sx_bankWriteEn_delay_1_io_out & _sx_bankWriteAddrDec_resp_pipMod_1_io_out_bits[0];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec0_0_2 =
    _sx_bankWriteEn_delay_2_io_out & _sx_bankWriteAddrDec_resp_pipMod_2_io_out_bits[0];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec0_1_0 = _sx_bankWriteEn_delay_io_out & _sx_bankWriteAddrDec_resp_pipMod_io_out_bits[1];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec0_1_1 =
    _sx_bankWriteEn_delay_1_io_out & _sx_bankWriteAddrDec_resp_pipMod_1_io_out_bits[1];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec0_1_2 =
    _sx_bankWriteEn_delay_2_io_out & _sx_bankWriteAddrDec_resp_pipMod_2_io_out_bits[1];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec0_2_0 = _sx_bankWriteEn_delay_io_out & _sx_bankWriteAddrDec_resp_pipMod_io_out_bits[2];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec0_2_1 =
    _sx_bankWriteEn_delay_1_io_out & _sx_bankWriteAddrDec_resp_pipMod_1_io_out_bits[2];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec0_2_2 =
    _sx_bankWriteEn_delay_2_io_out & _sx_bankWriteAddrDec_resp_pipMod_2_io_out_bits[2];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec1_0_0 =
    _sx_bankWriteEn_delay_3_io_out & _sx_bankWriteAddrDec_resp_pipMod_3_io_out_bits[0];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec1_0_1 =
    _sx_bankWriteEn_delay_4_io_out & _sx_bankWriteAddrDec_resp_pipMod_4_io_out_bits[0];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec1_0_2 =
    _sx_bankWriteEn_delay_5_io_out & _sx_bankWriteAddrDec_resp_pipMod_5_io_out_bits[0];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec1_1_0 =
    _sx_bankWriteEn_delay_3_io_out & _sx_bankWriteAddrDec_resp_pipMod_3_io_out_bits[1];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec1_1_1 =
    _sx_bankWriteEn_delay_4_io_out & _sx_bankWriteAddrDec_resp_pipMod_4_io_out_bits[1];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec1_1_2 =
    _sx_bankWriteEn_delay_5_io_out & _sx_bankWriteAddrDec_resp_pipMod_5_io_out_bits[1];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec1_2_0 =
    _sx_bankWriteEn_delay_3_io_out & _sx_bankWriteAddrDec_resp_pipMod_3_io_out_bits[2];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec1_2_1 =
    _sx_bankWriteEn_delay_4_io_out & _sx_bankWriteAddrDec_resp_pipMod_4_io_out_bits[2];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec1_2_2 =
    _sx_bankWriteEn_delay_5_io_out & _sx_bankWriteAddrDec_resp_pipMod_5_io_out_bits[2];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec2_0_0 =
    _sx_bankWriteEn_delay_6_io_out & _sx_bankWriteAddrDec_resp_pipMod_6_io_out_bits[0];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec2_0_1 =
    _sx_bankWriteEn_delay_7_io_out & _sx_bankWriteAddrDec_resp_pipMod_7_io_out_bits[0];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec2_0_2 =
    _sx_bankWriteEn_delay_8_io_out & _sx_bankWriteAddrDec_resp_pipMod_8_io_out_bits[0];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec2_1_0 =
    _sx_bankWriteEn_delay_6_io_out & _sx_bankWriteAddrDec_resp_pipMod_6_io_out_bits[1];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec2_1_1 =
    _sx_bankWriteEn_delay_7_io_out & _sx_bankWriteAddrDec_resp_pipMod_7_io_out_bits[1];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec2_1_2 =
    _sx_bankWriteEn_delay_8_io_out & _sx_bankWriteAddrDec_resp_pipMod_8_io_out_bits[1];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec2_2_0 =
    _sx_bankWriteEn_delay_6_io_out & _sx_bankWriteAddrDec_resp_pipMod_6_io_out_bits[2];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec2_2_1 =
    _sx_bankWriteEn_delay_7_io_out & _sx_bankWriteAddrDec_resp_pipMod_7_io_out_bits[2];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec2_2_2 =
    _sx_bankWriteEn_delay_8_io_out & _sx_bankWriteAddrDec_resp_pipMod_8_io_out_bits[2];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec3_0_0 =
    _sx_bankWriteEn_delay_9_io_out & _sx_bankWriteAddrDec_resp_pipMod_9_io_out_bits[0];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec3_0_1 =
    _sx_bankWriteEn_delay_10_io_out & _sx_bankWriteAddrDec_resp_pipMod_10_io_out_bits[0];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec3_0_2 =
    _sx_bankWriteEn_delay_11_io_out & _sx_bankWriteAddrDec_resp_pipMod_11_io_out_bits[0];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec3_1_0 =
    _sx_bankWriteEn_delay_9_io_out & _sx_bankWriteAddrDec_resp_pipMod_9_io_out_bits[1];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec3_1_1 =
    _sx_bankWriteEn_delay_10_io_out & _sx_bankWriteAddrDec_resp_pipMod_10_io_out_bits[1];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec3_1_2 =
    _sx_bankWriteEn_delay_11_io_out & _sx_bankWriteAddrDec_resp_pipMod_11_io_out_bits[1];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec3_2_0 =
    _sx_bankWriteEn_delay_9_io_out & _sx_bankWriteAddrDec_resp_pipMod_9_io_out_bits[2];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec3_2_1 =
    _sx_bankWriteEn_delay_10_io_out & _sx_bankWriteAddrDec_resp_pipMod_10_io_out_bits[2];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  wire        sx_entryWriteEnVec3_2_2 =
    _sx_bankWriteEn_delay_11_io_out & _sx_bankWriteAddrDec_resp_pipMod_11_io_out_bits[2];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:{86,93}, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23, :134:24
  always @(posedge clock) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:136:7
    if (|{sx_entryWriteEnVec0_0_2, sx_entryWriteEnVec0_0_1, sx_entryWriteEnVec0_0_0})	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:86, :114:{57,64}
      data_0 <=
        (sx_entryWriteEnVec0_0_0 ? _sx_writeData_resp_pipMod_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec0_0_1 ? _sx_writeData_resp_pipMod_1_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec0_0_2 ? _sx_writeData_resp_pipMod_2_io_out_bits : 24'h0);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :113:86, :115:36, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    if (|{sx_entryWriteEnVec0_1_2, sx_entryWriteEnVec0_1_1, sx_entryWriteEnVec0_1_0})	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:86, :114:{57,64}
      data_1 <=
        (sx_entryWriteEnVec0_1_0 ? _sx_writeData_resp_pipMod_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec0_1_1 ? _sx_writeData_resp_pipMod_1_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec0_1_2 ? _sx_writeData_resp_pipMod_2_io_out_bits : 24'h0);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :113:86, :115:36, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    if (|{sx_entryWriteEnVec0_2_2, sx_entryWriteEnVec0_2_1, sx_entryWriteEnVec0_2_0})	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:86, :114:{57,64}
      data_2 <=
        (sx_entryWriteEnVec0_2_0 ? _sx_writeData_resp_pipMod_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec0_2_1 ? _sx_writeData_resp_pipMod_1_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec0_2_2 ? _sx_writeData_resp_pipMod_2_io_out_bits : 24'h0);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :113:86, :115:36, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    if (|{sx_entryWriteEnVec1_0_2, sx_entryWriteEnVec1_0_1, sx_entryWriteEnVec1_0_0})	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:86, :114:{57,64}
      data_3 <=
        (sx_entryWriteEnVec1_0_0 ? _sx_writeData_resp_pipMod_3_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec1_0_1 ? _sx_writeData_resp_pipMod_4_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec1_0_2 ? _sx_writeData_resp_pipMod_5_io_out_bits : 24'h0);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :113:86, :115:36, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    if (|{sx_entryWriteEnVec1_1_2, sx_entryWriteEnVec1_1_1, sx_entryWriteEnVec1_1_0})	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:86, :114:{57,64}
      data_4 <=
        (sx_entryWriteEnVec1_1_0 ? _sx_writeData_resp_pipMod_3_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec1_1_1 ? _sx_writeData_resp_pipMod_4_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec1_1_2 ? _sx_writeData_resp_pipMod_5_io_out_bits : 24'h0);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :113:86, :115:36, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    if (|{sx_entryWriteEnVec1_2_2, sx_entryWriteEnVec1_2_1, sx_entryWriteEnVec1_2_0})	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:86, :114:{57,64}
      data_5 <=
        (sx_entryWriteEnVec1_2_0 ? _sx_writeData_resp_pipMod_3_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec1_2_1 ? _sx_writeData_resp_pipMod_4_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec1_2_2 ? _sx_writeData_resp_pipMod_5_io_out_bits : 24'h0);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :113:86, :115:36, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    if (|{sx_entryWriteEnVec2_0_2, sx_entryWriteEnVec2_0_1, sx_entryWriteEnVec2_0_0})	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:86, :114:{57,64}
      data_6 <=
        (sx_entryWriteEnVec2_0_0 ? _sx_writeData_resp_pipMod_6_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec2_0_1 ? _sx_writeData_resp_pipMod_7_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec2_0_2 ? _sx_writeData_resp_pipMod_8_io_out_bits : 24'h0);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :113:86, :115:36, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    if (|{sx_entryWriteEnVec2_1_2, sx_entryWriteEnVec2_1_1, sx_entryWriteEnVec2_1_0})	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:86, :114:{57,64}
      data_7 <=
        (sx_entryWriteEnVec2_1_0 ? _sx_writeData_resp_pipMod_6_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec2_1_1 ? _sx_writeData_resp_pipMod_7_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec2_1_2 ? _sx_writeData_resp_pipMod_8_io_out_bits : 24'h0);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :113:86, :115:36, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    if (|{sx_entryWriteEnVec2_2_2, sx_entryWriteEnVec2_2_1, sx_entryWriteEnVec2_2_0})	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:86, :114:{57,64}
      data_8 <=
        (sx_entryWriteEnVec2_2_0 ? _sx_writeData_resp_pipMod_6_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec2_2_1 ? _sx_writeData_resp_pipMod_7_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec2_2_2 ? _sx_writeData_resp_pipMod_8_io_out_bits : 24'h0);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :113:86, :115:36, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    if (|{sx_entryWriteEnVec3_0_2, sx_entryWriteEnVec3_0_1, sx_entryWriteEnVec3_0_0})	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:86, :114:{57,64}
      data_9 <=
        (sx_entryWriteEnVec3_0_0 ? _sx_writeData_resp_pipMod_9_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec3_0_1 ? _sx_writeData_resp_pipMod_10_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec3_0_2 ? _sx_writeData_resp_pipMod_11_io_out_bits : 24'h0);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :113:86, :115:36, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    if (|{sx_entryWriteEnVec3_1_2, sx_entryWriteEnVec3_1_1, sx_entryWriteEnVec3_1_0})	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:86, :114:{57,64}
      data_10 <=
        (sx_entryWriteEnVec3_1_0 ? _sx_writeData_resp_pipMod_9_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec3_1_1 ? _sx_writeData_resp_pipMod_10_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec3_1_2 ? _sx_writeData_resp_pipMod_11_io_out_bits : 24'h0);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :113:86, :115:36, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    if (|{sx_entryWriteEnVec3_2_2, sx_entryWriteEnVec3_2_1, sx_entryWriteEnVec3_2_0})	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:113:86, :114:{57,64}
      data_11 <=
        (sx_entryWriteEnVec3_2_0 ? _sx_writeData_resp_pipMod_9_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec3_2_1 ? _sx_writeData_resp_pipMod_10_io_out_bits : 24'h0)
        | (sx_entryWriteEnVec3_2_2 ? _sx_writeData_resp_pipMod_11_io_out_bits : 24'h0);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :113:86, :115:36, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  end // always @(posedge)
  DelayNWithValid_35_reference sx_bankWriteAddrDec_resp_pipMod (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (writeAddrDec_0[2:0]),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_in_valid (io_wen_0),
    .io_out_bits (_sx_bankWriteAddrDec_resp_pipMod_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayNWithValid_35_reference sx_bankWriteAddrDec_resp_pipMod_1 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (writeAddrDec_1[2:0]),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_in_valid (io_wen_1),
    .io_out_bits (_sx_bankWriteAddrDec_resp_pipMod_1_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayNWithValid_35_reference sx_bankWriteAddrDec_resp_pipMod_2 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (writeAddrDec_2[2:0]),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_in_valid (io_wen_2),
    .io_out_bits (_sx_bankWriteAddrDec_resp_pipMod_2_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayN_8_reference sx_bankWriteEn_delay (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
    .clock  (clock),
    .io_in  (io_wen_0 & (|(writeAddrDec_0[2:0]))),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, :86:{72,80}, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_out (_sx_bankWriteEn_delay_io_out)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  DelayN_8_reference sx_bankWriteEn_delay_1 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
    .clock  (clock),
    .io_in  (io_wen_1 & (|(writeAddrDec_1[2:0]))),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, :86:{72,80}, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_out (_sx_bankWriteEn_delay_1_io_out)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  DelayN_8_reference sx_bankWriteEn_delay_2 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
    .clock  (clock),
    .io_in  (io_wen_2 & (|(writeAddrDec_2[2:0]))),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, :86:{72,80}, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_out (_sx_bankWriteEn_delay_2_io_out)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  DelayNWithValid_38_reference sx_writeData_resp_pipMod (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (io_wdata_0),
    .io_in_valid (io_wen_0),
    .io_out_bits (_sx_writeData_resp_pipMod_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayNWithValid_38_reference sx_writeData_resp_pipMod_1 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (io_wdata_1),
    .io_in_valid (io_wen_1),
    .io_out_bits (_sx_writeData_resp_pipMod_1_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayNWithValid_38_reference sx_writeData_resp_pipMod_2 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (io_wdata_2),
    .io_in_valid (io_wen_2),
    .io_out_bits (_sx_writeData_resp_pipMod_2_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayNWithValid_35_reference sx_bankWriteAddrDec_resp_pipMod_3 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (writeAddrDec_0[5:3]),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_in_valid (io_wen_0),
    .io_out_bits (_sx_bankWriteAddrDec_resp_pipMod_3_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayNWithValid_35_reference sx_bankWriteAddrDec_resp_pipMod_4 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (writeAddrDec_1[5:3]),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_in_valid (io_wen_1),
    .io_out_bits (_sx_bankWriteAddrDec_resp_pipMod_4_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayNWithValid_35_reference sx_bankWriteAddrDec_resp_pipMod_5 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (writeAddrDec_2[5:3]),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_in_valid (io_wen_2),
    .io_out_bits (_sx_bankWriteAddrDec_resp_pipMod_5_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayN_8_reference sx_bankWriteEn_delay_3 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
    .clock  (clock),
    .io_in  (io_wen_0 & (|(writeAddrDec_0[5:3]))),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, :86:{72,80}, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_out (_sx_bankWriteEn_delay_3_io_out)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  DelayN_8_reference sx_bankWriteEn_delay_4 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
    .clock  (clock),
    .io_in  (io_wen_1 & (|(writeAddrDec_1[5:3]))),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, :86:{72,80}, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_out (_sx_bankWriteEn_delay_4_io_out)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  DelayN_8_reference sx_bankWriteEn_delay_5 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
    .clock  (clock),
    .io_in  (io_wen_2 & (|(writeAddrDec_2[5:3]))),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, :86:{72,80}, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_out (_sx_bankWriteEn_delay_5_io_out)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  DelayNWithValid_38_reference sx_writeData_resp_pipMod_3 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (io_wdata_0),
    .io_in_valid (io_wen_0),
    .io_out_bits (_sx_writeData_resp_pipMod_3_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayNWithValid_38_reference sx_writeData_resp_pipMod_4 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (io_wdata_1),
    .io_in_valid (io_wen_1),
    .io_out_bits (_sx_writeData_resp_pipMod_4_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayNWithValid_38_reference sx_writeData_resp_pipMod_5 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (io_wdata_2),
    .io_in_valid (io_wen_2),
    .io_out_bits (_sx_writeData_resp_pipMod_5_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayNWithValid_35_reference sx_bankWriteAddrDec_resp_pipMod_6 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (writeAddrDec_0[8:6]),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_in_valid (io_wen_0),
    .io_out_bits (_sx_bankWriteAddrDec_resp_pipMod_6_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayNWithValid_35_reference sx_bankWriteAddrDec_resp_pipMod_7 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (writeAddrDec_1[8:6]),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_in_valid (io_wen_1),
    .io_out_bits (_sx_bankWriteAddrDec_resp_pipMod_7_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayNWithValid_35_reference sx_bankWriteAddrDec_resp_pipMod_8 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (writeAddrDec_2[8:6]),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_in_valid (io_wen_2),
    .io_out_bits (_sx_bankWriteAddrDec_resp_pipMod_8_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayN_8_reference sx_bankWriteEn_delay_6 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
    .clock  (clock),
    .io_in  (io_wen_0 & (|(writeAddrDec_0[8:6]))),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, :86:{72,80}, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_out (_sx_bankWriteEn_delay_6_io_out)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  DelayN_8_reference sx_bankWriteEn_delay_7 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
    .clock  (clock),
    .io_in  (io_wen_1 & (|(writeAddrDec_1[8:6]))),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, :86:{72,80}, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_out (_sx_bankWriteEn_delay_7_io_out)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  DelayN_8_reference sx_bankWriteEn_delay_8 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
    .clock  (clock),
    .io_in  (io_wen_2 & (|(writeAddrDec_2[8:6]))),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, :86:{72,80}, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_out (_sx_bankWriteEn_delay_8_io_out)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  DelayNWithValid_38_reference sx_writeData_resp_pipMod_6 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (io_wdata_0),
    .io_in_valid (io_wen_0),
    .io_out_bits (_sx_writeData_resp_pipMod_6_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayNWithValid_38_reference sx_writeData_resp_pipMod_7 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (io_wdata_1),
    .io_in_valid (io_wen_1),
    .io_out_bits (_sx_writeData_resp_pipMod_7_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayNWithValid_38_reference sx_writeData_resp_pipMod_8 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (io_wdata_2),
    .io_in_valid (io_wen_2),
    .io_out_bits (_sx_writeData_resp_pipMod_8_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayNWithValid_35_reference sx_bankWriteAddrDec_resp_pipMod_9 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (writeAddrDec_0[11:9]),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_in_valid (io_wen_0),
    .io_out_bits (_sx_bankWriteAddrDec_resp_pipMod_9_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayNWithValid_35_reference sx_bankWriteAddrDec_resp_pipMod_10 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (writeAddrDec_1[11:9]),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_in_valid (io_wen_1),
    .io_out_bits (_sx_bankWriteAddrDec_resp_pipMod_10_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayNWithValid_35_reference sx_bankWriteAddrDec_resp_pipMod_11 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (writeAddrDec_2[11:9]),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_in_valid (io_wen_2),
    .io_out_bits (_sx_bankWriteAddrDec_resp_pipMod_11_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayN_8_reference sx_bankWriteEn_delay_9 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
    .clock  (clock),
    .io_in  (io_wen_0 & (|(writeAddrDec_0[11:9]))),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, :86:{72,80}, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_out (_sx_bankWriteEn_delay_9_io_out)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  DelayN_8_reference sx_bankWriteEn_delay_10 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
    .clock  (clock),
    .io_in  (io_wen_1 & (|(writeAddrDec_1[11:9]))),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, :86:{72,80}, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_out (_sx_bankWriteEn_delay_10_io_out)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  DelayN_8_reference sx_bankWriteEn_delay_11 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
    .clock  (clock),
    .io_in  (io_wen_2 & (|(writeAddrDec_2[11:9]))),	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:80:7, :86:{72,80}, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_out (_sx_bankWriteEn_delay_11_io_out)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:104:23
  DelayNWithValid_38_reference sx_writeData_resp_pipMod_9 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (io_wdata_0),
    .io_in_valid (io_wen_0),
    .io_out_bits (_sx_writeData_resp_pipMod_9_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayNWithValid_38_reference sx_writeData_resp_pipMod_10 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (io_wdata_1),
    .io_in_valid (io_wen_1),
    .io_out_bits (_sx_writeData_resp_pipMod_10_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  DelayNWithValid_38_reference sx_writeData_resp_pipMod_11 (	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
    .clock       (clock),
    .io_in_bits  (io_wdata_2),
    .io_in_valid (io_wen_2),
    .io_out_bits (_sx_writeData_resp_pipMod_11_io_out_bits)
  );	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/Hold.scala:134:24
  assign io_violationMmask_0_0 =
    io_violationMdata_0[23:2] == data_0[23:2] & (io_violationCheckLine_0 | io_violationMdata_0[1:0] == data_0[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_0_1 =
    io_violationMdata_0[23:2] == data_1[23:2] & (io_violationCheckLine_0 | io_violationMdata_0[1:0] == data_1[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_0_2 =
    io_violationMdata_0[23:2] == data_2[23:2] & (io_violationCheckLine_0 | io_violationMdata_0[1:0] == data_2[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_0_3 =
    io_violationMdata_0[23:2] == data_3[23:2] & (io_violationCheckLine_0 | io_violationMdata_0[1:0] == data_3[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_0_4 =
    io_violationMdata_0[23:2] == data_4[23:2] & (io_violationCheckLine_0 | io_violationMdata_0[1:0] == data_4[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_0_5 =
    io_violationMdata_0[23:2] == data_5[23:2] & (io_violationCheckLine_0 | io_violationMdata_0[1:0] == data_5[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_0_6 =
    io_violationMdata_0[23:2] == data_6[23:2] & (io_violationCheckLine_0 | io_violationMdata_0[1:0] == data_6[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_0_7 =
    io_violationMdata_0[23:2] == data_7[23:2] & (io_violationCheckLine_0 | io_violationMdata_0[1:0] == data_7[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_0_8 =
    io_violationMdata_0[23:2] == data_8[23:2] & (io_violationCheckLine_0 | io_violationMdata_0[1:0] == data_8[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_0_9 =
    io_violationMdata_0[23:2] == data_9[23:2] & (io_violationCheckLine_0 | io_violationMdata_0[1:0] == data_9[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_0_10 =
    io_violationMdata_0[23:2] == data_10[23:2] & (io_violationCheckLine_0 | io_violationMdata_0[1:0] == data_10[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_0_11 =
    io_violationMdata_0[23:2] == data_11[23:2] & (io_violationCheckLine_0 | io_violationMdata_0[1:0] == data_11[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_1_0 =
    io_violationMdata_1[23:2] == data_0[23:2] & (io_violationCheckLine_1 | io_violationMdata_1[1:0] == data_0[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_1_1 =
    io_violationMdata_1[23:2] == data_1[23:2] & (io_violationCheckLine_1 | io_violationMdata_1[1:0] == data_1[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_1_2 =
    io_violationMdata_1[23:2] == data_2[23:2] & (io_violationCheckLine_1 | io_violationMdata_1[1:0] == data_2[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_1_3 =
    io_violationMdata_1[23:2] == data_3[23:2] & (io_violationCheckLine_1 | io_violationMdata_1[1:0] == data_3[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_1_4 =
    io_violationMdata_1[23:2] == data_4[23:2] & (io_violationCheckLine_1 | io_violationMdata_1[1:0] == data_4[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_1_5 =
    io_violationMdata_1[23:2] == data_5[23:2] & (io_violationCheckLine_1 | io_violationMdata_1[1:0] == data_5[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_1_6 =
    io_violationMdata_1[23:2] == data_6[23:2] & (io_violationCheckLine_1 | io_violationMdata_1[1:0] == data_6[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_1_7 =
    io_violationMdata_1[23:2] == data_7[23:2] & (io_violationCheckLine_1 | io_violationMdata_1[1:0] == data_7[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_1_8 =
    io_violationMdata_1[23:2] == data_8[23:2] & (io_violationCheckLine_1 | io_violationMdata_1[1:0] == data_8[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_1_9 =
    io_violationMdata_1[23:2] == data_9[23:2] & (io_violationCheckLine_1 | io_violationMdata_1[1:0] == data_9[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_1_10 =
    io_violationMdata_1[23:2] == data_10[23:2] & (io_violationCheckLine_1 | io_violationMdata_1[1:0] == data_10[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
  assign io_violationMmask_1_11 =
    io_violationMdata_1[23:2] == data_11[23:2] & (io_violationCheckLine_1 | io_violationMdata_1[1:0] == data_11[1:0]);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:71:17, :136:7, :156:{51,84,95}, :157:{51,76,87}, :158:{49,82}
endmodule

