// Generated by CIRCT firtool-1.135.0
module MaxPeriodFibonacciLFSR_reference(	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
  input  clock,	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
         reset,	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
  output io_out_0,	// src/main/scala/chisel3/util/random/PRNG.scala:42:22
         io_out_1,	// src/main/scala/chisel3/util/random/PRNG.scala:42:22
         io_out_2,	// src/main/scala/chisel3/util/random/PRNG.scala:42:22
         io_out_3,	// src/main/scala/chisel3/util/random/PRNG.scala:42:22
         io_out_4,	// src/main/scala/chisel3/util/random/PRNG.scala:42:22
         io_out_5,	// src/main/scala/chisel3/util/random/PRNG.scala:42:22
         io_out_6,	// src/main/scala/chisel3/util/random/PRNG.scala:42:22
         io_out_7,	// src/main/scala/chisel3/util/random/PRNG.scala:42:22
         io_out_8,	// src/main/scala/chisel3/util/random/PRNG.scala:42:22
         io_out_9,	// src/main/scala/chisel3/util/random/PRNG.scala:42:22
         io_out_10,	// src/main/scala/chisel3/util/random/PRNG.scala:42:22
         io_out_11,	// src/main/scala/chisel3/util/random/PRNG.scala:42:22
         io_out_12,	// src/main/scala/chisel3/util/random/PRNG.scala:42:22
         io_out_13,	// src/main/scala/chisel3/util/random/PRNG.scala:42:22
         io_out_14	// src/main/scala/chisel3/util/random/PRNG.scala:42:22
);

  reg state_0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
  reg state_1;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
  reg state_2;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
  reg state_3;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
  reg state_4;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
  reg state_5;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
  reg state_6;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
  reg state_7;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
  reg state_8;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
  reg state_9;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
  reg state_10;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
  reg state_11;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
  reg state_12;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
  reg state_13;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
  reg state_14;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
  always @(posedge clock or posedge reset) begin	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
    if (reset) begin	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
      state_0 <= 1'h1;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_1 <= 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_2 <= 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_3 <= 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_4 <= 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_5 <= 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_6 <= 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_7 <= 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_8 <= 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_9 <= 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_10 <= 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_11 <= 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_12 <= 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_13 <= 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_14 <= 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
    end
    else begin	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
      state_0 <= state_13 ^ state_14;	// src/main/scala/chisel3/util/random/LFSR.scala:15:41, src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_1 <= state_0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_2 <= state_1;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_3 <= state_2;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_4 <= state_3;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_5 <= state_4;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_6 <= state_5;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_7 <= state_6;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_8 <= state_7;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_9 <= state_8;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_10 <= state_9;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_11 <= state_10;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_12 <= state_11;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_13 <= state_12;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      state_14 <= state_13;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
      if (reset) begin	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
        state_0 = 1'h1;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
        state_1 = 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
        state_2 = 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
        state_3 = 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
        state_4 = 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
        state_5 = 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
        state_6 = 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
        state_7 = 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
        state_8 = 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
        state_9 = 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
        state_10 = 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
        state_11 = 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
        state_12 = 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
        state_13 = 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
        state_14 = 1'h0;	// src/main/scala/chisel3/util/random/PRNG.scala:55:49
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_0 = state_0;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
  assign io_out_1 = state_1;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
  assign io_out_2 = state_2;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
  assign io_out_3 = state_3;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
  assign io_out_4 = state_4;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
  assign io_out_5 = state_5;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
  assign io_out_6 = state_6;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
  assign io_out_7 = state_7;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
  assign io_out_8 = state_8;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
  assign io_out_9 = state_9;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
  assign io_out_10 = state_10;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
  assign io_out_11 = state_11;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
  assign io_out_12 = state_12;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
  assign io_out_13 = state_13;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
  assign io_out_14 = state_14;	// src/main/scala/chisel3/util/random/FibonacciLFSR.scala:65:7, src/main/scala/chisel3/util/random/PRNG.scala:55:49
endmodule

