// Generated by CIRCT firtool-1.135.0
module MtopiModule_reference(	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRAIA.scala:22:26
  output [63:0] rdata,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:20:17
  input  [11:0] topIR_mtopi_IID,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRAIA.scala:266:17
  input  [7:0]  topIR_mtopi_IPRIO	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRAIA.scala:266:17
);

  assign rdata = {36'h0, topIR_mtopi_IID, 8'h0, topIR_mtopi_IPRIO};	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRAIA.scala:22:26, home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:48:24
endmodule

