// Generated by CIRCT firtool-1.135.0
module PlruStateGen(	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/PlruStateGen.scala:29:7
  input  [6:0] io_state,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/ReplacerStateGen.scala:32:34
  input        io_touches_0_valid,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/ReplacerStateGen.scala:32:34
               io_touches_1_valid,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/ReplacerStateGen.scala:32:34
               io_touches_2_valid,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/ReplacerStateGen.scala:32:34
               io_touches_3_valid,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/ReplacerStateGen.scala:32:34
               io_touches_4_valid,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/ReplacerStateGen.scala:32:34
               io_touches_5_valid,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/ReplacerStateGen.scala:32:34
               io_touches_6_valid,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/ReplacerStateGen.scala:32:34
               io_touches_7_valid,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/ReplacerStateGen.scala:32:34
  output [6:0] io_nextState	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/ReplacerStateGen.scala:32:34
);

  wire [6:0] _io_nextState_T_23 = io_touches_0_valid ? {1'h1, io_state[5:3], 1'h1, io_state[1], 1'h1} : io_state;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/util/package.scala:155:13, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/PlruStateGen.scala:81:31, :83:36, :87:12, :89:14, :94:14, :122:7, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/ReplacerStateGen.scala:35:54
  wire [6:0] _io_nextState_T_47 =
    io_touches_1_valid ? {1'h1, _io_nextState_T_23[5:3], 1'h1, _io_nextState_T_23[1], 1'h0} : _io_nextState_T_23;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/util/package.scala:155:13, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/PlruStateGen.scala:81:31, :83:36, :87:12, :89:14, :94:14, :122:7, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/ReplacerStateGen.scala:35:54
  wire [6:0] _io_nextState_T_71 =
    io_touches_2_valid ? {1'h1, _io_nextState_T_47[5:3], 2'h1, _io_nextState_T_47[0]} : _io_nextState_T_47;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/util/package.scala:155:13, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/PlruStateGen.scala:81:31, :83:36, :87:12, :89:14, :94:14, :122:7, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/ReplacerStateGen.scala:35:54
  wire [6:0] _io_nextState_T_95 =
    io_touches_3_valid ? {1'h1, _io_nextState_T_71[5:3], 2'h0, _io_nextState_T_71[0]} : _io_nextState_T_71;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/util/package.scala:155:13, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/PlruStateGen.scala:81:31, :83:36, :87:12, :89:14, :94:14, :122:7, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/ReplacerStateGen.scala:35:54
  wire [6:0] _io_nextState_T_119 =
    io_touches_4_valid ? {2'h1, _io_nextState_T_95[4], 1'h1, _io_nextState_T_95[2:0]} : _io_nextState_T_95;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/util/package.scala:155:13, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/PlruStateGen.scala:81:31, :83:36, :87:12, :89:14, :94:14, :122:7, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/ReplacerStateGen.scala:35:54
  wire [6:0] _io_nextState_T_143 =
    io_touches_5_valid ? {2'h1, _io_nextState_T_119[4], 1'h0, _io_nextState_T_119[2:0]} : _io_nextState_T_119;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/util/package.scala:155:13, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/PlruStateGen.scala:81:31, :83:36, :87:12, :89:14, :94:14, :122:7, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/ReplacerStateGen.scala:35:54
  wire [6:0] _io_nextState_T_167 = io_touches_6_valid ? {3'h1, _io_nextState_T_143[3:0]} : _io_nextState_T_143;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/PlruStateGen.scala:87:12, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/ReplacerStateGen.scala:35:54
  assign io_nextState = io_touches_7_valid ? {3'h0, _io_nextState_T_167[3:0]} : _io_nextState_T_167;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/PlruStateGen.scala:29:7, :87:12, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/replacer/ReplacerStateGen.scala:35:54
endmodule

