// Generated by CIRCT firtool-1.135.0
module Queue1_RegMapperInput_1(	// src/main/scala/chisel3/util/Queue.scala:60:7
  input         clock,	// src/main/scala/chisel3/util/Queue.scala:60:7
                reset,	// src/main/scala/chisel3/util/Queue.scala:60:7
  output        io_enq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input         io_enq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
                io_enq_bits_read,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [8:0]  io_enq_bits_index,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [63:0] io_enq_bits_data,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [7:0]  io_enq_bits_mask,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [4:0]  io_enq_bits_extra_tlrr_extra_source,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [1:0]  io_enq_bits_extra_tlrr_extra_size,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input         io_deq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output        io_deq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
                io_deq_bits_read,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [8:0]  io_deq_bits_index,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [63:0] io_deq_bits_data,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [7:0]  io_deq_bits_mask,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [4:0]  io_deq_bits_extra_tlrr_extra_source,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [1:0]  io_deq_bits_extra_tlrr_extra_size	// src/main/scala/chisel3/util/Queue.scala:72:14
);

  reg  [88:0] ram;	// src/main/scala/chisel3/util/Queue.scala:73:91
  reg         maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27
  wire        do_enq = ~maybe_full & io_enq_valid;	// src/main/scala/chisel3/util/Queue.scala:76:27, :103:19, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  always @(posedge clock or posedge reset) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
    if (reset)	// src/main/scala/chisel3/util/Queue.scala:60:7
      maybe_full <= 1'h0;	// src/main/scala/chisel3/util/Queue.scala:76:27
    else if (do_enq != (io_deq_ready & maybe_full))	// src/main/scala/chisel3/util/Queue.scala:76:27, :93:{15,27}, :94:16, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      maybe_full <= do_enq;	// src/main/scala/chisel3/util/Queue.scala:76:27, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  end // always @(posedge, posedge)
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
    if (do_enq)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      ram <=
        {io_enq_bits_read,
         io_enq_bits_index,
         io_enq_bits_data,
         io_enq_bits_mask,
         io_enq_bits_extra_tlrr_extra_source,
         io_enq_bits_extra_tlrr_extra_size};	// src/main/scala/chisel3/util/Queue.scala:73:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Queue.scala:60:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      if (reset)	// src/main/scala/chisel3/util/Queue.scala:60:7
        maybe_full = 1'h0;	// src/main/scala/chisel3/util/Queue.scala:76:27
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_enq_ready = ~maybe_full;	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27, :103:19
  assign io_deq_valid = maybe_full;	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
  assign io_deq_bits_read = ram[88];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_index = ram[87:79];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_data = ram[78:15];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_mask = ram[14:7];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_extra_tlrr_extra_source = ram[6:2];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_extra_tlrr_extra_size = ram[1:0];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
endmodule

