// Generated by CIRCT firtool-1.135.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module RefillBuffer_reference(	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7
  input          clock,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7
                 reset,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7
                 io_r_valid,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:29:14
                 io_r_beat,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:29:14
  input  [3:0]   io_r_id,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:29:14
  output         io_r_ready,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:29:14
  output [255:0] io_r_buffer_data_data,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:29:14
  output         io_r_buffer_data_corrupt,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:29:14
  input          io_r_last,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:29:14
                 io_w_valid,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:29:14
                 io_w_beat,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:29:14
  input  [255:0] io_w_data_data,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:29:14
  output         io_w_ready,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:29:14
  output [3:0]   io_w_id	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:29:14
);

  wire [513:0] _buffer_ext_R0_data;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:34:19
  reg          valids_0_0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
  reg          valids_0_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
  reg          valids_1_0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
  reg          valids_1_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
  reg          valids_2_0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
  reg          valids_2_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
  reg          valids_3_0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
  reg          valids_3_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
  reg          valids_4_0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
  reg          valids_4_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
  reg          valids_5_0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
  reg          valids_5_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
  reg          valids_6_0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
  reg          valids_6_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
  wire [7:0]   _GEN =
    {{valids_0_0}, {valids_6_0}, {valids_5_0}, {valids_4_0}, {valids_3_0}, {valids_2_0}, {valids_1_0}, {valids_0_0}};	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :45:11
  wire [7:0]   _GEN_0 =
    {{valids_0_1}, {valids_6_1}, {valids_5_1}, {valids_4_1}, {valids_3_1}, {valids_2_1}, {valids_1_1}, {valids_0_1}};	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :45:11
  wire         io_r_ready_0 = io_r_beat ? _GEN_0[io_r_id[2:0]] : _GEN[io_r_id[2:0]];	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:44:26, :45:11
  reg          io_w_ready_REG;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:59:33
  wire         io_w_ready_0 = io_w_beat | io_w_ready_REG;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:59:{17,33}
  reg  [2:0]   io_w_id_REG;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:61:12
  wire         buffer_MPORT_en = io_w_valid & io_w_ready_0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:59:17, :62:29
  reg  [3:0]   io_w_id_r;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:62:14
  wire [3:0]   _GEN_1 = {1'h0, io_w_id_REG};	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:60:14, :61:12
  wire [3:0]   io_w_id_0 = io_w_beat ? io_w_id_r : _GEN_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:60:14, :62:14
  `ifndef SYNTHESIS	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:48:11
    always @(posedge clock) begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:48:11
      if (io_r_valid & ~io_r_beat & ~reset & ~io_r_ready_0) begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:45:11, :47:{16,26}, :48:11
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:48:11
          $error("Assertion failed: [%d] first beat must hit!\n", io_r_id);	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:48:11
        if (`STOP_COND_)	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:48:11
          $fatal;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:48:11
      end
      if (buffer_MPORT_en & ~reset & (io_w_beat ? _GEN_0[io_w_id_0[2:0]] : _GEN[io_w_id_0[2:0]])) begin	// <stdin>:5775731:19, home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:45:11, :48:11, :60:14, :62:29, :65:16, :66:{11,12}
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:66:11
          $error("Assertion failed: [%d] attempt to write a valid entry\n", io_w_id_0);	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:60:14, :66:11
        if (`STOP_COND_)	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:66:11
          $fatal;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:66:11
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire         _GEN_2 = io_r_valid & io_r_ready_0 & io_r_last;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:45:11, :51:{16,27}
  wire         _GEN_3 = _GEN_2 & io_r_id[2:0] == 3'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :44:26, :51:{16,27,36}, :53:28, src/main/scala/chisel3/util/Mux.scala:58:84
  wire         _GEN_4 = _GEN_2 & io_r_id[2:0] == 3'h1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :44:26, :51:{16,27,36}, :53:28
  wire         _GEN_5 = _GEN_2 & io_r_id[2:0] == 3'h2;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :44:26, :51:{16,27,36}, :53:28
  wire         _GEN_6 = _GEN_2 & io_r_id[2:0] == 3'h3;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :44:26, :51:{16,27,36}, :53:28
  wire         _GEN_7 = _GEN_2 & io_r_id[2:0] == 3'h4;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :44:26, :51:{16,27,36}, :53:28
  wire         _GEN_8 = _GEN_2 & io_r_id[2:0] == 3'h5;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :44:26, :51:{16,27,36}, :53:28
  wire         _GEN_9 = _GEN_2 & io_r_id[2:0] == 3'h6;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :44:26, :51:{16,27,36}, :53:28
  wire [1:0]   _validMask_T = {valids_0_1, valids_0_0};	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :56:49
  wire [1:0]   _validMask_T_2 = {valids_1_1, valids_1_0};	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :56:49
  wire [1:0]   _validMask_T_4 = {valids_2_1, valids_2_0};	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :56:49
  wire [1:0]   _validMask_T_6 = {valids_3_1, valids_3_0};	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :56:49
  wire [1:0]   _validMask_T_8 = {valids_4_1, valids_4_0};	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :56:49
  wire [1:0]   _validMask_T_10 = {valids_5_1, valids_5_0};	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :56:49
  wire [5:0]   _freeIdx_T =
    ~{|_validMask_T_10, |_validMask_T_8, |_validMask_T_6, |_validMask_T_4, |_validMask_T_2, |_validMask_T};	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:56:{49,56,62}, :57:33
  wire         _GEN_10 = io_w_id_0[2:0] == 3'h0;	// <stdin>:5775731:19, home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:60:14, :67:26, src/main/scala/chisel3/util/Mux.scala:58:84
  wire         _GEN_11 = io_w_id_0[2:0] == 3'h1;	// <stdin>:5775731:19, home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:60:14, :67:26
  wire         _GEN_12 = io_w_id_0[2:0] == 3'h2;	// <stdin>:5775731:19, home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:60:14, :67:26
  wire         _GEN_13 = io_w_id_0[2:0] == 3'h3;	// <stdin>:5775731:19, home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:60:14, :67:26
  wire         _GEN_14 = io_w_id_0[2:0] == 3'h4;	// <stdin>:5775731:19, home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:60:14, :67:26
  wire         _GEN_15 = io_w_id_0[2:0] == 3'h5;	// <stdin>:5775731:19, home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:60:14, :67:26
  wire         _GEN_16 = io_w_id_0[2:0] == 3'h6;	// <stdin>:5775731:19, home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:60:14, :67:26
  always @(posedge clock or posedge reset) begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7
    if (reset) begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7
      valids_0_0 <= 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
      valids_0_1 <= 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
      valids_1_0 <= 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
      valids_1_1 <= 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
      valids_2_0 <= 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
      valids_2_1 <= 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
      valids_3_0 <= 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
      valids_3_1 <= 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
      valids_4_0 <= 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
      valids_4_1 <= 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
      valids_5_0 <= 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
      valids_5_1 <= 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
      valids_6_0 <= 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
      valids_6_1 <= 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
      io_w_ready_REG <= 1'h1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7, :59:33
      io_w_id_REG <= 3'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:61:12, src/main/scala/chisel3/util/Mux.scala:58:84
    end
    else begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7
      valids_0_0 <= buffer_MPORT_en & _GEN_10 & ~io_w_beat | ~_GEN_3 & valids_0_0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :51:36, :53:28, :62:29, :65:27, :67:26
      valids_0_1 <= buffer_MPORT_en & _GEN_10 & io_w_beat | ~_GEN_3 & valids_0_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :51:36, :53:28, :62:29, :65:27, :67:26
      valids_1_0 <= buffer_MPORT_en & _GEN_11 & ~io_w_beat | ~_GEN_4 & valids_1_0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :51:36, :53:28, :62:29, :65:27, :67:26
      valids_1_1 <= buffer_MPORT_en & _GEN_11 & io_w_beat | ~_GEN_4 & valids_1_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :51:36, :53:28, :62:29, :65:27, :67:26
      valids_2_0 <= buffer_MPORT_en & _GEN_12 & ~io_w_beat | ~_GEN_5 & valids_2_0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :51:36, :53:28, :62:29, :65:27, :67:26
      valids_2_1 <= buffer_MPORT_en & _GEN_12 & io_w_beat | ~_GEN_5 & valids_2_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :51:36, :53:28, :62:29, :65:27, :67:26
      valids_3_0 <= buffer_MPORT_en & _GEN_13 & ~io_w_beat | ~_GEN_6 & valids_3_0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :51:36, :53:28, :62:29, :65:27, :67:26
      valids_3_1 <= buffer_MPORT_en & _GEN_13 & io_w_beat | ~_GEN_6 & valids_3_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :51:36, :53:28, :62:29, :65:27, :67:26
      valids_4_0 <= buffer_MPORT_en & _GEN_14 & ~io_w_beat | ~_GEN_7 & valids_4_0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :51:36, :53:28, :62:29, :65:27, :67:26
      valids_4_1 <= buffer_MPORT_en & _GEN_14 & io_w_beat | ~_GEN_7 & valids_4_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :51:36, :53:28, :62:29, :65:27, :67:26
      valids_5_0 <= buffer_MPORT_en & _GEN_15 & ~io_w_beat | ~_GEN_8 & valids_5_0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :51:36, :53:28, :62:29, :65:27, :67:26
      valids_5_1 <= buffer_MPORT_en & _GEN_15 & io_w_beat | ~_GEN_8 & valids_5_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :51:36, :53:28, :62:29, :65:27, :67:26
      valids_6_0 <= buffer_MPORT_en & _GEN_16 & ~io_w_beat | ~_GEN_9 & valids_6_0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :51:36, :53:28, :62:29, :65:27, :67:26
      valids_6_1 <= buffer_MPORT_en & _GEN_16 & io_w_beat | ~_GEN_9 & valids_6_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :51:36, :53:28, :62:29, :65:27, :67:26
      io_w_ready_REG <=
        {|{valids_6_1, valids_6_0},
         |_validMask_T_10,
         |_validMask_T_8,
         |_validMask_T_6,
         |_validMask_T_4,
         |_validMask_T_2,
         |_validMask_T} != 7'h7F;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23, :56:{49,56,62}, :57:33, :59:{33,45}
      io_w_id_REG <=
        _freeIdx_T[0]
          ? 3'h0
          : _freeIdx_T[1]
              ? 3'h1
              : _freeIdx_T[2] ? 3'h2 : _freeIdx_T[3] ? 3'h3 : _freeIdx_T[4] ? 3'h4 : _freeIdx_T[5] ? 3'h5 : 3'h6;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:57:33, :61:12, src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/chisel3/util/OneHot.scala:48:45
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7
    if (~(buffer_MPORT_en & ~io_w_beat) | io_w_beat) begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:42:23, :62:{14,29,40}
    end
    else	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:62:14
      io_w_id_r <= _GEN_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:60:14, :62:14
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7
      `FIRRTL_BEFORE_INITIAL	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7
      if (reset) begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7
        valids_0_0 = 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
        valids_0_1 = 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
        valids_1_0 = 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
        valids_1_1 = 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
        valids_2_0 = 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
        valids_2_1 = 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
        valids_3_0 = 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
        valids_3_1 = 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
        valids_4_0 = 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
        valids_4_1 = 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
        valids_5_0 = 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
        valids_5_1 = 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
        valids_6_0 = 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
        valids_6_1 = 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:35:23
        io_w_ready_REG = 1'h1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7, :59:33
        io_w_id_REG = 3'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:61:12, src/main/scala/chisel3/util/Mux.scala:58:84
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7
      `FIRRTL_AFTER_INITIAL	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  buffer_7x514 buffer_ext (	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:34:19
    .R0_addr (io_r_id[2:0]),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:44:26
    .R0_en   (1'h1),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7
    .R0_clk  (clock),
    .R0_data (_buffer_ext_R0_data),
    .W0_addr (io_w_id_0[2:0]),	// <stdin>:5775731:19, home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:60:14
    .W0_en   (buffer_MPORT_en),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:62:29
    .W0_clk  (clock),
    .W0_data ({io_w_data_data, 1'h0, io_w_data_data, 1'h0}),	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:34:19
    .W0_mask ({{257{io_w_beat}}, {257{~io_w_beat}}})	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:34:19, :67:26
  );	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:34:19
  assign io_r_ready = io_r_ready_0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7, :45:11
  assign io_r_buffer_data_data = io_r_beat ? _buffer_ext_R0_data[513:258] : _buffer_ext_R0_data[256:1];	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7, :34:19, :44:17
  assign io_r_buffer_data_corrupt = io_r_beat ? _buffer_ext_R0_data[257] : _buffer_ext_R0_data[0];	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7, :34:19, :44:17
  assign io_w_ready = io_w_ready_0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7, :59:17
  assign io_w_id = io_w_id_0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/huancun/src/main/scala/huancun/RefillBuffer.scala:28:7, :60:14
endmodule

