// Generated by CIRCT firtool-1.135.0
module ShiftLeftPriorityWithF32EXPResult_reference(	// home/davide/gitdir/bianco/XiangShan/yunsuan/src/main/scala/yunsuan/vector/VectorFloatAdder.scala:711:7
  input  [9:0] io_src,	// home/davide/gitdir/bianco/XiangShan/yunsuan/src/main/scala/yunsuan/vector/VectorFloatAdder.scala:712:14
               io_priority_shiftValue,	// home/davide/gitdir/bianco/XiangShan/yunsuan/src/main/scala/yunsuan/vector/VectorFloatAdder.scala:712:14
  output [9:0] io_lshift_result,	// home/davide/gitdir/bianco/XiangShan/yunsuan/src/main/scala/yunsuan/vector/VectorFloatAdder.scala:712:14
  output [7:0] io_exp_result	// home/davide/gitdir/bianco/XiangShan/yunsuan/src/main/scala/yunsuan/vector/VectorFloatAdder.scala:712:14
);

  wire [17:0] lshift_result_lzd_exp =
    io_priority_shiftValue[9]
      ? {io_src, 8'h70}
      : io_priority_shiftValue[8]
          ? {io_src[8:0], 9'h6F}
          : io_priority_shiftValue[7]
              ? {io_src[7:0], 10'h6E}
              : io_priority_shiftValue[6]
                  ? {io_src[6:0], 11'h6D}
                  : io_priority_shiftValue[5]
                      ? {io_src[5:0], 12'h6C}
                      : io_priority_shiftValue[4]
                          ? {io_src[4:0], 13'h6B}
                          : io_priority_shiftValue[3]
                              ? {io_src[3:0], 14'h6A}
                              : io_priority_shiftValue[2]
                                  ? {io_src[2:0], 15'h69}
                                  : io_priority_shiftValue[1]
                                      ? {io_src[1:0], 16'h68}
                                      : {io_priority_shiftValue[0] ? {io_src[0], 9'h0} : 10'h0,
                                         7'h33,
                                         io_priority_shiftValue[0]};	// home/davide/gitdir/bianco/XiangShan/yunsuan/src/main/scala/yunsuan/vector/VectorFloatAdder.scala:722:20, :723:12, :724:29, :725:{14,23}, :728:12, :734:15, :735:27, :736:{28,56,85,98}
  assign io_lshift_result = lshift_result_lzd_exp[17:8];	// home/davide/gitdir/bianco/XiangShan/yunsuan/src/main/scala/yunsuan/vector/VectorFloatAdder.scala:711:7, :734:15, :743:49
  assign io_exp_result = lshift_result_lzd_exp[7:0];	// home/davide/gitdir/bianco/XiangShan/yunsuan/src/main/scala/yunsuan/vector/VectorFloatAdder.scala:711:7, :734:15, :744:46
endmodule

