// Generated by CIRCT firtool-1.135.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module TLError_reference(	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:18:9
  input        clock,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:18:9
               reset,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:18:9
  output       auto_in_a_ready,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input        auto_in_a_valid,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input  [3:0] auto_in_a_bits_opcode,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input        auto_in_d_ready,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output       auto_in_d_valid,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [3:0] auto_in_d_bits_opcode,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output       auto_in_d_bits_denied,	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
               auto_in_d_bits_corrupt	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
);

  wire             da_ready;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Arbiter.scala:94:31
  wire [3:0]       da_bits_opcode;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:35:21
  wire [15:0][3:0] _GEN =
    '{4'h0, 4'h0, 4'h0, 4'h0, 4'h0, 4'h8, 4'h8, 4'h8, 4'h4, 4'h4, 4'h2, 4'h1, 4'h1, 4'h1, 4'h0, 4'h0};	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:35:21
  reg              idle;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:26:23
  reg              r_counter;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27
  wire             da_valid = auto_in_a_valid & idle;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:26:23, :33:35
  assign da_bits_opcode = _GEN[auto_in_a_bits_opcode];	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:35:21
  reg              beatsLeft;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Arbiter.scala:60:30
  `ifndef SYNTHESIS	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:31:12
    always @(posedge clock) begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:31:12
      if (~reset & ~(idle | ~r_counter)) begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:26:23, :31:{12,18}, home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:31:12
          $error("Assertion failed at Error.scala:31\n");	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:31:12
        if (`STOP_COND_)	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:31:12
          $fatal;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:31:12
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  reg              state_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Arbiter.scala:88:26
  wire             muxState_1 = beatsLeft ? state_1 : da_valid;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:33:35, home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Arbiter.scala:60:30, :88:26, :89:25
  assign da_ready = auto_in_d_ready & (~beatsLeft | state_1);	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Arbiter.scala:60:30, :61:28, :88:26, :92:24, :94:31
  wire             nodeIn_d_valid = (~beatsLeft | state_1) & da_valid;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:33:35, home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Arbiter.scala:60:30, :61:28, :88:26, :96:{24,57}
  wire             r_3 = da_ready & da_valid;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:33:35, home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Arbiter.scala:94:31, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  always @(posedge clock or posedge reset) begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:18:9
    if (reset) begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:18:9
      idle <= 1'h1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:26:23
      r_counter <= 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27
      beatsLeft <= 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Arbiter.scala:60:30
      state_1 <= 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Arbiter.scala:88:26
    end
    else begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:18:9
      idle <= ~(r_3 & da_bits_opcode == 4'h4) & idle;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:26:23, :35:21, :52:{21,39,50,57}, home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Bundles.scala:54:27, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      r_counter <= (~r_3 | r_counter - 1'h1) & r_counter;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :230:28, :235:17, :236:15, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      beatsLeft <= ~(~beatsLeft & auto_in_d_ready) & beatsLeft - (auto_in_d_ready & nodeIn_d_valid);	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Arbiter.scala:60:30, :61:28, :62:24, :85:{23,52}, :96:{24,57}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      if (beatsLeft) begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Arbiter.scala:60:30
      end
      else	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Arbiter.scala:60:30
        state_1 <= da_valid;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:33:35, home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Arbiter.scala:88:26
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:18:9
    `ifdef FIRRTL_BEFORE_INITIAL	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:18:9
      `FIRRTL_BEFORE_INITIAL	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:18:9
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:18:9
      if (reset) begin	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:18:9
        idle = 1'h1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:26:23
        r_counter = 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27
        beatsLeft = 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Arbiter.scala:60:30
        state_1 = 1'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Arbiter.scala:88:26
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:18:9
      `FIRRTL_AFTER_INITIAL	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:18:9
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign auto_in_a_ready = da_ready & idle;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:18:9, :26:23, :32:37, home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Arbiter.scala:94:31
  assign auto_in_d_valid = nodeIn_d_valid;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:18:9, home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Arbiter.scala:96:{24,57}
  assign auto_in_d_bits_opcode = muxState_1 ? da_bits_opcode : 4'h0;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:18:9, :35:21, home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Arbiter.scala:89:25, :97:26
  assign auto_in_d_bits_denied = muxState_1;	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:18:9, home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Arbiter.scala:89:25
  assign auto_in_d_bits_corrupt = muxState_1 & da_bits_opcode[0];	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/devices/tilelink/Error.scala:18:9, :35:21, home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Arbiter.scala:89:25, :97:26, home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36
endmodule

