// Generated by CIRCT firtool-1.135.0
module TLToAXI4_reference(	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9
  input          clock /* #hw<innerSym@sym_147> */,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9
                 reset /* inner_sym: sym_1 */,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9
  output         auto_in_a_ready,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input          auto_in_a_valid,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input  [3:0]   auto_in_a_bits_opcode,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input  [2:0]   auto_in_a_bits_size,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input  [5:0]   auto_in_a_bits_source,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input  [47:0]  auto_in_a_bits_address,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input  [31:0]  auto_in_a_bits_mask,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input  [255:0] auto_in_a_bits_data,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input          auto_in_d_ready,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output         auto_in_d_valid,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [3:0]   auto_in_d_bits_opcode,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [2:0]   auto_in_d_bits_size,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [5:0]   auto_in_d_bits_source,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output         auto_in_d_bits_denied,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [255:0] auto_in_d_bits_data,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output         auto_in_d_bits_corrupt,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input          auto_out_aw_ready,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output         auto_out_aw_valid,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [5:0]   auto_out_aw_bits_id,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [47:0]  auto_out_aw_bits_addr,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [7:0]   auto_out_aw_bits_len,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [2:0]   auto_out_aw_bits_size,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [1:0]   auto_out_aw_bits_burst,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output         auto_out_aw_bits_lock,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [3:0]   auto_out_aw_bits_cache,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [2:0]   auto_out_aw_bits_prot,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [3:0]   auto_out_aw_bits_qos,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
                 auto_out_aw_bits_echo_tl_state_size,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [5:0]   auto_out_aw_bits_echo_tl_state_source,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input          auto_out_w_ready,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output         auto_out_w_valid,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [255:0] auto_out_w_bits_data,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [31:0]  auto_out_w_bits_strb,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output         auto_out_w_bits_last,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
                 auto_out_b_ready,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input          auto_out_b_valid,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input  [5:0]   auto_out_b_bits_id,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input  [1:0]   auto_out_b_bits_resp,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input  [3:0]   auto_out_b_bits_echo_tl_state_size,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input  [5:0]   auto_out_b_bits_echo_tl_state_source,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input          auto_out_ar_ready,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output         auto_out_ar_valid,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [5:0]   auto_out_ar_bits_id,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [47:0]  auto_out_ar_bits_addr,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [7:0]   auto_out_ar_bits_len,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [2:0]   auto_out_ar_bits_size,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [1:0]   auto_out_ar_bits_burst,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output         auto_out_ar_bits_lock,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [3:0]   auto_out_ar_bits_cache,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [2:0]   auto_out_ar_bits_prot,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [3:0]   auto_out_ar_bits_qos,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
                 auto_out_ar_bits_echo_tl_state_size,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output [5:0]   auto_out_ar_bits_echo_tl_state_source,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  output         auto_out_r_ready,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input          auto_out_r_valid,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input  [5:0]   auto_out_r_bits_id,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input  [255:0] auto_out_r_bits_data,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input  [1:0]   auto_out_r_bits_resp,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input  [3:0]   auto_out_r_bits_echo_tl_state_size,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input  [5:0]   auto_out_r_bits_echo_tl_state_source,	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
  input          auto_out_r_bits_last	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:365:18
);

  reg              count_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_47;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_46;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_45;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_44;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_43;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_42;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_41;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_40;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_39;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_38;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_37;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_36;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_35;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_34;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_33;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_32;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_31;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_30;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_29;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_28;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_27;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_26;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_25;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_24;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_23;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_22;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_21;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_20;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_19;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_18;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_17;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_16;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_15;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_14;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_13;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_12;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_11;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_10;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_9;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_8;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_7;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_6;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_5;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_4;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_3;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_2;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count_1;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  reg              count;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             _queue_arw_deq_q_io_enq_ready;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire             _queue_arw_deq_q_io_deq_valid;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire [5:0]       _queue_arw_deq_q_io_deq_bits_id;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire [47:0]      _queue_arw_deq_q_io_deq_bits_addr;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire [7:0]       _queue_arw_deq_q_io_deq_bits_len;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire [2:0]       _queue_arw_deq_q_io_deq_bits_size;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire [1:0]       _queue_arw_deq_q_io_deq_bits_burst;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire             _queue_arw_deq_q_io_deq_bits_lock;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire [3:0]       _queue_arw_deq_q_io_deq_bits_cache;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire [2:0]       _queue_arw_deq_q_io_deq_bits_prot;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire [3:0]       _queue_arw_deq_q_io_deq_bits_qos;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire [3:0]       _queue_arw_deq_q_io_deq_bits_echo_tl_state_size;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire [5:0]       _queue_arw_deq_q_io_deq_bits_echo_tl_state_source;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire             _queue_arw_deq_q_io_deq_bits_wen;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire             _nodeOut_w_deq_q_io_enq_ready;	// src/main/scala/chisel3/util/Queue.scala:200:21
  wire [63:0][5:0] _GEN =
    '{6'h30,
      6'h2F,
      6'h2E,
      6'h2D,
      6'h2C,
      6'h2B,
      6'h2A,
      6'h29,
      6'h28,
      6'h27,
      6'h26,
      6'h25,
      6'h24,
      6'h23,
      6'h22,
      6'h21,
      6'h20,
      6'h1F,
      6'h1E,
      6'h1D,
      6'h1C,
      6'h1B,
      6'h1A,
      6'h19,
      6'h18,
      6'h17,
      6'h16,
      6'h15,
      6'h14,
      6'h13,
      6'h12,
      6'h11,
      6'h0,
      6'h0,
      6'h0,
      6'h0,
      6'h0,
      6'h0,
      6'h0,
      6'h0,
      6'h0,
      6'h0,
      6'h0,
      6'h0,
      6'h0,
      6'h0,
      6'h0,
      6'h10,
      6'hF,
      6'hE,
      6'hD,
      6'hC,
      6'hB,
      6'hA,
      6'h9,
      6'h8,
      6'h7,
      6'h6,
      6'h5,
      6'h4,
      6'h3,
      6'h2,
      6'h1,
      6'h0};	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:165:17
  wire [12:0]      _r_beats1_decode_T = 13'h3F << auto_in_a_bits_size;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/util/package.scala:235:71
  wire             r_beats1 = ~(auto_in_a_bits_opcode[2]) & ~(_r_beats1_decode_T[5]);	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Edges.scala:92:{28,37}, :221:14, home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/util/package.scala:235:{46,71,76}
  reg              r_counter;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27
  wire             a_last = r_counter | ~r_beats1;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Edges.scala:221:14, :229:27, :232:{33,43}
  reg              doneAW;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:160:30
  wire [19:0]      _out_arw_bits_len_T = 20'h1FFF << auto_in_a_bits_size;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/util/package.scala:235:71
  wire [63:0]      _GEN_0 =
    {{count_48},
     {count_47},
     {count_46},
     {count_45},
     {count_44},
     {count_43},
     {count_42},
     {count_41},
     {count_40},
     {count_39},
     {count_38},
     {count_37},
     {count_36},
     {count_35},
     {count_34},
     {count_33},
     {count_32},
     {count_31},
     {count_30},
     {count_29},
     {count_28},
     {count_27},
     {count_26},
     {count_25},
     {count_24},
     {count_23},
     {count_22},
     {count_21},
     {count_20},
     {count_19},
     {count_18},
     {count_17},
     {1'h0},
     {1'h0},
     {1'h0},
     {1'h0},
     {1'h0},
     {1'h0},
     {1'h0},
     {1'h0},
     {1'h0},
     {1'h0},
     {1'h0},
     {1'h0},
     {1'h0},
     {1'h0},
     {1'h0},
     {count_16},
     {count_15},
     {count_14},
     {count_13},
     {count_12},
     {count_11},
     {count_10},
     {count_9},
     {count_8},
     {count_7},
     {count_6},
     {count_5},
     {count_4},
     {count_3},
     {count_2},
     {count_1},
     {count}};	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:198:49, :265:28
  wire             stall = _GEN_0[auto_in_a_bits_source] & ~r_counter;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25, home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:198:49
  wire             _out_w_valid_T_3 = doneAW | _queue_arw_deq_q_io_enq_ready;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:160:30, :199:52, src/main/scala/chisel3/util/Queue.scala:200:21
  wire             nodeIn_a_ready =
    ~stall
    & (auto_in_a_bits_opcode[2] ? _queue_arw_deq_q_io_enq_ready : _out_w_valid_T_3 & _nodeOut_w_deq_q_io_enq_ready);	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Edges.scala:92:37, home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:198:49, :199:{21,28,34,52,70}, src/main/scala/chisel3/util/Queue.scala:200:21
  wire             out_arw_valid =
    ~stall & auto_in_a_valid & (auto_in_a_bits_opcode[2] | ~doneAW & _nodeOut_w_deq_q_io_enq_ready);	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Edges.scala:92:37, home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:160:30, :198:49, :199:21, :200:{31,45,51,61,69}, src/main/scala/chisel3/util/Queue.scala:200:21
  reg              r_holds_d;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:209:30
  reg  [2:0]       b_delay;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:212:24
  wire             r_wins = auto_out_r_valid & b_delay != 3'h7 | r_holds_d;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:209:30, :212:24, :218:{33,44,53}
  wire             nodeOut_r_ready = auto_in_d_ready & r_wins;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:218:53, :220:33
  wire             nodeOut_b_ready = auto_in_d_ready & ~r_wins;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:218:53, :221:{33,36}
  wire             nodeIn_d_valid = r_wins ? auto_out_r_valid : auto_out_b_valid;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:218:53, :222:24
  reg              r_first;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:227:28
  reg              r_denied_r;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/util/package.scala:80:63
  wire             r_denied = r_first ? (&auto_out_r_bits_resp) : r_denied_r;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:227:28, :229:39, home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/util/package.scala:80:{42,63}
  wire [63:0]      _a_sel_T = 64'h1 << _GEN[auto_in_a_bits_source];	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:165:17, src/main/scala/chisel3/util/OneHot.scala:65:12
  wire [63:0]      _d_sel_T_1 = 64'h1 << (r_wins ? auto_out_r_bits_id : auto_out_b_bits_id);	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:218:53, :254:31, src/main/scala/chisel3/util/OneHot.scala:65:12
  wire             d_last = ~r_wins | auto_out_r_bits_last;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:218:53, :255:23
  wire             count_0 /* #hw<innerSym@sym_0> */ = count;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             _inc_T_48 = _queue_arw_deq_q_io_enq_ready & out_arw_valid;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:200:{31,45}, src/main/scala/chisel3/util/Queue.scala:200:21, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             inc /* #hw<innerSym@sym_2> */ = _a_sel_T[0] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             _dec_T_97 = auto_in_d_ready & nodeIn_d_valid;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:222:24, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec /* #hw<innerSym@sym> */ = _d_sel_T_1[0] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_1_0 /* #hw<innerSym@sym_4> */ = count_1;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_1 /* #hw<innerSym@sym_5> */ = _a_sel_T[1] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_1 /* #hw<innerSym@sym_3> */ = _d_sel_T_1[1] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_2_0 /* #hw<innerSym@sym_7> */ = count_2;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_2 /* #hw<innerSym@sym_8> */ = _a_sel_T[2] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_2 /* #hw<innerSym@sym_6> */ = _d_sel_T_1[2] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_3_0 /* #hw<innerSym@sym_10> */ = count_3;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_3 /* #hw<innerSym@sym_11> */ = _a_sel_T[3] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_3 /* #hw<innerSym@sym_9> */ = _d_sel_T_1[3] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_4_0 /* #hw<innerSym@sym_13> */ = count_4;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_4 /* #hw<innerSym@sym_14> */ = _a_sel_T[4] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_4 /* #hw<innerSym@sym_12> */ = _d_sel_T_1[4] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_5_0 /* #hw<innerSym@sym_16> */ = count_5;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_5 /* #hw<innerSym@sym_17> */ = _a_sel_T[5] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_5 /* #hw<innerSym@sym_15> */ = _d_sel_T_1[5] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_6_0 /* #hw<innerSym@sym_19> */ = count_6;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_6 /* #hw<innerSym@sym_20> */ = _a_sel_T[6] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_6 /* #hw<innerSym@sym_18> */ = _d_sel_T_1[6] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_7_0 /* #hw<innerSym@sym_22> */ = count_7;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_7 /* #hw<innerSym@sym_23> */ = _a_sel_T[7] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_7 /* #hw<innerSym@sym_21> */ = _d_sel_T_1[7] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_8_0 /* #hw<innerSym@sym_25> */ = count_8;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_8 /* #hw<innerSym@sym_26> */ = _a_sel_T[8] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_8 /* #hw<innerSym@sym_24> */ = _d_sel_T_1[8] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_9_0 /* #hw<innerSym@sym_28> */ = count_9;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_9 /* #hw<innerSym@sym_29> */ = _a_sel_T[9] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_9 /* #hw<innerSym@sym_27> */ = _d_sel_T_1[9] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_10_0 /* #hw<innerSym@sym_31> */ = count_10;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_10 /* #hw<innerSym@sym_32> */ = _a_sel_T[10] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_10 /* #hw<innerSym@sym_30> */ = _d_sel_T_1[10] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_11_0 /* #hw<innerSym@sym_34> */ = count_11;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_11 /* #hw<innerSym@sym_35> */ = _a_sel_T[11] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_11 /* #hw<innerSym@sym_33> */ = _d_sel_T_1[11] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_12_0 /* #hw<innerSym@sym_37> */ = count_12;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_12 /* #hw<innerSym@sym_38> */ = _a_sel_T[12] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_12 /* #hw<innerSym@sym_36> */ = _d_sel_T_1[12] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_13_0 /* #hw<innerSym@sym_40> */ = count_13;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_13 /* #hw<innerSym@sym_41> */ = _a_sel_T[13] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_13 /* #hw<innerSym@sym_39> */ = _d_sel_T_1[13] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_14_0 /* #hw<innerSym@sym_43> */ = count_14;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_14 /* #hw<innerSym@sym_44> */ = _a_sel_T[14] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_14 /* #hw<innerSym@sym_42> */ = _d_sel_T_1[14] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_15_0 /* #hw<innerSym@sym_46> */ = count_15;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_15 /* #hw<innerSym@sym_47> */ = _a_sel_T[15] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_15 /* #hw<innerSym@sym_45> */ = _d_sel_T_1[15] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_16_0 /* #hw<innerSym@sym_49> */ = count_16;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_16 /* #hw<innerSym@sym_50> */ = _a_sel_T[16] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_16 /* #hw<innerSym@sym_48> */ = _d_sel_T_1[16] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_17_0 /* #hw<innerSym@sym_52> */ = count_17;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_17 /* #hw<innerSym@sym_53> */ = _a_sel_T[17] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_17 /* #hw<innerSym@sym_51> */ = _d_sel_T_1[17] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_18_0 /* #hw<innerSym@sym_55> */ = count_18;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_18 /* #hw<innerSym@sym_56> */ = _a_sel_T[18] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_18 /* #hw<innerSym@sym_54> */ = _d_sel_T_1[18] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_19_0 /* #hw<innerSym@sym_58> */ = count_19;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_19 /* #hw<innerSym@sym_59> */ = _a_sel_T[19] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_19 /* #hw<innerSym@sym_57> */ = _d_sel_T_1[19] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_20_0 /* #hw<innerSym@sym_61> */ = count_20;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_20 /* #hw<innerSym@sym_62> */ = _a_sel_T[20] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_20 /* #hw<innerSym@sym_60> */ = _d_sel_T_1[20] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_21_0 /* #hw<innerSym@sym_64> */ = count_21;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_21 /* #hw<innerSym@sym_65> */ = _a_sel_T[21] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_21 /* #hw<innerSym@sym_63> */ = _d_sel_T_1[21] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_22_0 /* #hw<innerSym@sym_67> */ = count_22;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_22 /* #hw<innerSym@sym_68> */ = _a_sel_T[22] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_22 /* #hw<innerSym@sym_66> */ = _d_sel_T_1[22] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_23_0 /* #hw<innerSym@sym_70> */ = count_23;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_23 /* #hw<innerSym@sym_71> */ = _a_sel_T[23] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_23 /* #hw<innerSym@sym_69> */ = _d_sel_T_1[23] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_24_0 /* #hw<innerSym@sym_73> */ = count_24;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_24 /* #hw<innerSym@sym_74> */ = _a_sel_T[24] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_24 /* #hw<innerSym@sym_72> */ = _d_sel_T_1[24] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_25_0 /* #hw<innerSym@sym_76> */ = count_25;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_25 /* #hw<innerSym@sym_77> */ = _a_sel_T[25] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_25 /* #hw<innerSym@sym_75> */ = _d_sel_T_1[25] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_26_0 /* #hw<innerSym@sym_79> */ = count_26;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_26 /* #hw<innerSym@sym_80> */ = _a_sel_T[26] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_26 /* #hw<innerSym@sym_78> */ = _d_sel_T_1[26] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_27_0 /* #hw<innerSym@sym_82> */ = count_27;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_27 /* #hw<innerSym@sym_83> */ = _a_sel_T[27] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_27 /* #hw<innerSym@sym_81> */ = _d_sel_T_1[27] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_28_0 /* #hw<innerSym@sym_85> */ = count_28;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_28 /* #hw<innerSym@sym_86> */ = _a_sel_T[28] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_28 /* #hw<innerSym@sym_84> */ = _d_sel_T_1[28] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_29_0 /* #hw<innerSym@sym_88> */ = count_29;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_29 /* #hw<innerSym@sym_89> */ = _a_sel_T[29] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_29 /* #hw<innerSym@sym_87> */ = _d_sel_T_1[29] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_30_0 /* #hw<innerSym@sym_91> */ = count_30;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_30 /* #hw<innerSym@sym_92> */ = _a_sel_T[30] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_30 /* #hw<innerSym@sym_90> */ = _d_sel_T_1[30] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_31_0 /* #hw<innerSym@sym_94> */ = count_31;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_31 /* #hw<innerSym@sym_95> */ = _a_sel_T[31] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_31 /* #hw<innerSym@sym_93> */ = _d_sel_T_1[31] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_32_0 /* #hw<innerSym@sym_97> */ = count_32;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_32 /* #hw<innerSym@sym_98> */ = _a_sel_T[32] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_32 /* #hw<innerSym@sym_96> */ = _d_sel_T_1[32] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_33_0 /* #hw<innerSym@sym_100> */ = count_33;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_33 /* #hw<innerSym@sym_101> */ = _a_sel_T[33] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_33 /* #hw<innerSym@sym_99> */ = _d_sel_T_1[33] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_34_0 /* #hw<innerSym@sym_103> */ = count_34;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_34 /* #hw<innerSym@sym_104> */ = _a_sel_T[34] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_34 /* #hw<innerSym@sym_102> */ = _d_sel_T_1[34] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_35_0 /* #hw<innerSym@sym_106> */ = count_35;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_35 /* #hw<innerSym@sym_107> */ = _a_sel_T[35] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_35 /* #hw<innerSym@sym_105> */ = _d_sel_T_1[35] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_36_0 /* #hw<innerSym@sym_109> */ = count_36;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_36 /* #hw<innerSym@sym_110> */ = _a_sel_T[36] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_36 /* #hw<innerSym@sym_108> */ = _d_sel_T_1[36] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_37_0 /* #hw<innerSym@sym_112> */ = count_37;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_37 /* #hw<innerSym@sym_113> */ = _a_sel_T[37] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_37 /* #hw<innerSym@sym_111> */ = _d_sel_T_1[37] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_38_0 /* #hw<innerSym@sym_115> */ = count_38;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_38 /* #hw<innerSym@sym_116> */ = _a_sel_T[38] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_38 /* #hw<innerSym@sym_114> */ = _d_sel_T_1[38] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_39_0 /* #hw<innerSym@sym_118> */ = count_39;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_39 /* #hw<innerSym@sym_119> */ = _a_sel_T[39] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_39 /* #hw<innerSym@sym_117> */ = _d_sel_T_1[39] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_40_0 /* #hw<innerSym@sym_121> */ = count_40;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_40 /* #hw<innerSym@sym_122> */ = _a_sel_T[40] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_40 /* #hw<innerSym@sym_120> */ = _d_sel_T_1[40] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_41_0 /* #hw<innerSym@sym_124> */ = count_41;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_41 /* #hw<innerSym@sym_125> */ = _a_sel_T[41] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_41 /* #hw<innerSym@sym_123> */ = _d_sel_T_1[41] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_42_0 /* #hw<innerSym@sym_127> */ = count_42;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_42 /* #hw<innerSym@sym_128> */ = _a_sel_T[42] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_42 /* #hw<innerSym@sym_126> */ = _d_sel_T_1[42] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_43_0 /* #hw<innerSym@sym_130> */ = count_43;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_43 /* #hw<innerSym@sym_131> */ = _a_sel_T[43] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_43 /* #hw<innerSym@sym_129> */ = _d_sel_T_1[43] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_44_0 /* #hw<innerSym@sym_133> */ = count_44;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_44 /* #hw<innerSym@sym_134> */ = _a_sel_T[44] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_44 /* #hw<innerSym@sym_132> */ = _d_sel_T_1[44] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_45_0 /* #hw<innerSym@sym_136> */ = count_45;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_45 /* #hw<innerSym@sym_137> */ = _a_sel_T[45] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_45 /* #hw<innerSym@sym_135> */ = _d_sel_T_1[45] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_46_0 /* #hw<innerSym@sym_139> */ = count_46;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_46 /* #hw<innerSym@sym_140> */ = _a_sel_T[46] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_46 /* #hw<innerSym@sym_138> */ = _d_sel_T_1[46] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_47_0 /* #hw<innerSym@sym_142> */ = count_47;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_47 /* #hw<innerSym@sym_143> */ = _a_sel_T[47] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_47 /* #hw<innerSym@sym_141> */ = _d_sel_T_1[47] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             count_48_0 /* #hw<innerSym@sym_145> */ = count_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
  wire             inc_48 /* #hw<innerSym@sym_146> */ = _a_sel_T[48] & _inc_T_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:253:58, :269:22, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire             dec_48 /* #hw<innerSym@sym_144> */ = _d_sel_T_1[48] & d_last & _dec_T_97;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:254:93, :255:23, :270:{22,32}, src/main/scala/chisel3/util/OneHot.scala:65:{12,33}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  always @(posedge clock or posedge reset) begin	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9
    if (reset) begin	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9
      r_counter <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27
      doneAW <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:160:30
      r_holds_d <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:209:30
      r_first <= 1'h1;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:227:28
      count <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_1 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_2 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_3 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_4 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_5 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_6 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_7 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_8 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_9 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_10 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_11 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_12 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_13 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_14 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_15 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_16 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_17 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_18 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_19 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_20 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_21 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_22 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_23 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_24 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_25 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_26 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_27 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_28 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_29 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_30 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_31 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_32 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_33 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_34 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_35 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_36 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_37 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_38 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_39 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_40 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_41 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_42 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_43 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_44 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_45 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_46 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_47 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      count_48 <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
    end
    else begin	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9
      if (nodeIn_a_ready & auto_in_a_valid) begin	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:199:28, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        r_counter <= ~r_counter & r_beats1;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Edges.scala:221:14, :229:27, :236:21
        doneAW <= ~a_last;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Edges.scala:232:33, home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:160:30, :161:36
      end
      if (nodeOut_r_ready & auto_out_r_valid) begin	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:220:33, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        r_holds_d <= ~auto_out_r_bits_last;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:209:30, :210:40
        r_first <= auto_out_r_bits_last;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:227:28
      end
      count <= count + inc - dec;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_1 <= count_1 + inc_1 - dec_1;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_2 <= count_2 + inc_2 - dec_2;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_3 <= count_3 + inc_3 - dec_3;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_4 <= count_4 + inc_4 - dec_4;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_5 <= count_5 + inc_5 - dec_5;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_6 <= count_6 + inc_6 - dec_6;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_7 <= count_7 + inc_7 - dec_7;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_8 <= count_8 + inc_8 - dec_8;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_9 <= count_9 + inc_9 - dec_9;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_10 <= count_10 + inc_10 - dec_10;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_11 <= count_11 + inc_11 - dec_11;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_12 <= count_12 + inc_12 - dec_12;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_13 <= count_13 + inc_13 - dec_13;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_14 <= count_14 + inc_14 - dec_14;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_15 <= count_15 + inc_15 - dec_15;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_16 <= count_16 + inc_16 - dec_16;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_17 <= count_17 + inc_17 - dec_17;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_18 <= count_18 + inc_18 - dec_18;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_19 <= count_19 + inc_19 - dec_19;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_20 <= count_20 + inc_20 - dec_20;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_21 <= count_21 + inc_21 - dec_21;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_22 <= count_22 + inc_22 - dec_22;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_23 <= count_23 + inc_23 - dec_23;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_24 <= count_24 + inc_24 - dec_24;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_25 <= count_25 + inc_25 - dec_25;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_26 <= count_26 + inc_26 - dec_26;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_27 <= count_27 + inc_27 - dec_27;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_28 <= count_28 + inc_28 - dec_28;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_29 <= count_29 + inc_29 - dec_29;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_30 <= count_30 + inc_30 - dec_30;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_31 <= count_31 + inc_31 - dec_31;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_32 <= count_32 + inc_32 - dec_32;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_33 <= count_33 + inc_33 - dec_33;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_34 <= count_34 + inc_34 - dec_34;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_35 <= count_35 + inc_35 - dec_35;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_36 <= count_36 + inc_36 - dec_36;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_37 <= count_37 + inc_37 - dec_37;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_38 <= count_38 + inc_38 - dec_38;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_39 <= count_39 + inc_39 - dec_39;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_40 <= count_40 + inc_40 - dec_40;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_41 <= count_41 + inc_41 - dec_41;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_42 <= count_42 + inc_42 - dec_42;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_43 <= count_43 + inc_43 - dec_43;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_44 <= count_44 + inc_44 - dec_44;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_45 <= count_45 + inc_45 - dec_45;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_46 <= count_46 + inc_46 - dec_46;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_47 <= count_47 + inc_47 - dec_47;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
      count_48 <= count_48 + inc_48 - dec_48;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28, :269:22, :270:32, :271:{24,37}
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9
    b_delay <= auto_out_b_valid & ~nodeOut_b_ready ? b_delay + 3'h1 : 3'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Edges.scala:831:15, home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:212:24, :213:{25,28,42}, :214:{17,28}, :216:17, :221:33
    if (r_first)	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:227:28
      r_denied_r <= &auto_out_r_bits_resp;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:229:39, home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/util/package.scala:80:63
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9
    `ifdef FIRRTL_BEFORE_INITIAL	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9
      `FIRRTL_BEFORE_INITIAL	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9
      if (reset) begin	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9
        r_counter = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27
        doneAW = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:160:30
        r_holds_d = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:209:30
        r_first = 1'h1;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:227:28
        count = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_1 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_2 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_3 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_4 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_5 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_6 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_7 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_8 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_9 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_10 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_11 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_12 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_13 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_14 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_15 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_16 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_17 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_18 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_19 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_20 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_21 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_22 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_23 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_24 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_25 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_26 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_27 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_28 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_29 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_30 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_31 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_32 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_33 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_34 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_35 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_36 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_37 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_38 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_39 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_40 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_41 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_42 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_43 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_44 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_45 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_46 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_47 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
        count_48 = 1'h0;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:265:28
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9
      `FIRRTL_AFTER_INITIAL	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Queue1_AXI4BundleW_reference nodeOut_w_deq_q (	// src/main/scala/chisel3/util/Queue.scala:200:21
    .clock            (clock),
    .reset            (reset),
    .io_enq_ready     (_nodeOut_w_deq_q_io_enq_ready),
    .io_enq_valid     (~stall & auto_in_a_valid & ~(auto_in_a_bits_opcode[2]) & _out_w_valid_T_3),	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Edges.scala:92:{28,37}, home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:198:49, :199:{21,52}, :202:{29,43,54}
    .io_enq_bits_data (auto_in_a_bits_data),
    .io_enq_bits_strb (auto_in_a_bits_mask),
    .io_enq_bits_last (a_last),	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Edges.scala:232:33
    .io_deq_ready     (auto_out_w_ready),
    .io_deq_valid     (auto_out_w_valid),
    .io_deq_bits_data (auto_out_w_bits_data),
    .io_deq_bits_strb (auto_out_w_bits_strb),
    .io_deq_bits_last (auto_out_w_bits_last)
  );	// src/main/scala/chisel3/util/Queue.scala:200:21
  Queue1_AXI4BundleARW_reference queue_arw_deq_q (	// src/main/scala/chisel3/util/Queue.scala:200:21
    .clock                            (clock),
    .reset                            (reset),
    .io_enq_ready                     (_queue_arw_deq_q_io_enq_ready),
    .io_enq_valid                     (out_arw_valid),	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:200:{31,45}
    .io_enq_bits_id                   (_GEN[auto_in_a_bits_source]),	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:165:17
    .io_enq_bits_addr                 (auto_in_a_bits_address),
    .io_enq_bits_len                  (~(_out_arw_bits_len_T[12:5])),	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/util/package.scala:235:{46,71,76}
    .io_enq_bits_size                 (auto_in_a_bits_size > 3'h4 ? 3'h5 : auto_in_a_bits_size),	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:115:39, :168:{23,31}
    .io_enq_bits_echo_tl_state_size   ({1'h0, auto_in_a_bits_size}),	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:182:22
    .io_enq_bits_echo_tl_state_source (auto_in_a_bits_source),
    .io_enq_bits_wen                  (~(auto_in_a_bits_opcode[2])),	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Edges.scala:92:{28,37}
    .io_deq_ready                     (_queue_arw_deq_q_io_deq_bits_wen ? auto_out_aw_ready : auto_out_ar_ready),	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:156:29, src/main/scala/chisel3/util/Queue.scala:200:21
    .io_deq_valid                     (_queue_arw_deq_q_io_deq_valid),
    .io_deq_bits_id                   (_queue_arw_deq_q_io_deq_bits_id),
    .io_deq_bits_addr                 (_queue_arw_deq_q_io_deq_bits_addr),
    .io_deq_bits_len                  (_queue_arw_deq_q_io_deq_bits_len),
    .io_deq_bits_size                 (_queue_arw_deq_q_io_deq_bits_size),
    .io_deq_bits_burst                (_queue_arw_deq_q_io_deq_bits_burst),
    .io_deq_bits_lock                 (_queue_arw_deq_q_io_deq_bits_lock),
    .io_deq_bits_cache                (_queue_arw_deq_q_io_deq_bits_cache),
    .io_deq_bits_prot                 (_queue_arw_deq_q_io_deq_bits_prot),
    .io_deq_bits_qos                  (_queue_arw_deq_q_io_deq_bits_qos),
    .io_deq_bits_echo_tl_state_size   (_queue_arw_deq_q_io_deq_bits_echo_tl_state_size),
    .io_deq_bits_echo_tl_state_source (_queue_arw_deq_q_io_deq_bits_echo_tl_state_source),
    .io_deq_bits_wen                  (_queue_arw_deq_q_io_deq_bits_wen)
  );	// src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_in_a_ready = nodeIn_a_ready;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, :199:28
  assign auto_in_d_valid = nodeIn_d_valid;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, :222:24
  assign auto_in_d_bits_opcode = {3'h0, r_wins};	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, :218:53, :248:23
  assign auto_in_d_bits_size =
    r_wins ? auto_out_r_bits_echo_tl_state_size[2:0] : auto_out_b_bits_echo_tl_state_size[2:0];	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Edges.scala:815:15, :833:15, home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, :218:53, :248:23
  assign auto_in_d_bits_source = r_wins ? auto_out_r_bits_echo_tl_state_source : auto_out_b_bits_echo_tl_state_source;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, :218:53, :248:23
  assign auto_in_d_bits_denied = r_wins ? r_denied : (|auto_out_b_bits_resp);	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, :218:53, :231:39, :248:23, home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/util/package.scala:80:42
  assign auto_in_d_bits_data = auto_out_r_bits_data;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9
  assign auto_in_d_bits_corrupt = r_wins & ((|auto_out_r_bits_resp) | r_denied);	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, :218:53, :230:39, :233:96, :248:23, home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/util/package.scala:80:42
  assign auto_out_aw_valid = _queue_arw_deq_q_io_deq_valid & _queue_arw_deq_q_io_deq_bits_wen;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, :155:39, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_aw_bits_id = _queue_arw_deq_q_io_deq_bits_id;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_aw_bits_addr = _queue_arw_deq_q_io_deq_bits_addr;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_aw_bits_len = _queue_arw_deq_q_io_deq_bits_len;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_aw_bits_size = _queue_arw_deq_q_io_deq_bits_size;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_aw_bits_burst = _queue_arw_deq_q_io_deq_bits_burst;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_aw_bits_lock = _queue_arw_deq_q_io_deq_bits_lock;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_aw_bits_cache = _queue_arw_deq_q_io_deq_bits_cache;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_aw_bits_prot = _queue_arw_deq_q_io_deq_bits_prot;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_aw_bits_qos = _queue_arw_deq_q_io_deq_bits_qos;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_aw_bits_echo_tl_state_size = _queue_arw_deq_q_io_deq_bits_echo_tl_state_size;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_aw_bits_echo_tl_state_source = _queue_arw_deq_q_io_deq_bits_echo_tl_state_source;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_b_ready = nodeOut_b_ready;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, :221:33
  assign auto_out_ar_valid = _queue_arw_deq_q_io_deq_valid & ~_queue_arw_deq_q_io_deq_bits_wen;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, :154:{39,42}, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_ar_bits_id = _queue_arw_deq_q_io_deq_bits_id;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_ar_bits_addr = _queue_arw_deq_q_io_deq_bits_addr;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_ar_bits_len = _queue_arw_deq_q_io_deq_bits_len;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_ar_bits_size = _queue_arw_deq_q_io_deq_bits_size;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_ar_bits_burst = _queue_arw_deq_q_io_deq_bits_burst;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_ar_bits_lock = _queue_arw_deq_q_io_deq_bits_lock;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_ar_bits_cache = _queue_arw_deq_q_io_deq_bits_cache;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_ar_bits_prot = _queue_arw_deq_q_io_deq_bits_prot;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_ar_bits_qos = _queue_arw_deq_q_io_deq_bits_qos;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_ar_bits_echo_tl_state_size = _queue_arw_deq_q_io_deq_bits_echo_tl_state_size;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_ar_bits_echo_tl_state_source = _queue_arw_deq_q_io_deq_bits_echo_tl_state_source;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, src/main/scala/chisel3/util/Queue.scala:200:21
  assign auto_out_r_ready = nodeOut_r_ready;	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:96:9, :220:33
endmodule

