// Generated by CIRCT firtool-1.135.0
module Trigger3_Tdata1Module(	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala:46:16
  input         clock,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala:46:16
                reset,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala:46:16
                w_wen,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:17:13
  input  [63:0] w_wdata,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:17:13
  output [63:0] rdata,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:20:17
  input         canWriteDmode,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala:350:25
                chainable	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala:351:21
);

  reg  [3:0]  reg_TYPE;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53
  reg         reg_DMODE;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53
  reg  [58:0] reg_DATA;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53
  wire        dmode = w_wdata[59] & canWriteDmode;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundle.scala:42:42, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala:142:35
  wire        _GEN = w_wdata[63:60] == 4'h6;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundle.scala:42:42, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRFields.scala:502:35
  always @(posedge clock or posedge reset) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala:46:16
    if (reset) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala:46:16
      reg_TYPE <= 4'hF;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundle.scala:52:15, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53
      reg_DMODE <= 1'h0;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53
      reg_DATA <= 59'h0;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundle.scala:52:15, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53
    end
    else if (w_wen) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:17:13
      reg_TYPE <= _GEN ? w_wdata[63:60] : 4'hF;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundle.scala:42:42, :52:15, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRFields.scala:247:12, :502:35, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala:230:23, :231:{10,31}
      reg_DMODE <= dmode;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala:142:35
      reg_DATA <=
        _GEN
          ? {34'h0,
             w_wdata[24:23],
             7'h0,
             w_wdata[15:12] == 4'h0 | w_wdata[15:12] == 4'h1 & dmode ? w_wdata[15:12] : 4'h0,
             w_wdata[11] & chainable,
             w_wdata[10:7] == 4'h0 | w_wdata[10:7] == 4'h2 | w_wdata[10:7] == 4'h3 ? w_wdata[10:7] : 4'h0,
             w_wdata[6],
             1'h0,
             w_wdata[4:0]}
          : 59'h0;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundle.scala:42:42, :52:15, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRFields.scala:247:12, :502:{35,51}, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala:142:35, :145:29, :149:56, :204:42, :245:{90,106,128,140}, :251:23, :252:38, :253:11, :279:23, :280:31, :281:11
    end
    else if (w_wen & _GEN)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRFields.scala:502:35, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:54:15
      reg_TYPE <= w_wdata[63:60];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundle.scala:42:42, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala:46:16
    `ifdef FIRRTL_BEFORE_INITIAL	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala:46:16
      `FIRRTL_BEFORE_INITIAL	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala:46:16
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala:46:16
      if (reset) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala:46:16
        reg_TYPE = 4'hF;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundle.scala:52:15, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53
        reg_DMODE = 1'h0;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53
        reg_DATA = 59'h0;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundle.scala:52:15, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala:46:16
      `FIRRTL_AFTER_INITIAL	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala:46:16
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign rdata = {reg_TYPE, reg_DMODE, reg_DATA};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53, :48:24, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/DebugLevel.scala:46:16
endmodule

