// Generated by CIRCT firtool-1.135.0
module UIntExtractor_24_000000000000111111010101_reference(	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/UIntUtils.scala:50:7
  input  [8:0]  io_in,	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/UIntUtils.scala:70:14
  output [23:0] io_out	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/UIntUtils.scala:70:14
);

  assign io_out = {12'h0, io_in[8:3], 1'h0, io_in[2], 1'h0, io_in[1], 1'h0, io_in[0]};	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/UIntUtils.scala:50:7, :75:32, :77:37, :79:20
endmodule

