// Generated by CIRCT firtool-1.135.0
module VSatpModule_reference(	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:196:26
  input         clock,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:196:26
                reset,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:196:26
                w_wen,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:17:13
  input  [63:0] w_wdata,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:17:13
  output [63:0] rdata,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:20:17
  output [3:0]  regOut_MODE,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:22:18
  output [15:0] regOut_ASID,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:22:18
  output [43:0] regOut_PPN,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:22:18
  input         v,	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:317:13
  input  [3:0]  hgatp_MODE	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:318:17
);

  reg  [3:0]  reg_MODE;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53
  reg  [15:0] reg_ASID;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53
  reg  [43:0] reg_PPN;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53
  wire        _GEN = w_wdata[63:60] == 4'h0 | w_wdata[63:60] == 4'h8 | w_wdata[63:60] == 4'h9;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundle.scala:42:42, :52:15, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRFields.scala:502:{35,51}
  wire        _GEN_0 = w_wen & _GEN;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRFields.scala:502:51, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:54:15
  wire [43:0] effectivePPNMask =
    (hgatp_MODE == 4'h0 ? 44'hFFFFFFFFF : 44'h0) | (hgatp_MODE == 4'h8 ? 44'h1FFFFFFF : 44'h0)
    | (hgatp_MODE == 4'h9 ? 44'h3FFFFFFFFF : 44'h0);	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundle.scala:52:15, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRFields.scala:502:35, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:202:33, :203:19, :204:19, :205:19, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/BitUtils.scala:104:41
  wire        _GEN_1 = w_wen & ~v & ~_GEN;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRFields.scala:502:51, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:218:{20,23,26,29}
  always @(posedge clock or posedge reset) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:196:26
    if (reset) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:196:26
      reg_MODE <= 4'h0;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundle.scala:52:15, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53
      reg_ASID <= 16'h0;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundle.scala:52:15, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53
      reg_PPN <= 44'h0;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53
    end
    else begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:196:26
      if (_GEN_0 | _GEN_1 & _GEN_0)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:54:{15,90}, :55:13, :61:13, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:215:37, :216:11, :218:{20,26,50}, :222:11
        reg_MODE <= w_wdata[63:60];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundle.scala:42:42, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53
      if (_GEN_0 | _GEN_1)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:54:15, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:215:37, :216:11, :218:{20,26,50}, :220:16, :222:11
        reg_ASID <= w_wdata[59:44];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundle.scala:42:42, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53
      if (_GEN_0)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:54:15
        reg_PPN <= w_wdata[43:0] & effectivePPNMask;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundle.scala:42:42, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRFields.scala:364:17, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:202:33
      else if (_GEN_1)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:218:{20,26}
        reg_PPN <= w_wdata[43:0] & effectivePPNMask;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundle.scala:42:42, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRFields.scala:364:17, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:202:33
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:196:26
    `ifdef FIRRTL_BEFORE_INITIAL	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:196:26
      `FIRRTL_BEFORE_INITIAL	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:196:26
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:196:26
      if (reset) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:196:26
        reg_MODE = 4'h0;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundle.scala:52:15, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53
        reg_ASID = 16'h0;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRBundle.scala:52:15, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53
        reg_PPN = 44'h0;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:196:26
      `FIRRTL_AFTER_INITIAL	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:196:26
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign rdata = {reg_MODE, reg_ASID, reg_PPN};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53, :48:24, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:196:26
  assign regOut_MODE = reg_MODE;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:196:26
  assign regOut_ASID = reg_ASID;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:196:26
  assign regOut_PPN = reg_PPN;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/VirtualSupervisorLevel.scala:196:26
endmodule

