`ifdef BIANCO_DIFFTEST
// Generated by CIRCT firtool-1.135.0
`ifndef layers_DCache_Verification_Assert	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala:886:7
  `define layers_DCache_Verification_Assert
  `include "layers-DCache-Verification.sv"	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala:886:7
  `include "layers-BankedDataArray-Verification-Assert.sv"	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala:886:7
  `include "layers-BloomFilter-Verification-Assert.sv"	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala:886:7
  `include "layers-CounterFilter-Verification-Assert.sv"	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala:886:7
  `include "layers-LoadPipe-Verification-Assert.sv"	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala:886:7
  `include "layers-MainPipe-Verification-Assert.sv"	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala:886:7
  `include "layers-MissQueue-Verification-Assert.sv"	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala:886:7
  `include "layers-ProbeQueue-Verification-Assert.sv"	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala:886:7
  `include "layers-WritebackQueue-Verification-Assert.sv"	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala:886:7
  bind DCache DCache_Verification_Assert verification_assert ();
`endif // not def layers_DCache_Verification_Assert
`endif // BIANCO_DIFFTEST
