`ifdef BIANCO_DIFFTEST
// Generated by CIRCT firtool-1.135.0
`ifndef layers_VSSplitBufferImp_Verification_Assert	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/vector/VSplit.scala:465:7
  `define layers_VSSplitBufferImp_Verification_Assert
  `include "layers-VSSplitBufferImp-Verification.sv"	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/vector/VSplit.scala:465:7
  bind VSSplitBufferImp_reference VSSplitBufferImp_Verification_Assert verification_assert ();
`endif // not def layers_VSSplitBufferImp_Verification_Assert
`endif // BIANCO_DIFFTEST
