`ifdef BIANCO_DIFFTEST
// Generated by CIRCT firtool-1.135.0
`ifndef layers_JtagTapController_Verification_Assert	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/jtag/JtagTap.scala:59:7
  `define layers_JtagTapController_Verification_Assert
  `include "layers-JtagTapController-Verification.sv"	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/jtag/JtagTap.scala:59:7
  `include "layers-CaptureUpdateChain_2-Verification-Assert.sv"	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/jtag/JtagTap.scala:59:7
`endif // not def layers_JtagTapController_Verification_Assert
`endif // BIANCO_DIFFTEST
