`ifdef BIANCO_DIFFTEST
// Generated by CIRCT firtool-1.135.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module MStatusModule_Verification_Assert_reference();	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala:599:11
  `ifndef SYNTHESIS	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala:594:11
    always @(posedge MStatusModule.clock) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala:568:7, :594:11
      if (MStatusModule._layer_probe & ~MStatusModule.reset & MStatusModule.reg_FS_0 == 2'h0) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala:568:7, :593:27, :594:{11,19}
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala:594:11
          $error("Assertion failed: The [m|s]status.FS should not be Off when set dirty, please check decode\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala:594:11
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala:594:11
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala:594:11
      end
      if (MStatusModule._layer_probe_0 & ~MStatusModule.reset & MStatusModule.reg_VS_0 == 2'h0) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/CSRModule.scala:24:53, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala:568:7, :594:{11,19}, :598:40, :599:{11,19}
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala:599:11
          $error("Assertion failed: The [m|s]status.VS should not be Off when set dirty, please check decode\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala:599:11
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala:599:11
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/fu/NewCSR/MachineLevel.scala:599:11
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule

`endif // BIANCO_DIFFTEST
