`ifdef BIANCO_DIFFTEST
// Generated by CIRCT firtool-1.135.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module Sbuffer_Verification_Assert_reference();	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:974:15
  `ifndef SYNTHESIS	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:279:9
    wire [3:0]       _GEN =
      {{Sbuffer.stateVec_3_state_valid_0},
       {Sbuffer.stateVec_2_state_valid_0},
       {Sbuffer.stateVec_1_state_valid_0},
       {Sbuffer.stateVec_0_state_valid_0}};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:76:53, :221:25
    wire [3:0]       _GEN_0 =
      {{Sbuffer.stateVec_3_state_inflight_0},
       {Sbuffer.stateVec_2_state_inflight_0},
       {Sbuffer.stateVec_1_state_inflight_0},
       {Sbuffer.stateVec_0_state_inflight_0}};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:76:53, :221:25
    wire [3:0]       _GEN_1 =
      {{Sbuffer.stateVec_3_w_sameblock_inflight_0},
       {Sbuffer.stateVec_2_w_sameblock_inflight_0},
       {Sbuffer.stateVec_1_w_sameblock_inflight_0},
       {Sbuffer.stateVec_0_w_sameblock_inflight_0}};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:76:53, :221:25
    wire [1:0]       evenInsertIdx = {Sbuffer.stateVec_0_state_valid_0, 1'h0};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:221:25, :359:26
    wire [1:0]       oddInsertIdx = {Sbuffer.stateVec_1_state_valid_0, 1'h1};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:221:25, :360:25, :458:11
    wire             _GEN_2 = Sbuffer.accessValid & ~Sbuffer.canMerge_0;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:481:31, :488:24, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/ParallelMux.scala:36:53
    wire             _GEN_3 = Sbuffer.accessValid_1 & ~Sbuffer.canMerge_1;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:481:31, :488:24, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/ParallelMux.scala:36:53
    wire [3:0][41:0] _GEN_4 = {{Sbuffer.ptag_3_0}, {Sbuffer.ptag_2_0}, {Sbuffer.ptag_1_0}, {Sbuffer.ptag_0_0}};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:215:17, :590:53
    wire [41:0]      _GEN_5 = _GEN_4[Sbuffer.sbuffer_out_s0_evictionIdx];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:590:53, :629:39
    wire             _GEN_6 = _GEN_2 & ~Sbuffer.reset;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:190:7, :279:9, :488:24
    wire             _GEN_7 = _GEN_3 & ~Sbuffer.reset;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:190:7, :279:9, :488:24
    wire [2:0]       _GEN_8 =
      {1'h0, {1'h0, Sbuffer.mergeMask_0_0} + {1'h0, Sbuffer.mergeMask_0_1}}
      + {1'h0, {1'h0, Sbuffer.mergeMask_0_2} + {1'h0, Sbuffer.mergeMask_0_3}};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:326:23, :335:22
    wire [2:0]       _GEN_9 =
      {1'h0, {1'h0, Sbuffer.mergeMask_1_0} + {1'h0, Sbuffer.mergeMask_1_1}}
      + {1'h0, {1'h0, Sbuffer.mergeMask_1_2} + {1'h0, Sbuffer.mergeMask_1_3}};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:326:23, :335:22
    wire [2:0]       _GEN_10 =
      {1'h0, {1'h0, Sbuffer._layer_probe} + {1'h0, Sbuffer._layer_probe_0}}
      + {1'h0, {1'h0, Sbuffer._layer_probe_1} + {1'h0, Sbuffer._layer_probe_2}};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:479:23
    wire [2:0]       _sameBlockInflightMask_T_9 =
      {1'h0, {1'h0, Sbuffer._sameBlockInflightMask_T} + {1'h0, Sbuffer._sameBlockInflightMask_T_1}}
      + {1'h0, {1'h0, Sbuffer._sameBlockInflightMask_T_2} + {1'h0, Sbuffer._sameBlockInflightMask_T_3}};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:594:54, :595:22
    wire [2:0]       _GEN_11 =
      {1'h0, {1'h0, Sbuffer._layer_probe_3} + {1'h0, Sbuffer._layer_probe_4}}
      + {1'h0, {1'h0, Sbuffer._layer_probe_5} + {1'h0, Sbuffer._layer_probe_6}};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:479:23
    wire [2:0]       _sameBlockInflightMask_T_23 =
      {1'h0, {1'h0, Sbuffer._sameBlockInflightMask_T_14} + {1'h0, Sbuffer._sameBlockInflightMask_T_15}}
      + {1'h0, {1'h0, Sbuffer._sameBlockInflightMask_T_16} + {1'h0, Sbuffer._sameBlockInflightMask_T_17}};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:594:54, :595:22
    always @(posedge Sbuffer.clock) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:190:7, :279:9
      if (~Sbuffer.reset
          & (|{Sbuffer.candidateVec_3, Sbuffer.candidateVec_2, Sbuffer.candidateVec_1, Sbuffer.candidateVec_0})
          & ~(_GEN[Sbuffer.replaceAlgoIdx] & ~_GEN_0[Sbuffer.replaceAlgoIdx] & ~_GEN_1[Sbuffer.replaceAlgoIdx])) begin	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/util/Replacement.scala:306:47, :308:13, :312:53, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:76:{50,53,69,72}, :190:7, :277:39, :279:{9,25,32,36}
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:279:9
          $error("Assertion failed: we have way to select, but replace algo selects invalid way\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:279:9
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:279:9
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:279:9
      end
      if (~Sbuffer.reset & (|(_GEN_8[2:1])) & Sbuffer._perfEvents_T_7 & Sbuffer.io_in_req_0_bits_vecValid) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:190:7, :194:14, :279:9, :335:{11,22,44,50,71}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:335:11
          $error("Assertion failed at Sbuffer.scala:335\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:335:11
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:335:11
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:335:11
      end
      if (~Sbuffer.reset & (|(_GEN_9[2:1])) & Sbuffer._perfEvents_T_8 & Sbuffer.io_in_req_1_bits_vecValid) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:190:7, :194:14, :279:9, :335:{11,22,44,50,71}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:335:11
          $error("Assertion failed at Sbuffer.scala:335\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:335:11
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:335:11
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:335:11
      end
      if (~Sbuffer.reset & (|(_GEN_10[2:1])) & Sbuffer._perfEvents_T_7 & Sbuffer.io_in_req_0_bits_vecValid) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:190:7, :194:14, :279:9, :479:{11,23,35,42,53}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:479:11
          $error("Assertion failed at Sbuffer.scala:479\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:479:11
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:479:11
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:479:11
      end
      if (Sbuffer.accessValid & Sbuffer.canMerge_0 & ~Sbuffer.reset & 4'h1
          << Sbuffer.mergeIdx_0 != Sbuffer.mergeVec_0) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:190:7, :279:9, :329:34, :458:{11,31}, :481:31, :488:24, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/ParallelMux.scala:36:53, src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/chisel3/util/OneHot.scala:58:35
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:458:11
          $error("Assertion failed at Sbuffer.scala:458\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:458:11
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:458:11
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:458:11
      end
      if (_GEN_6 & 4'h1 << Sbuffer.insertIdx != Sbuffer.firstInsertVec) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:374:27, :433:{11,32}, :488:24, src/main/scala/chisel3/util/OneHot.scala:32:10, :58:35
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:433:11
          $error("Assertion failed at Sbuffer.scala:433\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:433:11
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:433:11
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:433:11
      end
      if (_GEN_2 & ~Sbuffer.reset & (|(_sameBlockInflightMask_T_9[2:1]))) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:190:7, :488:24, :595:{11,12,22,29}
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:595:11
          $error("Assertion failed at Sbuffer.scala:595\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:595:11
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:595:11
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:595:11
      end
      if (_GEN_6 & (Sbuffer.enbufferSelReg_0 ? evenInsertIdx : oddInsertIdx) != Sbuffer.insertIdx) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:359:26, :360:25, :364:31, :369:27, :488:24, :494:{15,32}, src/main/scala/chisel3/util/OneHot.scala:32:10
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:494:15
          $error("Assertion failed at Sbuffer.scala:494\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:494:15
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:494:15
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:494:15
      end
      if (~Sbuffer.reset & (|(_GEN_11[2:1])) & Sbuffer._perfEvents_T_8 & Sbuffer.io_in_req_1_bits_vecValid) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:190:7, :194:14, :279:9, :479:{11,23,35,42,53}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:479:11
          $error("Assertion failed at Sbuffer.scala:479\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:479:11
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:479:11
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:479:11
      end
      if (Sbuffer.accessValid_1 & Sbuffer.canMerge_1 & ~Sbuffer.reset & 4'h1
          << Sbuffer.mergeIdx_1 != Sbuffer.mergeVec_1) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:190:7, :279:9, :329:34, :458:{11,31}, :481:31, :488:24, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/ParallelMux.scala:36:53, src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/chisel3/util/OneHot.scala:58:35
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:458:11
          $error("Assertion failed at Sbuffer.scala:458\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:458:11
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:458:11
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:458:11
      end
      if (_GEN_7 & 4'h1 << Sbuffer.insertIdx_1 != Sbuffer.secondInsertVec) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:375:28, :433:{11,32}, :488:24, src/main/scala/chisel3/util/OneHot.scala:32:10, :58:35
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:433:11
          $error("Assertion failed at Sbuffer.scala:433\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:433:11
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:433:11
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:433:11
      end
      if (_GEN_3 & ~Sbuffer.reset & (|(_sameBlockInflightMask_T_23[2:1]))) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:190:7, :488:24, :595:{11,12,22,29}
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:595:11
          $error("Assertion failed at Sbuffer.scala:595\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:595:11
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:595:11
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:595:11
      end
      if (_GEN_7
          & ((Sbuffer.sameTag ? Sbuffer.enbufferSelReg_0 : Sbuffer._secondCanInsert_T_1)
               ? evenInsertIdx
               : oddInsertIdx) != Sbuffer.insertIdx_1) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:322:117, :359:26, :360:25, :364:31, :369:27, :370:28, :372:{8,9}, :488:24, :494:{15,32}, src/main/scala/chisel3/util/OneHot.scala:32:10
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:494:15
          $error("Assertion failed at Sbuffer.scala:494\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:494:15
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:494:15
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:494:15
      end
      if (~Sbuffer.reset & _GEN[Sbuffer.sbuffer_out_s0_evictionIdx] & ~_GEN_0[Sbuffer.sbuffer_out_s0_evictionIdx]
          & ~_GEN_1[Sbuffer.sbuffer_out_s0_evictionIdx]
          & (|{Sbuffer.stateVec_0_state_inflight_0 & _GEN_5 == Sbuffer.ptag_0_0,
               Sbuffer.stateVec_1_state_inflight_0 & _GEN_5 == Sbuffer.ptag_1_0,
               Sbuffer.stateVec_2_state_inflight_0 & _GEN_5 == Sbuffer.ptag_2_0,
               Sbuffer.stateVec_3_state_inflight_0 & _GEN_5 == Sbuffer.ptag_3_0})) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:76:{50,53,69,72}, :190:7, :215:17, :221:25, :279:9, :590:{9,40,53,67}, :629:39, :642:9, :643:65
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:642:9
          $error("Assertion failed at Sbuffer.scala:642\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:642:9
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:642:9
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:642:9
      end
      if (Sbuffer.io_dcache_main_pipe_hit_resp_valid & ~Sbuffer.reset & ~_GEN_0[Sbuffer._layer_probe_7]) begin	// <stdin>:5436935:60, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:76:53, :190:7, :194:14, :279:9, :720:{13,54}
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:720:13
          $error("Assertion failed at Sbuffer.scala:720\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:720:13
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:720:13
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:720:13
      end
      if (Sbuffer.io_dcache_replay_resp_valid & ~Sbuffer.reset & ~_GEN_0[Sbuffer._layer_probe_8]) begin	// <stdin>:5437022:53, home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:76:53, :190:7, :194:14, :279:9, :752:{11,52}
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:752:11
          $error("Assertion failed at Sbuffer.scala:752\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:752:11
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:752:11
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:752:11
      end
      if (~Sbuffer.isVSLine_0 & Sbuffer.io_diffStore_cacheableStore_0_bits_wline & ~Sbuffer.reset
          & ~(~Sbuffer.storeCommitValid_0 | Sbuffer.io_diffStore_cacheableStore_0_bits_data == 128'h0)) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:190:7, :194:14, :279:9, :932:55, :950:81, :964:23, :969:28, :974:{15,16,34,45}
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:974:15
          $error("Assertion failed: wline only supports whole zero write now\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:974:15
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:974:15
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:974:15
      end
      if (~Sbuffer.isVSLine_1_0 & Sbuffer.io_diffStore_cacheableStore_1_bits_wline & ~Sbuffer.reset
          & ~(~Sbuffer.storeCommitValid_1_0 | Sbuffer.io_diffStore_cacheableStore_1_bits_data == 128'h0)) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:190:7, :194:14, :279:9, :932:55, :950:81, :964:23, :969:28, :974:{15,16,34,45}
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:974:15
          $error("Assertion failed: wline only supports whole zero write now\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:974:15
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:974:15
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/sbuffer/Sbuffer.scala:974:15
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule

`endif // BIANCO_DIFFTEST
