`ifdef BIANCO_DIFFTEST
// Generated by CIRCT firtool-1.135.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module StoreUnitS1_Verification_Assert();	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/pipeline/NewStoreUnit.scala:398:9
  `ifndef SYNTHESIS	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/pipeline/NewStoreUnit.scala:356:9
    always @(posedge StoreUnitS1.clock) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/pipeline/NewStoreUnit.scala:262:7, :356:9
      if (~StoreUnitS1.reset & StoreUnitS1.io_pipeIn_valid & ~StoreUnitS1.io_tlbResp_valid) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/pipeline/NewStoreUnit.scala:262:7, :266:14, :356:{9,25,28}, :1022:12
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/pipeline/NewStoreUnit.scala:356:9
          $error("Assertion failed at NewStoreUnit.scala:356\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/pipeline/NewStoreUnit.scala:356:9
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/pipeline/NewStoreUnit.scala:356:9
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/pipeline/NewStoreUnit.scala:356:9
      end
      if (~StoreUnitS1.reset & StoreUnitS1.unalignTailInjectValid
          & (StoreUnitS1.io_pipeIn_bits_accessType_isCbo | StoreUnitS1.io_pipeIn_bits_accessType_isCboNoZero)) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/pipeline/NewStoreUnit.scala:262:7, :356:9, :386:37, :398:{9,35,45}, :1022:12
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/pipeline/NewStoreUnit.scala:398:9
          $error("Assertion failed at NewStoreUnit.scala:398\n");	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/pipeline/NewStoreUnit.scala:398:9
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/pipeline/NewStoreUnit.scala:398:9
          $fatal;	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/pipeline/NewStoreUnit.scala:398:9
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule

`endif // BIANCO_DIFFTEST
