`ifdef BIANCO_DIFFTEST
// Generated by CIRCT firtool-1.135.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module VLMergeBufferImp_Verification_Assert_reference();	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
  `ifndef SYNTHESIS	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
    wire [15:0][4:0] _GEN =
      {{VLMergeBufferImp.entries_15_flowNum_0},
       {VLMergeBufferImp.entries_14_flowNum_0},
       {VLMergeBufferImp.entries_13_flowNum_0},
       {VLMergeBufferImp.entries_12_flowNum_0},
       {VLMergeBufferImp.entries_11_flowNum_0},
       {VLMergeBufferImp.entries_10_flowNum_0},
       {VLMergeBufferImp.entries_9_flowNum_0},
       {VLMergeBufferImp.entries_8_flowNum_0},
       {VLMergeBufferImp.entries_7_flowNum_0},
       {VLMergeBufferImp.entries_6_flowNum_0},
       {VLMergeBufferImp.entries_5_flowNum_0},
       {VLMergeBufferImp.entries_4_flowNum_0},
       {VLMergeBufferImp.entries_3_flowNum_0},
       {VLMergeBufferImp.entries_2_flowNum_0},
       {VLMergeBufferImp.entries_1_flowNum_0},
       {VLMergeBufferImp.entries_0_flowNum_0}};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala:159:25, :329:44
    wire [4:0]       _GEN_0 = _GEN[VLMergeBufferImp.latchWbIndex_0];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala:314:68, :329:44
    wire [15:0]      _GEN_1 =
      {{VLMergeBufferImp.allocated_15_0},
       {VLMergeBufferImp.allocated_14_0},
       {VLMergeBufferImp.allocated_13_0},
       {VLMergeBufferImp.allocated_12_0},
       {VLMergeBufferImp.allocated_11_0},
       {VLMergeBufferImp.allocated_10_0},
       {VLMergeBufferImp.allocated_9_0},
       {VLMergeBufferImp.allocated_8_0},
       {VLMergeBufferImp.allocated_7_0},
       {VLMergeBufferImp.allocated_6_0},
       {VLMergeBufferImp.allocated_5_0},
       {VLMergeBufferImp.allocated_4_0},
       {VLMergeBufferImp.allocated_3_0},
       {VLMergeBufferImp.allocated_2_0},
       {VLMergeBufferImp.allocated_1_0},
       {VLMergeBufferImp.allocated_0_0}};	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala:161:29, :330:13
    wire [4:0]       _GEN_2 = _GEN[VLMergeBufferImp.latchWbIndex_1_0];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala:314:68, :329:44
    wire [4:0]       _GEN_3 = _GEN[VLMergeBufferImp.latchWbIndex_2_0];	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala:314:68, :329:44
    always @(posedge VLMergeBufferImp.clock) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala:393:7, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
      if (_GEN_0 - {3'h0, VLMergeBufferImp.latchFlowNum_0} > _GEN_0 & VLMergeBufferImp.latchWbValid_0
          & VLMergeBufferImp._layer_probe & ~VLMergeBufferImp.reset) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala:313:66, :315:69, :317:26, :329:{44,59,92,108}, :393:7, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
          $error("Assertion failed at LogUtils.scala:132\n");	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
          $fatal;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
      end
      if (~_GEN_1[VLMergeBufferImp.latchWbIndex_0] & VLMergeBufferImp.latchWbValid_0 & ~VLMergeBufferImp.reset) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala:313:66, :314:68, :330:{13,38}, :393:7, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
          $error("Assertion failed at LogUtils.scala:132\n");	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
          $fatal;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
      end
      if (_GEN_2 - {3'h0, VLMergeBufferImp.latchFlowNum_1_0} > _GEN_2 & VLMergeBufferImp.latchWbValid_1_0
          & VLMergeBufferImp._layer_probe_0 & ~VLMergeBufferImp.reset) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala:313:66, :315:69, :317:26, :329:{44,59,92,108}, :393:7, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
          $error("Assertion failed at LogUtils.scala:132\n");	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
          $fatal;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
      end
      if (~_GEN_1[VLMergeBufferImp.latchWbIndex_1_0] & VLMergeBufferImp.latchWbValid_1_0
          & ~VLMergeBufferImp.reset) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala:313:66, :314:68, :330:{13,38}, :393:7, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
          $error("Assertion failed at LogUtils.scala:132\n");	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
          $fatal;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
      end
      if (_GEN_3 - {3'h0, VLMergeBufferImp.latchFlowNum_2_0} > _GEN_3 & VLMergeBufferImp.latchWbValid_2_0
          & VLMergeBufferImp._layer_probe_1 & ~VLMergeBufferImp.reset) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala:313:66, :315:69, :317:26, :329:{44,59,92,108}, :393:7, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
          $error("Assertion failed at LogUtils.scala:132\n");	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
          $fatal;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
      end
      if (~_GEN_1[VLMergeBufferImp.latchWbIndex_2_0] & VLMergeBufferImp.latchWbValid_2_0
          & ~VLMergeBufferImp.reset) begin	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/vector/VMergeBuffer.scala:313:66, :314:68, :330:{13,38}, :393:7, home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
        if (`ASSERT_VERBOSE_COND_)	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
          $error("Assertion failed at LogUtils.scala:132\n");	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
        if (`STOP_COND_)	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
          $fatal;	// home/davide/gitdir/bianco/XiangShan/utility/src/main/scala/utility/LogUtils.scala:132:17
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule

`endif // BIANCO_DIFFTEST
