`ifdef BIANCO_DIFFTEST
// Generated by CIRCT firtool-1.135.0
module AXI4UserYanker_4_Verification_reference();	// home/davide/gitdir/bianco_ci/bianco/XiangShan/rocket-chip/src/main/scala/amba/axi4/UserYanker.scala:95:14
endmodule

`endif // BIANCO_DIFFTEST
