`ifdef BIANCO_DIFFTEST
// Generated by CIRCT firtool-1.135.0
module CounterFilter_Verification_reference();	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/prefetch/FDP.scala:111:11
endmodule

`endif // BIANCO_DIFFTEST
