`ifdef BIANCO_DIFFTEST
// Generated by CIRCT firtool-1.135.0
`ifndef layers_AXI4DMAC_Verification	// home/davide/gitdir/bianco_ci/bianco/XiangShan/src/main/scala/device/AXI4DMAC.scala:48:34
  `define layers_AXI4DMAC_Verification
  bind AXI4DMAC_reference AXI4DMAC_Verification verification ();
`endif // not def layers_AXI4DMAC_Verification
`endif // BIANCO_DIFFTEST
