`ifdef BIANCO_DIFFTEST
// Generated by CIRCT firtool-1.135.0
`ifndef layers_TLXbar_5_Verification	// home/davide/gitdir/bianco/XiangShan/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  `define layers_TLXbar_5_Verification
  bind TLXbar_5_reference TLXbar_5_Verification verification ();
`endif // not def layers_TLXbar_5_Verification
`endif // BIANCO_DIFFTEST
