`ifdef BIANCO_DIFFTEST
// Generated by CIRCT firtool-1.135.0
`ifndef layers_LqMaskModule_Verification	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LoadQueueData.scala:210:7
  `define layers_LqMaskModule_Verification
  bind LqMaskModule LqMaskModule_Verification verification ();
`endif // not def layers_LqMaskModule_Verification
`endif // BIANCO_DIFFTEST
