`ifdef BIANCO_DIFFTEST
// Generated by CIRCT firtool-1.135.0
`ifndef layers_SinkC_Verification	// home/davide/gitdir/bianco/XiangShan/XSCache/src/main/scala/coupledL2/SinkC.scala:35:7
  `define layers_SinkC_Verification
  bind SinkC SinkC_Verification verification ();
`endif // not def layers_SinkC_Verification
`endif // BIANCO_DIFFTEST
