`ifdef BIANCO_DIFFTEST
// Generated by CIRCT firtool-1.135.0
`ifndef layers_OldestArbiter_28_Verification	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/datapath/RFReadArbiter.scala:47:7
  `define layers_OldestArbiter_28_Verification
  bind OldestArbiter_28_reference OldestArbiter_28_Verification verification ();
`endif // not def layers_OldestArbiter_28_Verification
`endif // BIANCO_DIFFTEST
