`ifdef BIANCO_DIFFTEST
// Generated by CIRCT firtool-1.135.0
`ifndef layers_HuanCun_Verification	// home/davide/gitdir/bianco/XiangShan/huancun/src/main/scala/huancun/HuanCun.scala:253:9
  `define layers_HuanCun_Verification
  `include "layers-Slice_2-Verification.sv"	// home/davide/gitdir/bianco/XiangShan/huancun/src/main/scala/huancun/HuanCun.scala:253:9
`endif // not def layers_HuanCun_Verification
`endif // BIANCO_DIFFTEST
