`ifdef BIANCO_DIFFTEST
// Generated by CIRCT firtool-1.135.0
`ifndef layers_VirtualLoadQueue_Verification	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/VirtualLoadQueue.scala:34:7
  `define layers_VirtualLoadQueue_Verification
  bind VirtualLoadQueue_reference VirtualLoadQueue_Verification verification ();
`endif // not def layers_VirtualLoadQueue_Verification
`endif // BIANCO_DIFFTEST
