`ifdef BIANCO_DIFFTEST
// Generated by CIRCT firtool-1.135.0
`ifndef layers_WriteBuffer_12_Verification	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/WriteBuffer.scala:45:7
  `define layers_WriteBuffer_12_Verification
  bind WriteBuffer_12_reference WriteBuffer_12_Verification verification ();
`endif // not def layers_WriteBuffer_12_Verification
`endif // BIANCO_DIFFTEST
