`ifdef BIANCO_DIFFTEST
// Generated by CIRCT firtool-1.135.0
`ifndef layers_OthersEntry_32_Verification	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/backend/issue/OthersEntry.scala:27:7
  `define layers_OthersEntry_32_Verification
  bind OthersEntry_32 OthersEntry_32_Verification verification ();
`endif // not def layers_OthersEntry_32_Verification
`endif // BIANCO_DIFFTEST
