`ifdef BIANCO_DIFFTEST
// Generated by CIRCT firtool-1.135.0
module LsqWrapper_Verification();	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/mem/lsqueue/LSQWrapper.scala:307:11
endmodule

`endif // BIANCO_DIFFTEST
