`ifdef BIANCO_DIFFTEST
// Generated by CIRCT firtool-1.135.0
module SourceB_Verification();	// home/davide/gitdir/bianco/XiangShan/XSCache/src/main/scala/coupledL2/SourceB.scala:97:11
endmodule

`endif // BIANCO_DIFFTEST
