`ifdef BIANCO_DIFFTEST
// Generated by CIRCT firtool-1.135.0
module Tage_Verification();	// home/davide/gitdir/bianco/XiangShan/src/main/scala/xiangshan/frontend/bpu/tage/Tage.scala:597:13
endmodule

`endif // BIANCO_DIFFTEST
